# -*- coding: utf-8 -*-
# Polish (pl) & Dutch (nl)

pl = {
    'nav.store': 'Sklep', 'nav.profile': 'Profil', 'nav.replays': 'Powtórki', 'nav.coins': 'Monety',
    'nav.language': 'Język', 'nav.bestStreak': 'Najlepsza seria', 'nav.online': 'Online', 'nav.connecting': 'Łączenie...',
    'game.title': 'FREE KICK LEGENDS', 'menu.quickPlay': 'SZYBKI MECZ', 'menu.quickPlaySub': 'MECZE ONLINE I OFFLINE',
    'menu.survivalMode': 'TRYB PRZETRWANIA', 'survival.threeLives': '3 ŻYCIA', 'survival.endlessStreak': 'Niekończąca się seria',
    'survival.best': 'Rekord', 'survival.streak': 'SERIA', 'survival.onlineAvailable': 'Dostępny pojedynek 1v1 online',
    'menu.wagerArena': 'ARENA ZAKŁADÓW', 'wager.betCoinsPot': 'Postaw monety • Zwycięzca bierze wszystko',
    'wager.onlineDuel': 'Pojedynek 1v1 na monety online', 'wager.duel': 'POJEDYNEK', 'wager.arena': 'Arena', 'wager.bet': 'Zakład',
    'wager.winnerTakes': 'Zwycięzca zgarnia', 'wager.prizePot': 'Pula nagród', 'menu.worldCup': 'MISTRZOSTWA ŚWIATA FIFA',
    'menu.tournamentFormat': 'Format turniejowy', 'menu.practice': 'TRENING', 'menu.practiceSub': 'Trening rzutów wolnych',
    'menu.shop': 'SKLEP', 'menu.onlineMultiplayer': 'Dostępny tryb wieloosobowy online',
    'profile.savedReplaysStats': 'POWTÓRKI I STATYSTYKI', 'replays.title': 'Zapisane powtórki',
    'common.coins': 'MONETY', 'common.coinsUpper': 'MONETY', 'common.online': 'ONLINE', 'common.offline': 'OFFLINE',
    'common.back': 'WSTECZ', 'common.backToMenu': 'Powrót do menu', 'common.active': 'AKTYWNY', 'common.done': 'GOTOWE',
    'common.close': 'ZAMKNIJ', 'common.gotIt': 'ROZUMIEM', 'common.cancel': 'Anuluj', 'common.continue': 'KONTYNUUJ',
    'common.exit': 'WYJDŹ', 'common.quit': 'WYJŚCIE', 'common.play': 'GRAJ', 'common.saved': 'ZAPISANO', 'common.goal': 'GOL',
    'common.goals': 'goli', 'common.pts': 'PKT', 'common.you': 'Ty', 'common.opponent': 'Przeciwnik',
    'common.watchAdCoins': 'Obejrzyj reklamę za +50 darmowych monet', 'currency.coins': 'MONETY',
    'btn.play': 'Graj teraz', 'btn.select': 'Wybierz', 'btn.confirm': 'Zatwierdź', 'btn.cancel': 'Anuluj',
    'btn.close': 'Zamknij', 'btn.back': 'Wstecz', 'btn.continue': 'Dalej', 'btn.nextMatch': 'Następny mecz',
    'btn.returnMenu': 'Menu główne', 'btn.equip': 'Załóż', 'btn.equipped': 'Założone', 'btn.unlock': 'Odblokuj',
    'btn.locked': 'Zablokowane', 'btn.saveReplay': 'Zapisz powtórkę', 'btn.save': 'ZAPISZ', 'btn.saved': 'ZAPISANO',
    'btn.skip': 'POMIŃ', 'btn.playAgain': 'Zagraj ponownie', 'btn.watchAd': 'Obejrzyj wideo (+50 monet)', 'btn.freeCoins': 'Darmowe monety',
    'hud.aim': 'Celowanie', 'hud.power': 'Siła', 'hud.curve': 'Podkręcenie', 'hud.kick': 'Strzał',
    'hud.stepAim': 'USTAW KĄT STRZAŁU', 'hud.stepPower': 'ZABLOKUJ SIŁĘ', 'hud.stepCurve': 'PODKRĘĆ PIŁKĘ',
    'hud.stepKick': 'WYKONAJ STRZAŁ', 'hud.shoot': 'STRZAŁ!', 'hud.tapToLock': 'DOTKNIJ, ABY ZABLOKOWAĆ',
    'hud.tapToKick': 'DOTKNIJ, ABY STRZELIĆ', 'hud.goal': 'GOL!', 'hud.saved': 'OBRONA!', 'hud.missed': 'PUDŁO!',
    'hud.wallBlocked': 'MUR ZABLOKOWAŁ!', 'hud.postHit': 'SŁUPEK!', 'hud.suddenDeath': 'ZŁOTY GOL',
    'hud.goldenGoal': 'ZŁOTY GOL', 'hud.penaltyShootout': 'RZUTY KARNE', 'hud.turn': 'Tura',
    'hud.yourTurn': 'TWOJA TURA', 'hud.oppTurn': 'TURA PRZECIWNIKA', 'hud.aiThinking': 'BOT MYŚLI...',
    'hud.aiAiming': 'BOT CELUJE...', 'hud.aiStriking': 'BOT STRZELA...', 'hud.timer': 'Czas',
    'hud.matchOver': 'KONIEC MECZU', 'hud.rematch': 'Rewanż', 'hud.exitMatch': 'Opuść mecz',
    'hud.resume': 'Wznów', 'hud.pause': 'Pauza', 'hud.yourTurnPenalty': 'TWÓJ RZUT KARNY',
    'hud.oppPenalty': 'PRZECIWNIK STRZELA KARNEGO...', 'hud.aiPenalty': 'BOT STRZELA KARNEGO...',
    'hud.playIn': 'KAMERA:', 'hud.ballTracking': 'ŚLEDZENIE PIŁKI', 'hud.behindGoal': 'ZA BRAMKĄ',
    'hud.meter': 'WSKAŹNIK', 'hud.aiGoalkeeper': 'BRAMKARZ BOT', 'hud.aiStriker': 'NAPASTNIK BOT',
    'hud.defenseSim': 'Symulacja obrony', 'hud.precisionFK': 'Precyzyjny rzut wolny', 'hud.aiming': 'CELOWANIE',
    'hud.holdToCharge': 'PRZYTRZYMAJ, ABY ZAŁADOWAĆ', 'hud.releaseToStrikeInstruction': 'PRZYTRZYMAJ SPACJĘ / EKRAN • PUŚĆ, ABY STRZELIĆ',
    'hud.weak': 'SŁABO', 'hud.sweetSpot': 'IDEALNIE', 'hud.max': 'MAX', 'hud.chargingPower': 'ŁADOWANIE SIŁY...',
    'hud.replay': 'POWTÓRKA', 'game.goal': 'GOL!', 'game.saved': 'OBRONA',
    'quickPlay.selectMode': 'Wybierz tryb meczu:', 'quickPlay.ranked': 'Rankingowy', 'quickPlay.vsAi': 'Vs Bot / Lokalnie',
    'country.selectTeams': 'WYBÓR DRUŻYN', 'country.nationalTeams': 'Reprezentacje narodowe', 'country.teamsAvailable': 'Dostępne drużyny',
    'country.tapToSelect': 'Dotknij, aby wybrać', 'country.myTeam': 'MOJA DRUŻYNA', 'country.opponent': 'PRZECIWNIK',
    'country.continueToMatch': 'PRZEJDŹ DO MECZU', 'search.countries': 'Szukaj kraju...', 'teamSelect.teams': 'Drużyny',
    'teamSelect.searchPlaceholder': 'Szukaj reprezentacji...', 'teamSelect.att': 'ATK', 'teamSelect.def': 'OBR',
    'team.selectNew': 'WYBIERZ NOWĄ DRUŻYNĘ', 'team.selectNewDesc': 'Wybieraj spośród 120 reprezentacji z całego świata',
    'online.matchTitle': 'MECZ ONLINE', 'online.matchSubtitle': 'Połącz się i wybierz reprezentację na żywo:',
    'online.createRoom': 'Stwórz prywatny pokój', 'online.joinRoom': 'Dołącz z kodem', 'online.joinRoomTitle': 'DOŁĄCZ DO POKOJU',
    'online.roomCode': 'Kod pokoju', 'online.copyCode': 'Kopiuj kod', 'online.codeCopied': 'Skopiowano!',
    'online.shareCode': 'Udostępnij ten 4-cyfrowy kod znajomemu:', 'online.enterCode': 'Wpisz 4-cyfrowy kod:',
    'online.findMatch': 'Szybki mecz online', 'online.searchingMatch': 'Szukanie rywala...', 'online.stillSearching': 'Wyszukiwanie graczy...',
    'online.retrySearch': 'Spróbuj ponownie', 'online.cancelSearch': 'Anuluj szukanie', 'online.cancelRoom': 'Anuluj pokój',
    'online.leaveRoom': 'Opuść pokój', 'online.inviteLink': 'Kopiuj link z zaproszeniem', 'online.linkCopied': 'Link skopiowany!',
    'online.lookingOpponent': 'Szukanie rywala na świecie...', 'online.pairingAuto': 'Łączenie z graczem...', 'online.ready': 'GOTOWY',
    'online.bothSelected': 'Oboje gotowi! Rozpoczęcie meczu...', 'online.selectTeamBelow': 'Wybierz drużynę poniżej:',
    'online.lockedIn': 'ZATWIERDZONE', 'online.selecting': 'Wybieranie...', 'online.choosing': 'Wybiera reprezentację...',
    'online.opponentLeft': 'Przeciwnik opuścił pokój', 'online.opponentLeftSub': 'Powrót do menu za chwilę...',
    'online.roomCreated': 'POKÓJ STWORZONY', 'online.room': 'Pokój', 'online.host': 'Gospodarz', 'online.guest': 'Gość',
    'online.firstTurn': 'Strzelasz pierwszy', 'online.secondTurn': 'Przeciwnik strzela pierwszy',
    'online.matchStartingIn': 'Mecz rozpocznie się za', 'online.kickoff': 'GWIZDEK!',
    'online.leaveMatchTitle': 'OPUŚCIĆ MECZ?', 'online.leaveMatchSub': 'Rozłączenie przyzna rywalowi walkower.',
    'online.leaveMatch': 'OPUŚĆ MECZ', 'online.leave': 'OPUŚĆ', 'online.returnToMenu': 'Do menu głównego',
    'online.returningToMenu': 'Powrót do menu...', 'online.sessionDisconnected': 'Rozłączono sesję',
    'online.yourCountry': 'TWOJA DRUŻYNA', 'online.oppCountry': 'DRUŻYNA PRZECIWNIKA',
    'online.waitingOpponent': 'Oczekiwanie na wybór przeciwnika...', 'online.waitingOpponentCode': 'Oczekiwanie na gracza z kodem...',
    'online.connectSub': 'Globalne serwery multiplayer 1v1', 'modal.matchmaking': 'Szukanie rywala...',
    'modal.matchmakingDesc': 'Przeszukiwanie serwerów globalnych', 'modal.searchingTime': 'Czas szukania',
    'modal.opponentFound': 'PRZECIWNIK ZNALEZIONY!', 'modal.connectingBot': 'Połączenie z botem za 30s...',
    'modal.quitMatchSub': 'Postęp w obecnym meczu zostanie utracony.', 'modal.forfeitMatchTitle': 'PODDAĆ MECZ?',
    'modal.forfeitMatchSub': 'Poddanie oznacza automatyczną porażkę.', 'modal.forfeit': 'PODDAJ',
    'match.opponentLeftTitle': 'PRZECIWNIK OPUŚCIŁ MECZ', 'match.opponentLeftDesc': 'Twój rywal się rozłączył.',
    'match.playAgainUnavailable': 'Rewanż niedostępny, ponieważ rywal wyszedł.',
    'match.waitingOpponent': 'Oczekiwanie na odpowiedź przeciwnika...', 'match.changeTeams': 'ZMIEŃ DRUŻYNY',
    'tournament.selectFormat': 'Wybierz format:', 'tournament.globalCup': 'Puchar Globalny', 'tournament.customCup': 'Własny Puchar',
    'tournament.inDevelopment': 'W BUDOWIE', 'tournament.onlineWorldCup': 'MISTRZOSTWA ŚWIATA ONLINE',
    'tournament.multiplayerWorldCup': 'Puchary Świata & Drabinki Pucharowe', 'tournament.knockoutBrackets': 'Drabinka na 16 drużyn',
    'tournament.knockoutBracketsSub': 'Turnieje pucharowe na żywo', 'tournament.globalLeaderboards': 'Globalne tabele sezonowe',
    'tournament.globalLeaderboardsSub': 'Zdobywaj punkty rankingowe i puchary', 'tournament.exclusiveUnlockables': 'Unikalne stroje i piłki mistrzowskie',
    'tournament.exclusiveUnlockablesSub': 'Wyjątkowe nagrody dla zwycięzców', 'tournament.playOfflineNow': 'GRAJ MŚ OFFLINE',
    'tournament.selectYourTeam': 'WYBIERZ DRUŻYNĘ', 'tournament.worldCupQualifiedSub': 'FIFA World Cup • 40 Zakwalifikowanych Krajów (Grupy A – J)',
    'tournament.searchCountry': 'Szukaj kraju lub grupy...', 'tournament.qualifiedNations': 'Zakwalifikowane kraje',
    'tournament.tapToSelect': 'Dotknij, aby wybrać', 'tournament.selected': 'WYBRANO', 'tournament.ovr': 'OVR',
    'tournament.randomGroupDraw': 'Losowanie grup na starcie', 'tournament.tapAnyCountryPrompt': 'DOTKNIJ KRAJU, ABY GO WYBRAĆ',
    'tournament.enterWorldCup': 'ROZPOCZNIJ MISTRZOSTWA (GRUPY A - J)', 'tournament.backToMenu': 'Do menu głównego',
    'tournament.forfeitMatch': 'PODDAJ MECZ', 'tournament.continue': 'PRZEJDŹ DO FAZY PUCHAROWEJ',
    'tournament.championTitle': '★ MISTRZOWIE ŚWIATA ★', 'tournament.worldChampions': 'MISTRZOWIE ŚWIATA',
    'tournament.winnerLiftsCup': 'Wzniosłeś Puchar Świata!', 'tournament.freeKickCup': 'Mistrzostwa Rzutów Wolnych',
    'tournament.roundOf16': '1/8 Finału', 'tournament.quarterFinals': 'Ćwierćfinał', 'tournament.semiFinal1': 'Półfinał 1',
    'tournament.semiFinal2': 'Półfinał 2', 'tournament.worldFinal': 'Finał Mistrzostw Świata', 'tournament.awaitingFinal': 'Oczekiwanie na finalistę',
    'tournament.fixture': 'Mecz', 'tournament.ft': 'KONIEC', 'tournament.tbd': 'DO USTALENIA', 'tournament.cancelTournament': 'Anuluj turniej',
    'practice.selectDrill': 'Wybierz ćwiczenie:', 'practice.freeKick': 'RZUT WOLNY',
    'practice.freeKickSub': 'Szybka gra • Mur i strzały w okienko', 'practice.instant': 'Natychmiast',
    'practice.penalty': 'RZUT KARNY', 'practice.penaltySub': '1v1 przeciwko bramkarzowi • Bez limitu czasu', 'practice.random': 'Losowo',
    'practice.exitTitle': 'OPUŚCIĆ TRENING?', 'practice.exitSub': 'Możesz wrócić do menu w każdej chwili.',
    'practice.exitButton': 'OPUŚĆ TRENING', 'survival.title': 'Arena Przetrwania',
    'survival.subtitle': '3 Życia • Nieskończone serie • Pojedynki', 'survival.arenaTitle': 'ARENA PRZETRWANIA',
    'survival.onlineSurvivalTitle': 'PRZETRWANIE 1V1 ONLINE',
    'survival.onlineSurvivalSubtitle': '3 Życia • Pojedynek 1v1 na żywo • Wyzwanie serii goli',
    'survival.selectGameMode': 'Wybierz tryb gry:', 'survival.offlineSurvivalBtn': 'PRZETRWANIE OFFLINE',
    'survival.onlineDuelBtn': 'POJEDYNEK 1V1 ONLINE', 'survival.rulesBtn': 'Zasady',
    'survival.rulesTitle': 'ZASADY PRZETRWANIA', 'survival.rulesSubtitle': 'Przestrzegaj tych 2 zasad, aby pobić rekord:',
    'survival.rule1Title': 'System 3 żyć',
    'survival.rule1Desc': 'Każdy gracz zaczyna z 3 sercami. Niecelny strzał lub obrona bramkarza odbiera 1 życie. Kto pierwszy straci życia, przegrywa!',
    'survival.rule2Title': 'Strzały na zmianę i zegar 100s',
    'survival.rule2Desc': 'Naprzemienne rzuty wolne z limitem 100 sekund. Trafiaj, by wydłużać serię goli!',
    'survival.backToRules': 'Powrót do zasad', 'survival.howItWorks': 'Jak to działa', 'survival.guideBadge': 'PRZEWODNIK PRZETRWANIA',
    'survival.livesRemaining': 'Pozostałe życia', 'survival.bestRecord': 'Rekord wszech czasów', 'survival.bestStreak': 'NAJLEPSZA SERIA',
    'survival.startRun': 'Rozpocznij próbę', 'survival.personalRecord': 'Rekord osobisty', 'survival.goalStreak': 'SERIA GOLI',
    'survival.goalsStreak': 'SERIA GOLI', 'survival.kicks': 'Strzały', 'survival.duel': 'POJEDYNEK PRZETRWANIA 1V1',
    'survival.duelSub': 'Pojedynek pucharowy online', 'survival.runEnded': 'KONIEC PRÓBY!',
    'survival.challengeComplete': 'Wyzwanie ukończone', 'survival.finalGoalsStreak': 'Ostateczna seria goli',
    'survival.challengeMode': 'Tryb wyzwania', 'survival.reviveExtraLife': 'ODRÓDŹ SIĘ (+1 ŻYCIE)',
    'survival.endSurvivalTitle': 'ZAKOŃCZYĆ PRZETRWANIE?', 'survival.endSurvival': 'ZAKOŃCZ', 'survival.endRun': 'ZAKOŃCZ PRÓBĘ',
    'survival.concludeSub': 'Mecz zostanie natychmiast zakończony.', 'survival.currentStreak': 'Obecna seria:',
    'wager.title': 'Areny Zakładów', 'wager.subtitle': 'Wybierz stawkę • Zwycięzca zgarnia całą pulę!',
    'wager.rookie': 'Arena Nowicjusza', 'wager.pro': 'Arena Pro', 'wager.champion': 'Arena Mistrza', 'wager.legend': 'Arena Legendy',
    'wager.entryFee': 'Wpisowe', 'wager.entry': 'WPISOWE', 'wager.prizePot': 'Pula nagród', 'wager.winPot': 'NAGRODA ZWYCIĘZCY',
    'wager.highRoller': 'Pojedynek o wysokie stawki', 'wager.bottomBanner': 'Odkrywaj areny • Wysokie stawki, podwójne wygrane!',
    'wager.tapToSelect': 'Dotknij, aby wybrać', 'wager.playWithCoins': 'Graj na monety', 'wager.needMoreCoins': 'Potrzebujesz więcej monet',
    'wager.forfeitWager': 'PODDAJ ZAKŁAD', 'wager.surrenderTitle': 'PODDAĆ ZAKŁAD?',
    'wager.surrenderSub': 'Poddanie zakładu spowoduje utratę postawionych monet:', 'wager.surrender': 'PODDAJ SIĘ', 'wager.victory': 'WYGRANY ZAKŁAD!',
    'wager.coinDuelResults': 'Wyniki pojedynku', 'wager.drawRefunded': 'REMIS • ZWROT WPISOWEGO',
    'wager.arenaPot': 'Pula areny', 'wager.netResult': 'Wynik netto',
    'wager.opponentLeft': 'Rywal rozłączył się z areny', 'wager.rematch': 'REWANŻ O STAWKĘ',
    'targetSmash.title': 'STRZELNICA DO CELU', 'targetSmash.arcadeBadge': 'NOWY TRYB ARCADE',
    'targetSmash.trickshotSubtitle': 'Cele & Podkręcone Strzały', 'targetSmash.selectStage': 'Poziom (1 - 10)',
    'targetSmash.unlocked': 'Odblokowano', 'targetSmash.stage': 'Poziom', 'targetSmash.objective': 'Cel',
    'targetSmash.highScore': 'Rekord', 'targetSmash.pts': 'PKT', 'targetSmash.distance': 'Dystans',
    'targetSmash.defendersWall': 'Mur obronny', 'targetSmash.players': 'Gracze', 'targetSmash.targetScore': 'Wymagany wynik',
    'targetSmash.targetRequired': 'Wymagane punkty', 'targetSmash.playStage': 'GRAJ POZIOM', 'targetSmash.stageLocked': 'POZIOM ZABLOKOWANY',
    'targetSmash.stageCleared': 'POZIOM ZALICZONY!', 'targetSmash.stageFailed': 'POZIOM NIEZALICZONY', 'targetSmash.finalScore': 'Wynik końcowy',
    'targetSmash.coinsReward': 'Nagroda w monetach', 'targetSmash.nextStage': 'NASTĘPNY POZIOM', 'targetSmash.retryStage': 'POWTÓRZ',
    'targetSmash.exitToSelect': 'DO WYBORU POZIOMÓW', 'divisions.title': 'Liga Dywizji', 'divisions.titleUpper': 'LIGA DYWIZJI',
    'divisions.rank': 'Pozycja w dywizji', 'divisions.titleTarget': 'Cel mistrzowski', 'divisions.titleClaimed': 'Tytuł zdobyty!',
    'divisions.ptsForTrophy': 'Punkty do pucharu', 'divisions.seasonFinished': 'Koniec sezonu',
    'divisions.promotionAchieved': 'Awans osiągnięty!', 'divisions.thisSeason': 'Ten sezon',
    'divisions.matchesLeft': 'Pozostałe mecze', 'divisions.ptsNeeded': 'Wymagane punkty', 'divisions.win': 'Wygrana',
    'divisions.draw': 'Remis', 'divisions.loss': 'Porażka', 'divisions.pt': 'PKT', 'divisions.pts': 'PKT',
    'divisions.allTime': 'Bilans historyczny', 'divisions.matchesHistory': 'Historia meczów', 'divisions.match': 'Mecz',
    'divisions.noMatchesYet': 'Brak meczów w tym sezonie', 'divisions.noMatchesSub': 'Rozpocznij sezon poniżej!',
    'divisions.nextMatchChooseOpponent': 'Następny mecz • Wybierz rywala', 'divisions.whoDoYouWantToPlay': 'Wybierz kolejnego rywala:',
    'divisions.teamsAvailable': 'Dostępne drużyny', 'divisions.searchNationalTeam': 'Szukaj reprezentacji...',
    'divisions.playMatchVs': 'ZAGRAJ MECZ PRZECIWKO', 'divisions.opponent': 'Przeciwnik', 'divisions.opponentUpper': 'PRZECIWNIK',
    'divisions.opponentConnected': 'Rywal połączony', 'divisions.change': 'Zmień', 'divisions.chooseOpponent': 'Wybierz rywala',
    'divisions.divShort': 'DYW', 'divisions.of': 'z', 'divisions.continueTo': 'Przejdź do', 'divisions.next': 'Dalej',
    'divisions.findingOpponent': 'Szukanie rywala w dywizji...', 'divisions.matchingWithOnline': 'Wyszukiwanie graczy z Twojej dywizji',
    'divisions.searchingActivePlayers': 'Szukanie na serwerach...', 'divisions.matchStartingIn': 'Mecz rozpocznie się za',
    'divisions.cancelMatchmaking': 'Anuluj szukanie', 'divisions.cancelSearch': 'Anuluj szukanie', 'divisions.wdl': 'W-R-P',
    'division.return': 'Powrót do Dywizji', 'division.reward': 'Nagroda za dywizję', 'result.victory': 'ZWYCIĘSTWO!',
    'result.defeat': 'PORAŻKA', 'result.draw': 'REMIS', 'result.champion': 'MISTRZ ŚWIATA!', 'result.prizeWon': 'Zdobyta nagroda',
    'result.streak': 'Obecna seria', 'result.newRecord': 'NOWY REKORD!', 'result.coinsEarned': 'Zdobyte monety',
    'result.finalScore': 'Wynik końcowy', 'result.totalScore': 'Suma punktów', 'result.wonOnPenalties': 'WYGRANA W KARNYCH',
    'result.lostOnPenalties': 'PRZEGRANA W KARNYCH', 'result.survivalVictory': 'ZWYCIĘSTWO W PRZETRWANIU!',
    'result.survivalDefeat': 'WYELIMINOWANY Z PRZETRWANIA', 'result.wagerResults': 'Wyniki zakładu',
    'rematch.invitationTitle': 'Zaproszenie do rewanżu', 'rematch.invitationDesc': 'Przeciwnik chce zagrać rewanż!',
    'rematch.accept': 'Przyjmij rewanż', 'rematch.decline': 'Odrzuć', 'rematch.starting': 'Uruchamianie rewanżu...',
    'rematch.survivalRequested': 'Przeciwnik żąda rewanżu w Przetrwaniu!',
    'rematch.survivalDesc': 'Przyjmij, by natychmiast wrócić do pojedynku 1v1!',
    'rematch.wagerChallenge': 'wyzywa Cię na rewanż o stawkę!', 'stats.goals': 'Gole', 'stats.shots': 'Strzały',
    'status.live': 'NA ŻYWO', 'status.offline': 'OFFLINE', 'status.winner': 'ZWYCIĘZCA', 'status.eliminated': 'ODPADA',
    'status.survived': 'PRZETRWAŁ', 'status.left': 'OPUŚCIŁ', 'status.disconnected': 'ROZŁĄCZONO',
    'store.title': 'Sklep z wyposażeniem', 'store.subtitle': 'TEKSTURY 3D PIŁEK I WZORY TRAWY',
    'store.balls': 'Piłki', 'store.pitches': 'Murawy', 'store.ballStore': 'SKLEP Z PIŁKAMI',
    'store.ballStoreDesc': 'Tekstury 3D & Profesjonalne modele', 'store.pitchStore': 'SKLEP ZE STADIONAMI',
    'store.pitchStoreDesc': 'Wzory koszenia murawy na stadionach', 'store.selectCategory': 'WYBIERZ KATEGORIĘ',
    'store.unlockedAndEquipped': 'ODBLOKOWANE I ZAŁOŻONE', 'store.owned': 'Posiadane', 'store.buyFor': 'Kup za',
    'store.notEnoughCoins': 'ZA MAŁO MONET!', 'store.needMore': 'BRAKUJE', 'store.more': 'WIĘCEJ',
    'profile.title': 'Profil Gracza', 'profile.cloudStorageNotice': 'ZAPIS W CHMURZE CRAZYGAMES I LOKALNY',
    'replays.subtitle': 'Przeglądaj i zarządzaj swoimi najlepszymi golami', 'replays.savedReplays': 'ZAPISANE POWTÓRKI',
    'replays.savedHighlights': 'NAJLEPSZE MOMENTY', 'replays.clips': 'Klipy', 'replays.savedClips': 'Zapisane klipy',
    'replays.noSavedReplays': 'BRAK ZAPISANYCH POWTÓREK', 'replays.noHighlightsTitle': 'BRAK POWTÓREK',
    'replays.noHighlightsDesc': 'Strzel gola w meczu i naciśnij ZAPISZ podczas powtórki!',
    'replays.playMatchNow': 'ZAGRAJ MECZ', 'replays.emptyInstructions': 'Strzel bramkę i dotknij ZAPISZ w prawym górnym rogu powtórki!',
    'replays.savedHighlight': 'ZAPISANY GOL', 'replays.savedDate': 'DATA', 'replays.shotDistance': 'DYSTANS STRZAŁU',
    'replays.longestStrike': 'Najdalszy strzał', 'replays.goalHighlights': 'Najlepsze gole', 'replays.watchReplay': 'OBEJRZYJ POWTÓRKĘ',
    'replays.exitReplay': 'WYJDŹ Z POWTÓRKI', 'replays.deleteReplay': 'Usuń powtórkę',
    'replays.confirmDelete': 'Czy chcesz usunąć tę powtórkę?', 'replays.deleteAllConfirm': 'USUNĄĆ WSZYSTKIE POWTÓRKI?',
    'replays.deleteAllDesc': 'Czy na pewno chcesz skasować całą galerię powtórek?', 'ads.videoReward': 'NAGRODA ZA REKLAMĘ',
    'ads.coinsReward': 'NAGRODA W MONETACH', 'ads.watchToEarn': 'Oglądaj reklamy wideo, by zyskać +50 monet',
    'ads.instantBoost': 'Natychmiastowe doładowanie monet', 'ads.integrationFinalizing': 'Finalizacja integracji reklam.',
    'ads.unlockAllItems': 'Odblokuj wszystkie 50 piłek i 50 stylów murawy!', 'ads.loading': 'ŁADOWANIE REKLAMY...',
    'lang.title': 'Ustawienia języka', 'lang.subtitle': 'Wybierz swój język (16 dostępnych języków)',
    'lang.autoDetect': 'Automatycznie wykryty język', 'lang.currentlyActive': 'OBECNIE AKTYWNY',
    'lang.sdkSyncTitle': 'Synchronizacja CrazyGames', 'lang.sdkSyncDesc': 'Język gry automatycznie synchronizuje się z Twoim portalem',
    'lang.searchPlaceholder': 'Szukaj języka lub kraju...', 'lang.tabAll': 'Wszystkie (16)', 'lang.tabPopular': 'Popularne',
    'lang.tabEurope': 'Europa', 'lang.tabAmericas': 'Ameryki', 'lang.tabAsiaMe': 'Azja i Bliski Wschód',
    'lang.noMatches': 'Nie znaleziono języków', 'lang.noMatchesDesc': 'Spróbuj wpisać inną nazwę kraju lub języka',
    'lang.resetFilters': 'Resetuj filtry'
}

nl = {
    'nav.store': 'Winkel', 'nav.profile': 'Profiel', 'nav.replays': 'Herhalingen', 'nav.coins': 'Munten',
    'nav.language': 'Taal', 'nav.bestStreak': 'Beste Reeks', 'nav.online': 'Online', 'nav.connecting': 'Verbinden...',
    'game.title': 'FREE KICK LEGENDS', 'menu.quickPlay': 'SNEL SPELEN', 'menu.quickPlaySub': 'ONLINE & OFFLINE WEDSTRIJDEN',
    'menu.survivalMode': 'SURVIVAL-MODUS', 'survival.threeLives': '3 LEVENS', 'survival.endlessStreak': 'Eindeloze Reeks',
    'survival.best': 'Record', 'survival.streak': 'REEKS', 'survival.onlineAvailable': 'Online 1v1 Survival Beschikbaar',
    'menu.wagerArena': 'INZET-ARENA', 'wager.betCoinsPot': 'Zet Munten In • Winnaar Krijgt Alles',
    'wager.onlineDuel': 'Online 1v1 Munten-Inzet Duel', 'wager.duel': 'DUEL', 'wager.arena': 'Arena', 'wager.bet': 'Inzet',
    'wager.winnerTakes': 'Winnaar Krijgt', 'wager.prizePot': 'Prijzenpot', 'menu.worldCup': 'FIFA WERELDBEKER',
    'menu.tournamentFormat': 'Toernooiformat', 'menu.practice': 'TRAINING', 'menu.practiceSub': 'Vrije Trappen Oefenen',
    'menu.shop': 'WINKEL', 'menu.onlineMultiplayer': 'Online Multiplayer Beschikbaar',
    'profile.savedReplaysStats': 'HERHALINGEN & STATISTIEKEN', 'replays.title': 'Opgeslagen Herhalingen',
    'common.coins': 'MUNTEN', 'common.coinsUpper': 'MUNTEN', 'common.online': 'ONLINE', 'common.offline': 'OFFLINE',
    'common.back': 'TERUG', 'common.backToMenu': 'Terug naar Menu', 'common.active': 'ACTIEF', 'common.done': 'KLAAR',
    'common.close': 'SLUITEN', 'common.gotIt': 'BEGREPEN', 'common.cancel': 'Annuleren', 'common.continue': 'DOORGAAN',
    'common.exit': 'VERLATEN', 'common.quit': 'STOPPEN', 'common.play': 'SPELEN', 'common.saved': 'OPGESLAGEN',
    'common.goal': 'DOELPUNT', 'common.goals': 'doelpunten', 'common.pts': 'PNT', 'common.you': 'Jij',
    'common.opponent': 'Tegenstander', 'common.watchAdCoins': 'Bekijk video voor +50 gratis munten',
    'currency.coins': 'MUNTEN', 'btn.play': 'Nu Spelen', 'btn.select': 'Selecteren', 'btn.confirm': 'Bevestigen',
    'btn.cancel': 'Annuleren', 'btn.close': 'Sluiten', 'btn.back': 'Terug', 'btn.continue': 'Doorgaan',
    'btn.nextMatch': 'Volgende Wedstrijd', 'btn.returnMenu': 'Hoofdmenu', 'btn.equip': 'Kiezen',
    'btn.equipped': 'Gekozen', 'btn.unlock': 'Ontgrendelen', 'btn.locked': 'Vergrendeld',
    'btn.saveReplay': 'Herhaling Opslaan', 'btn.save': 'OPSLAAN', 'btn.saved': 'OPGESLAGEN',
    'btn.skip': 'OVERSLAAN', 'btn.playAgain': 'Opnieuw Spelen', 'btn.watchAd': 'Video Bekijken (+50 Munten)',
    'btn.freeCoins': 'Gratis Munten', 'hud.aim': 'Mikken', 'hud.power': 'Kracht', 'hud.curve': 'Effect', 'hud.kick': 'Schot',
    'hud.stepAim': 'PAS SCHOTHOEK AAN', 'hud.stepPower': 'BEPAAL KRACHT', 'hud.stepCurve': 'GEEF EFFECT AAN DE BAL',
    'hud.stepKick': 'SCHIET DE BAL', 'hud.shoot': 'SCHIET!', 'hud.tapToLock': 'TIK OM TE VERGRENDELEN',
    'hud.tapToKick': 'TIK OM TE SCHIETEN', 'hud.goal': 'DOELPUNT!', 'hud.saved': 'REDDING!', 'hud.missed': 'GEMIST!',
    'hud.wallBlocked': 'MUUR BLOKKEERT!', 'hud.postHit': 'OP DE PAAL!', 'hud.suddenDeath': 'SUDDEN DEATH',
    'hud.goldenGoal': 'GOLDEN GOAL', 'hud.penaltyShootout': 'STRAFSCHOPPENSERIE', 'hud.turn': 'Beurt',
    'hud.yourTurn': 'JOUW BEURT', 'hud.oppTurn': 'BEURT TEGENSTANDER', 'hud.aiThinking': 'BOT DENKT NA...',
    'hud.aiAiming': 'BOT MIKT...', 'hud.aiStriking': 'BOT SCHIET...', 'hud.timer': 'Tijd',
    'hud.matchOver': 'WEDSTRIJD AFGELOPEN', 'hud.rematch': 'Revanche', 'hud.exitMatch': 'Wedstrijd Verlaten',
    'hud.resume': 'Hervatten', 'hud.pause': 'Pauze', 'hud.yourTurnPenalty': 'JOUW STRAFSCHOP',
    'hud.oppPenalty': 'TEGENSTANDER NEEMT STRAFSCHOP...', 'hud.aiPenalty': 'BOT NEEMT STRAFSCHOP...',
    'hud.playIn': 'CAMERA:', 'hud.ballTracking': 'BAL VOLGEN', 'hud.behindGoal': 'ACHTER HET DOEL',
    'hud.meter': 'METER', 'hud.aiGoalkeeper': 'BOT DOELMAN', 'hud.aiStriker': 'BOT AANVALLER',
    'hud.defenseSim': 'Verdedigingssimulatie', 'hud.precisionFK': 'Precisievrije Trap', 'hud.aiming': 'MIKKEN',
    'hud.holdToCharge': 'INGEDRUKT HOUDEN VOOR KRACHT', 'hud.releaseToStrikeInstruction': 'HOUD SPATIE / SCHERM VAST • LAAT LOS OM TE SCHIETEN',
    'hud.weak': 'ZWAK', 'hud.sweetSpot': 'PERFECT', 'hud.max': 'MAX', 'hud.chargingPower': 'KRACHT OPLADEN...',
    'hud.replay': 'HERHALING', 'game.goal': 'GOAL!', 'game.saved': 'REDDING',
    'quickPlay.selectMode': 'Kies wedstrijdmodus:', 'quickPlay.ranked': 'Gerangschikt', 'quickPlay.vsAi': 'Vs Bot / Lokaal',
    'country.selectTeams': 'TEAMSELECTIE', 'country.nationalTeams': 'Nationale Teams', 'country.teamsAvailable': 'Beschikbare Teams',
    'country.tapToSelect': 'Tik om te selecteren', 'country.myTeam': 'MIJN TEAM', 'country.opponent': 'TEGENSTANDER',
    'country.continueToMatch': 'DOORGAAN NAAR WEDSTRIJD', 'search.countries': 'Land zoeken...', 'teamSelect.teams': 'Teams',
    'teamSelect.searchPlaceholder': 'Zoek nationaal team...', 'teamSelect.att': 'AAN', 'teamSelect.def': 'VER',
    'team.selectNew': 'KIES NIEUW TEAM', 'team.selectNewDesc': 'Kies uit 120 nationale elftallen wereldwijd',
    'online.matchTitle': 'ONLINE WEDSTRIJD', 'online.matchSubtitle': 'Maak live verbinding en kies je land:',
    'online.createRoom': 'Privékamer Aanmaken', 'online.joinRoom': 'Deelnemen met Code', 'online.joinRoomTitle': 'DEELNEMEN MET CODE',
    'online.roomCode': 'Kamercode', 'online.copyCode': 'Code Kopiëren', 'online.codeCopied': 'Gekopieerd!',
    'online.shareCode': 'Deel deze 4-cijferige code met een vriend:', 'online.enterCode': 'Voer 4-cijferige code in:',
    'online.findMatch': 'Snelle Matchmaking', 'online.searchingMatch': 'Tegenstander zoeken...', 'online.stillSearching': 'Zoeken naar actieve spelers...',
    'online.retrySearch': 'Opnieuw Zoeken', 'online.cancelSearch': 'Zoeken Annuleren', 'online.cancelRoom': 'Kamer Annuleren',
    'online.leaveRoom': 'Kamer Verlaten', 'online.inviteLink': 'Uitnodigingslink Kopiëren', 'online.linkCopied': 'Link Gekopieerd!',
    'online.lookingOpponent': 'Zoeken naar wereldwijde tegenstander...', 'online.pairingAuto': 'Koppelen met speler...', 'online.ready': 'KLAAR',
    'online.bothSelected': 'Beiden klaar! Wedstrijd begint...', 'online.selectTeamBelow': 'Kies hieronder je team:',
    'online.lockedIn': 'VASTGELEGD', 'online.selecting': 'Kiezen...', 'online.choosing': 'Kiest nationaal team...',
    'online.opponentLeft': 'Tegenstander heeft de kamer verlaten', 'online.opponentLeftSub': 'Binnenkort terug naar het menu...',
    'online.roomCreated': 'KAMER AANGEMAAKT', 'online.room': 'Kamer', 'online.host': 'Host', 'online.guest': 'Gast',
    'online.firstTurn': 'Jij trapt eerst af', 'online.secondTurn': 'Tegenstander trapt eerst af',
    'online.matchStartingIn': 'Wedstrijd begint over', 'online.kickoff': 'AFTRAP!',
    'online.leaveMatchTitle': 'WEDSTRIJD VERLATEN?', 'online.leaveMatchSub': 'Verlaten geeft de overwinning automatisch aan de tegenstander.',
    'online.leaveMatch': 'WEDSTRIJD VERLATEN', 'online.leave': 'VERLATEN', 'online.returnToMenu': 'Naar Hoofdmenu',
    'online.returningToMenu': 'Terug naar het menu...', 'online.sessionDisconnected': 'Sessie Verbroken',
    'online.yourCountry': 'JOUW LAND', 'online.oppCountry': 'LAND TEGENSTANDER',
    'online.waitingOpponent': 'Wachten op keuze tegenstander...', 'online.waitingOpponentCode': 'Wachten op vriend met code...',
    'online.connectSub': 'Wereldwijde 1v1 multiplayer servers', 'modal.matchmaking': 'Tegenstander Zoeken...',
    'modal.matchmakingDesc': 'Zoeken op wereldwijde servers', 'modal.searchingTime': 'Zoektijd',
    'modal.opponentFound': 'TEGENSTANDER GEVONDEN!', 'modal.connectingBot': 'Verbinden met bot in 30s...',
    'modal.quitMatchSub': 'Huidige wedstrijdvoortgang wordt niet opgeslagen.', 'modal.forfeitMatchTitle': 'OPGEVEN?',
    'modal.forfeitMatchSub': 'Opgeven telt als een automatisch verlies.', 'modal.forfeit': 'OPGEVEN',
    'match.opponentLeftTitle': 'TEGENSTANDER HEEFT VERLATEN', 'match.opponentLeftDesc': 'Je tegenstander heeft de verbinding verbroken.',
    'match.playAgainUnavailable': 'Revanche niet mogelijk omdat de tegenstander vertrokken is.',
    'match.waitingOpponent': 'Wachten op reactie van de tegenstander...', 'match.changeTeams': 'TEAMS WIJZIGEN',
    'tournament.selectFormat': 'Kies toernooiformat:', 'tournament.globalCup': 'Wereldbeker', 'tournament.customCup': 'Aangepaste Beker',
    'tournament.inDevelopment': 'IN ONTWIKKELING', 'tournament.onlineWorldCup': 'ONLINE WERELDBEKER',
    'tournament.multiplayerWorldCup': 'Multiplayer Wereldbekers & Knock-out Toernooien', 'tournament.knockoutBrackets': '16-Team Knock-out Schema',
    'tournament.knockoutBracketsSub': 'Real-time knock-out toernooien', 'tournament.globalLeaderboards': 'Wereldwijde Seizoensranglijsten',
    'tournament.globalLeaderboardsSub': 'Verdien ranglijstpunten en trofeeën', 'tournament.exclusiveUnlockables': 'Exclusieve Kampioenshirtjes & Ballen',
    'tournament.exclusiveUnlockablesSub': 'Speciale beloningen voor winnaars', 'tournament.playOfflineNow': 'SPEEL OFFLINE WERELDBEKER',
    'tournament.selectYourTeam': 'KIES JE TEAM', 'tournament.worldCupQualifiedSub': 'FIFA Wereldbeker • 40 Gekwalificeerde Landen (Groep A – J)',
    'tournament.searchCountry': 'Zoek land of groep...', 'tournament.qualifiedNations': 'Gekwalificeerde Landen',
    'tournament.tapToSelect': 'Tik om te Kiezen', 'tournament.selected': 'GESELECTEERD', 'tournament.ovr': 'ALG',
    'tournament.randomGroupDraw': 'Willekeurige groepsloting bij start', 'tournament.tapAnyCountryPrompt': 'TIK OP EEN LAND OM JE TEAM TE KIEZEN',
    'tournament.enterWorldCup': 'START WERELDBEKER (GROEPEN A - J)', 'tournament.backToMenu': 'Naar Hoofdmenu',
    'tournament.forfeitMatch': 'WEDSTRIJD OPGEVEN', 'tournament.continue': 'DOORGAAN NAAR KNOCK-OUTFASE',
    'tournament.championTitle': '★ WERELDKAMPIOEN ★', 'tournament.worldChampions': 'WERELDKAMPIOEN',
    'tournament.winnerLiftsCup': 'Je hebt de Wereldbeker omhoog getild!', 'tournament.freeKickCup': 'Vrije Trappen Wereldbeker',
    'tournament.roundOf16': 'Achtste Finale', 'tournament.quarterFinals': 'Kwartfinale', 'tournament.semiFinal1': 'Halve Finale 1',
    'tournament.semiFinal2': 'Halve Finale 2', 'tournament.worldFinal': 'Wereldbeker Finale', 'tournament.awaitingFinal': 'Wachten op finalist',
    'tournament.fixture': 'Wedstrijd', 'tournament.ft': 'FT', 'tournament.tbd': 'NOG ONBEKEND', 'tournament.cancelTournament': 'Toernooi Annuleren',
    'practice.selectDrill': 'Kies oefening:', 'practice.freeKick': 'VRIJE TRAP',
    'practice.freeKickSub': 'Direct spelen • Muur en hoeken', 'practice.instant': 'Direct',
    'practice.penalty': 'STRAFSCHOP', 'practice.penaltySub': '1v1 tegen doelman • Geen tijdslimiet', 'practice.random': 'Willekeurig',
    'practice.exitTitle': 'TRAINING VERLATEN?', 'practice.exitSub': 'Je kunt op elk moment terugkeren naar het hoofdmenu.',
    'practice.exitButton': 'TRAINING VERLATEN', 'survival.title': 'Survival-Arena',
    'survival.subtitle': '3 Levens • Eindeloze Reeksen • Duels', 'survival.arenaTitle': 'SURVIVAL-ARENA',
    'survival.onlineSurvivalTitle': 'ONLINE SURVIVAL 1V1',
    'survival.onlineSurvivalSubtitle': '3 Levens • Live 1v1 Duel • Eindeloze Doelpuntenreeks Uitdaging',
    'survival.selectGameMode': 'Kies spelmodus:', 'survival.offlineSurvivalBtn': 'OFFLINE SURVIVAL',
    'survival.onlineDuelBtn': 'ONLINE 1V1 DUEL', 'survival.rulesBtn': 'Regels',
    'survival.rulesTitle': 'SURVIVAL-REGELS', 'survival.rulesSubtitle': 'Volg deze 2 regels om het record te breken:',
    'survival.rule1Title': '3 Levens Systeem',
    'survival.rule1Desc': 'Elke speler begint met 3 harten. Een misser of redding kost 1 leven. Wie als eerste door zijn levens heen is, verliest!',
    'survival.rule2Title': 'Om de Beurt & 100s Timer',
    'survival.rule2Desc': 'Afwisselende vrije trappen met een 100-seconden klok. Scoor om je winnende reeks te vergroten!',
    'survival.backToRules': 'Terug naar Regels', 'survival.howItWorks': 'Hoe het werkt', 'survival.guideBadge': 'SURVIVAL-GIDS',
    'survival.livesRemaining': 'Resterende Levens', 'survival.bestRecord': 'All-Time Record', 'survival.bestStreak': 'BESTE REEKS',
    'survival.startRun': 'Poging Starten', 'survival.personalRecord': 'Persoonlijk Record', 'survival.goalStreak': 'DOELPUNTENREEKS',
    'survival.goalsStreak': 'DOELPUNTENREEKS', 'survival.kicks': 'Schoten', 'survival.duel': 'SURVIVAL 1V1 DUEL',
    'survival.duelSub': 'Online Knock-out Duel', 'survival.runEnded': 'POGING AFGELOPEN!',
    'survival.challengeComplete': 'Survival Uitdaging Voltooid', 'survival.finalGoalsStreak': 'Uiteindelijke Doelpuntenreeks',
    'survival.challengeMode': 'Uitdagingsmodus', 'survival.reviveExtraLife': 'HERLEVEN (+1 EXTRA LEVEN)',
    'survival.endSurvivalTitle': 'SURVIVAL BEËINDIGEN?', 'survival.endSurvival': 'BEËINDIGEN', 'survival.endRun': 'POGING STOPPEN',
    'survival.concludeSub': 'De wedstrijd wordt onmiddellijk beëindigd.', 'survival.currentStreak': 'Huidige reeks:',
    'wager.title': 'Inzet-Arenas', 'wager.subtitle': 'Kies je inzet • De winnaar krijgt alle munten!',
    'wager.rookie': 'Beginners-Arena', 'wager.pro': 'Pro-Arena', 'wager.champion': 'Kampioenen-Arena', 'wager.legend': 'Legenden-Arena',
    'wager.entryFee': 'Toegangsprijs', 'wager.entry': 'TOEGANG', 'wager.prizePot': 'Prijzenpot', 'wager.winPot': 'WINNAARSPOT',
    'wager.highRoller': 'High-Stakes Live Duel', 'wager.bottomBanner': 'Ontdek arenas • Hoge inzet, dubbele winst!',
    'wager.tapToSelect': 'Tik om te kiezen', 'wager.playWithCoins': 'Speel voor munten', 'wager.needMoreCoins': 'Meer munten nodig',
    'wager.forfeitWager': 'INZET OPGEVEN', 'wager.surrenderTitle': 'INZET OPGEVEN?',
    'wager.surrenderSub': 'Opgeven betekent verlies van je inzet:', 'wager.surrender': 'OPGEVEN', 'wager.victory': 'INZET GEWONNEN!',
    'wager.coinDuelResults': 'Duel Resultaten', 'wager.drawRefunded': 'GELIJKSPEL • INZET TERUGBETAALD',
    'wager.arenaPot': 'Arena Pot', 'wager.netResult': 'Netto Resultaat',
    'wager.opponentLeft': 'Tegenstander heeft arena verlaten', 'wager.rematch': 'REVANCHE MET INZET',
    'targetSmash.title': 'DOELWITTEN RAKEN', 'targetSmash.arcadeBadge': 'NIEUWE ARCADE-MODUS',
    'targetSmash.trickshotSubtitle': 'Doelwitten & Effectballen', 'targetSmash.selectStage': 'Level (1 - 10)',
    'targetSmash.unlocked': 'Ontgrendeld', 'targetSmash.stage': 'Level', 'targetSmash.objective': 'Doel',
    'targetSmash.highScore': 'Record', 'targetSmash.pts': 'PNT', 'targetSmash.distance': 'Afstand',
    'targetSmash.defendersWall': 'Verdedigingsmuur', 'targetSmash.players': 'Spelers', 'targetSmash.targetScore': 'Doelscore',
    'targetSmash.targetRequired': 'Vereiste Punten', 'targetSmash.playStage': 'LEVEL SPELEN', 'targetSmash.stageLocked': 'LEVEL VERGRENDELD',
    'targetSmash.stageCleared': 'LEVEL GEHAALD!', 'targetSmash.stageFailed': 'LEVEL MISLUKT', 'targetSmash.finalScore': 'Eindscore',
    'targetSmash.coinsReward': 'Muntenbeloning', 'targetSmash.nextStage': 'VOLGEND LEVEL', 'targetSmash.retryStage': 'OPNIEUW PROBEREN',
    'targetSmash.exitToSelect': 'NAAR LEVELSELECTIE', 'divisions.title': 'Divisie-Competitie', 'divisions.titleUpper': 'DIVISIE-COMPETITIE',
    'divisions.rank': 'Divisie-Rang', 'divisions.titleTarget': 'Titeldoel', 'divisions.titleClaimed': 'Titel Gewonnen!',
    'divisions.ptsForTrophy': 'Punten voor Kampioenstrofee', 'divisions.seasonFinished': 'Seizoen Afgelopen',
    'divisions.promotionAchieved': 'Promotie Behaald!', 'divisions.thisSeason': 'Dit Seizoen',
    'divisions.matchesLeft': 'Resterende Wedstrijden', 'divisions.ptsNeeded': 'Benodigde Punten', 'divisions.win': 'Winst',
    'divisions.draw': 'Gelijkspel', 'divisions.loss': 'Verlies', 'divisions.pt': 'PNT', 'divisions.pts': 'PNT',
    'divisions.allTime': 'Totaaloverzicht', 'divisions.matchesHistory': 'Wedstrijdgeschiedenis', 'divisions.match': 'Wedstrijd',
    'divisions.noMatchesYet': 'Nog geen wedstrijden gespeeld dit seizoen', 'divisions.noMatchesSub': 'Begin je seizoen hieronder!',
    'divisions.nextMatchChooseOpponent': 'Volgende Wedstrijd • Kies Tegenstander', 'divisions.whoDoYouWantToPlay': 'Kies je volgende tegenstander:',
    'divisions.teamsAvailable': 'Beschikbare Teams', 'divisions.searchNationalTeam': 'Zoek nationaal elftal...',
    'divisions.playMatchVs': 'SPEEL WEDSTRIJD TEGEN', 'divisions.opponent': 'Tegenstander', 'divisions.opponentUpper': 'TEGENSTANDER',
    'divisions.opponentConnected': 'Tegenstander Verbonden', 'divisions.change': 'Wijzigen', 'divisions.chooseOpponent': 'Tegenstander Kiezen',
    'divisions.divShort': 'DIV', 'divisions.of': 'van', 'divisions.continueTo': 'Doorgaan naar', 'divisions.next': 'Volgende',
    'divisions.findingOpponent': 'Zoeken naar Divisie-tegenstander...', 'divisions.matchingWithOnline': 'Koppelen met spelers uit je divisie',
    'divisions.searchingActivePlayers': 'Zoeken op divisie-servers...', 'divisions.matchStartingIn': 'Wedstrijd begint over',
    'divisions.cancelMatchmaking': 'Annuleren', 'divisions.cancelSearch': 'Zoeken Annuleren', 'divisions.wdl': 'W-G-V',
    'division.return': 'Terug naar Divisies', 'division.reward': 'Divisiebeloning', 'result.victory': 'OVERWINNING!',
    'result.defeat': 'NEDERLAAG', 'result.draw': 'GELIJKSPEL', 'result.champion': 'WERELDKAMPIOEN!', 'result.prizeWon': 'Prijs Gewonnen',
    'result.streak': 'Huidige Reeks', 'result.newRecord': 'NIEUW RECORD!', 'result.coinsEarned': 'Gewonnen Munten',
    'result.finalScore': 'Eindstand', 'result.totalScore': 'Totale Score', 'result.wonOnPenalties': 'GEWONNEN NA STRAFSCHOPPEN',
    'result.lostOnPenalties': 'VERLOREN NA STRAFSCHOPPEN', 'result.survivalVictory': 'SURVIVAL OVERWINNING!',
    'result.survivalDefeat': 'UITGESCHAKELD IN SURVIVAL', 'result.wagerResults': 'Inzet Resultaten',
    'rematch.invitationTitle': 'Revanche Aangevraagd', 'rematch.invitationDesc': 'Tegenstander wil een revanche spelen!',
    'rematch.accept': 'Revanche Accepteren', 'rematch.decline': 'Weigeren', 'rematch.starting': 'Revanche Starten...',
    'rematch.survivalRequested': 'Tegenstander vraagt om Survival-revanche!',
    'rematch.survivalDesc': 'Accepteer om meteen terug te keren naar het 1v1-duel!',
    'rematch.wagerChallenge': 'daagt je uit voor een Revanche met Inzet!', 'stats.goals': 'Doelpunten', 'stats.shots': 'Schoten',
    'status.live': 'LIVE', 'status.offline': 'OFFLINE', 'status.winner': 'WINNAAR', 'status.eliminated': 'UITGESCHAKELD',
    'status.survived': 'OVERLEEFD', 'status.left': 'VERLATEN', 'status.disconnected': 'VERBROKEN',
    'store.title': 'Uitrustingswinkel', 'store.subtitle': '3D BALTEXTUREN & GRASPATRONEN',
    'store.balls': 'Ballen', 'store.pitches': 'Velden', 'store.ballStore': 'BALLENWINKEL',
    'store.ballStoreDesc': '3D Texturen & Pro Modellen', 'store.pitchStore': 'STADIONWINKEL',
    'store.pitchStoreDesc': 'Stadiongras maaipatronen', 'store.selectCategory': 'KIES CATEGORIE',
    'store.unlockedAndEquipped': 'ONTGRENDELD EN GEKOZEN', 'store.owned': 'In Bezit', 'store.buyFor': 'Kopen voor',
    'store.notEnoughCoins': 'NIET GENOEG MUNTEN!', 'store.needMore': 'NOG NODIG', 'store.more': 'MEER',
    'profile.title': 'Spelersprofiel', 'profile.cloudStorageNotice': 'OPGESLAGEN IN CRAZYGAMES CLOUD & LOKAAL',
    'replays.subtitle': 'Bekijk en beheer je mooiste opgeslagen doelpunten', 'replays.savedReplays': 'OPGESLAGEN HERHALINGEN',
    'replays.savedHighlights': 'OPGESLAGEN HOOGTEPUNTEN', 'replays.clips': 'Clips', 'replays.savedClips': 'Opgeslagen Clips',
    'replays.noSavedReplays': 'NOG GEEN HERHALINGEN', 'replays.noHighlightsTitle': 'GEEN HOOGTEPUNTEN',
    'replays.noHighlightsDesc': 'Scoor in een wedstrijd en tik op OPSLAAN tijdens de herhaling!',
    'replays.playMatchNow': 'SPEEL EEN WEDSTRIJD', 'replays.emptyInstructions': 'Scoor een doelpunt en tik rechtsboven op OPSLAAN in de herhaling!',
    'replays.savedHighlight': 'OPGESLAGEN DOELPUNT', 'replays.savedDate': 'DATUM', 'replays.shotDistance': 'SCHOTAFSTAND',
    'replays.longestStrike': 'Verste Schot', 'replays.goalHighlights': 'Doelpunten Hoogtepunten', 'replays.watchReplay': 'HERHALING BEKIJKEN',
    'replays.exitReplay': 'HERHALING VERLATEN', 'replays.deleteReplay': 'Herhaling Verwijderen',
    'replays.confirmDelete': 'Dit opgeslagen hoogtepunt verwijderen?', 'replays.deleteAllConfirm': 'ALLE HERHALINGEN VERWIJDEREN?',
    'replays.deleteAllDesc': 'Weet je zeker dat je alle opgeslagen herhalingen wilt wissen?', 'ads.videoReward': 'VIDEOBELONING',
    'ads.coinsReward': 'MUNTENBELONING', 'ads.watchToEarn': 'Bekijk videoreclames voor +50 munten',
    'ads.instantBoost': 'Directe Muntenboost', 'ads.integrationFinalizing': 'Reclame-integratie wordt voltooid.',
    'ads.unlockAllItems': 'Ontgrendel alle 50 ballen en 50 stadionvelden!', 'ads.loading': 'RECLAME LADEN...',
    'lang.title': 'Taalinstellingen', 'lang.subtitle': 'Kies je voorkeurstaal (16 talen ondersteund)',
    'lang.autoDetect': 'Automatisch Gedetecteerde Taal', 'lang.currentlyActive': 'MOMENTEEL ACTIEF',
    'lang.sdkSyncTitle': 'CrazyGames Synchronisatie', 'lang.sdkSyncDesc': 'Speltaal past zich automatisch aan je portaal aan',
    'lang.searchPlaceholder': 'Zoek taal of land...', 'lang.tabAll': 'Alles (16)', 'lang.tabPopular': 'Populair',
    'lang.tabEurope': 'Europa', 'lang.tabAmericas': 'Amerika', 'lang.tabAsiaMe': 'Azië & MO',
    'lang.noMatches': 'Geen talen gevonden', 'lang.noMatchesDesc': 'Probeer een andere taal of landnaam',
    'lang.resetFilters': 'Filters Resetten'
}

print("PL and NL loaded.")
