# -*- coding: utf-8 -*-
# German (de) & Italian (it)

de = {
    'nav.store': 'Shop', 'nav.profile': 'Profil', 'nav.replays': 'Replays', 'nav.coins': 'Münzen',
    'nav.language': 'Sprache', 'nav.bestStreak': 'Beste Serie', 'nav.online': 'Online', 'nav.connecting': 'Verbinde...',
    'game.title': 'FREE KICK LEGENDS', 'menu.quickPlay': 'SCHNELLES SPIEL', 'menu.quickPlaySub': 'ONLINE- & OFFLINE-SPIELE',
    'menu.survivalMode': 'SURVIVAL-MODUS', 'survival.threeLives': '3 LEBEN', 'survival.endlessStreak': 'Endlose Serie',
    'survival.best': 'Rekord', 'survival.streak': 'SERIE', 'survival.onlineAvailable': 'Online 1v1 Survival Verfügbar',
    'menu.wagerArena': 'WETT-ARENA', 'wager.betCoinsPot': 'Münzen Setzen • Gewinner Bekommt Alles',
    'wager.onlineDuel': 'Online 1v1 Münzwettspiel', 'wager.duel': 'DUELL', 'wager.arena': 'Arena', 'wager.bet': 'Einsatz',
    'wager.winnerTakes': 'Gewinner Bekommt', 'wager.prizePot': 'Preis-Pott', 'menu.worldCup': 'FIFA WELTMEISTERSCHAFT',
    'menu.tournamentFormat': 'Turnier-Format', 'menu.practice': 'TRAINING', 'menu.practiceSub': 'Freistoßtraining',
    'menu.shop': 'SHOP', 'menu.onlineMultiplayer': 'Online-Mehrspieler Verfügbar',
    'profile.savedReplaysStats': 'REPLAYS & STATISTIKEN', 'replays.title': 'Gespeicherte Replays',
    'common.coins': 'MÜNZEN', 'common.coinsUpper': 'MÜNZEN', 'common.online': 'ONLINE', 'common.offline': 'OFFLINE',
    'common.back': 'ZURÜCK', 'common.backToMenu': 'Zurück zum Menü', 'common.active': 'AKTIV', 'common.done': 'FERTIG & ZURÜCK',
    'common.close': 'SCHLIESSEN', 'common.gotIt': 'VERSTANDEN', 'common.cancel': 'Abbrechen', 'common.continue': 'WEITER',
    'common.exit': 'BEENDEN', 'common.quit': 'BEENDEN', 'common.play': 'SPIELEN', 'common.saved': 'GESPEICHERT',
    'common.goal': 'TOR', 'common.goals': 'Tore', 'common.pts': 'PKT', 'common.you': 'Du', 'common.opponent': 'Gegner',
    'common.watchAdCoins': 'Video-Werbung für +50 Gratis-Münzen ansehen', 'currency.coins': 'MÜNZEN',
    'btn.play': 'Jetzt Spielen', 'btn.select': 'Auswählen', 'btn.confirm': 'Bestätigen', 'btn.cancel': 'Abbrechen',
    'btn.close': 'Schließen', 'btn.back': 'Zurück', 'btn.continue': 'Weiter', 'btn.nextMatch': 'Nächstes Spiel',
    'btn.returnMenu': 'Hauptmenü', 'btn.equip': 'Ausrüsten', 'btn.equipped': 'Ausgerüstet', 'btn.unlock': 'Freischalten',
    'btn.locked': 'Gesperrt', 'btn.saveReplay': 'Replay Speichern', 'btn.save': 'SPEICHERN', 'btn.saved': 'GESPEICHERT',
    'btn.skip': 'ÜBERSPRINGEN', 'btn.playAgain': 'Nochmal Spielen', 'btn.watchAd': 'Video Ansehen (+50 Münzen)', 'btn.freeCoins': 'Gratis-Münzen',
    'hud.aim': 'Zielen', 'hud.power': 'Kraft', 'hud.curve': 'Drall', 'hud.kick': 'Schuss',
    'hud.stepAim': 'WINKEL ANPASSEN', 'hud.stepPower': 'KRAFT FESTLEGEN', 'hud.stepCurve': 'DRALL ANWENDEN',
    'hud.stepKick': 'SCHUSS AUSFÜHREN', 'hud.shoot': 'SCHIESSEN!', 'hud.tapToLock': 'TIPPEN ZUM FESTLEGEN',
    'hud.tapToKick': 'TIPPEN ZUM SCHUSS', 'hud.goal': 'TOR!', 'hud.saved': 'GEHALTEN!', 'hud.missed': 'DANEBEN!',
    'hud.wallBlocked': 'MAUER HAT GEBLOCKT!', 'hud.postHit': 'PFOSTEN!', 'hud.suddenDeath': 'SUDDEN DEATH',
    'hud.goldenGoal': 'GOLDEN GOAL', 'hud.penaltyShootout': 'ELFMETERSCHIESSEN', 'hud.turn': 'Runde',
    'hud.yourTurn': 'DU BIST DRAN', 'hud.oppTurn': 'GEGNER AM ZUG', 'hud.aiThinking': 'KI DENKT NACH...',
    'hud.aiAiming': 'KI ZIELT...', 'hud.aiStriking': 'KI SCHIESST...', 'hud.timer': 'Spielzeit',
    'hud.matchOver': 'SPIEL VORBEI', 'hud.rematch': 'Revanche', 'hud.exitMatch': 'Spiel Verlassen',
    'hud.resume': 'Fortsetzen', 'hud.pause': 'Pause', 'hud.yourTurnPenalty': 'DU SCHIESST DEN ELFMETER',
    'hud.oppPenalty': 'GEGNER SCHIESST ELFMETER...', 'hud.aiPenalty': 'KI SCHIESST ELFMETER...',
    'hud.playIn': 'SPIELEN IN:', 'hud.ballTracking': 'BALLVERFOLGUNG', 'hud.behindGoal': 'HINTER DEM TOR',
    'hud.meter': 'ANZEIGE', 'hud.aiGoalkeeper': 'KI-TORWART', 'hud.aiStriker': 'KI-SCHÜTZE',
    'hud.defenseSim': 'Abwehrsimulation', 'hud.precisionFK': 'Präzisions-Freistoß', 'hud.aiming': 'ZIELEN',
    'hud.holdToCharge': 'HALTEN ZUM AUFLADEN', 'hud.releaseToStrikeInstruction': 'LEERTASTE / TOUCH HALTEN • LOSLASSEN ZUM SCHIESSEN',
    'hud.weak': 'SCHWACH', 'hud.sweetSpot': 'PERFEKT', 'hud.max': 'MAX', 'hud.chargingPower': 'LADE KRAFT...',
    'hud.replay': 'REPLAY', 'game.goal': 'TOR!', 'game.saved': 'PARADE',
    'quickPlay.selectMode': 'Spielmodus wählen:', 'quickPlay.ranked': 'Gewertet', 'quickPlay.vsAi': 'Vs KI / Lokal',
    'country.selectTeams': 'TEAMS AUSWÄHLEN', 'country.nationalTeams': 'Nationalmannschaften', 'country.teamsAvailable': 'Verfügbare Teams',
    'country.tapToSelect': 'Karte antippen zum Auswählen', 'country.myTeam': 'MEIN TEAM', 'country.opponent': 'GEGNER',
    'country.continueToMatch': 'WEITER ZUM SPIEL', 'search.countries': 'Land suchen...', 'teamSelect.teams': 'Teams',
    'teamSelect.searchPlaceholder': 'Nationalteam suchen...', 'teamSelect.att': 'ANG', 'teamSelect.def': 'ABW',
    'team.selectNew': 'NEUES TEAM WÄHLEN', 'team.selectNewDesc': 'Wähle aus 120 Nationalmannschaften weltweit',
    'online.matchTitle': 'ONLINE-MATCH', 'online.matchSubtitle': 'Verbinde dich und wähle live dein Team:',
    'online.createRoom': 'Privaten Raum Erstellen', 'online.joinRoom': 'Mit Code Beitreten', 'online.joinRoomTitle': 'RAUM BEITRETEN',
    'online.roomCode': 'Raum-Code', 'online.copyCode': 'Code Kopieren', 'online.codeCopied': 'Kopiert!',
    'online.shareCode': 'Teile diesen 4-stelligen Code mit deinem Freund:', 'online.enterCode': '4-stelligen Raumcode eingeben:',
    'online.findMatch': 'Schnelle Spielsuche', 'online.searchingMatch': 'Suche nach Gegnern...', 'online.stillSearching': 'Suche aktive Spieler...',
    'online.retrySearch': 'Erneut Suchen', 'online.cancelSearch': 'Suche Abbrechen', 'online.cancelRoom': 'Raum Abbrechen',
    'online.leaveRoom': 'Raum Verlassen', 'online.inviteLink': 'Einladungslink Kopieren', 'online.linkCopied': 'Link Kopiert!',
    'online.lookingOpponent': 'Suche Gegner weltweit...', 'online.pairingAuto': 'Verbinde mit Spieler...', 'online.ready': 'BEREIT',
    'online.bothSelected': 'Beide bereit! Spiel startet...', 'online.selectTeamBelow': 'Wähle dein Team unten:',
    'online.lockedIn': 'BESTÄTIGT', 'online.selecting': 'Auswählen...', 'online.choosing': 'Wählt Nation...',
    'online.opponentLeft': 'Gegner hat den Raum verlassen', 'online.opponentLeftSub': 'Kehre gleich zum Menü zurück...',
    'online.roomCreated': 'RAUM ERSTELLT', 'online.room': 'Raum', 'online.host': 'Host', 'online.guest': 'Gast',
    'online.firstTurn': 'Du schießt zuerst', 'online.secondTurn': 'Gegner schießt zuerst',
    'online.matchStartingIn': 'Spiel startet in', 'online.kickoff': 'ANPFIFF!',
    'online.leaveMatchTitle': 'SPIEL VERLASSEN?', 'online.leaveMatchSub': 'Trennen wertet das Spiel als Sieg für deinen Gegner.',
    'online.leaveMatch': 'SPIEL VERLASSEN', 'online.leave': 'VERLASSEN', 'online.returnToMenu': 'Hauptmenü',
    'online.returningToMenu': 'Kehre zum Menü zurück...', 'online.sessionDisconnected': 'Verbindung Getrennt',
    'online.yourCountry': 'DEINE NATION', 'online.oppCountry': 'GEGNERISCHE NATION',
    'online.waitingOpponent': 'Warte auf Wahl des Gegners...', 'online.waitingOpponentCode': 'Warte auf Freund mit Code...',
    'online.connectSub': 'Weltweite Live 1v1 Multiplayer-Server', 'modal.matchmaking': 'Suche Gegner...',
    'modal.matchmakingDesc': 'Durchsuche globale Server', 'modal.searchingTime': 'Suchzeit',
    'modal.opponentFound': 'GEGNER GEFUNDEN!', 'modal.connectingBot': 'Verbinde mit Bot in 30s...',
    'modal.quitMatchSub': 'Aktueller Fortschritt wird nicht gespeichert.', 'modal.forfeitMatchTitle': 'AUFGEBEN?',
    'modal.forfeitMatchSub': 'Verlassen zählt als automatische Niederlage.', 'modal.forfeit': 'AUFGEBEN',
    'match.opponentLeftTitle': 'GEGNER HAT DAS SPIEL VERLASSEN', 'match.opponentLeftDesc': 'Dein Gegner hat die Verbindung getrennt.',
    'match.playAgainUnavailable': 'Revanche nicht verfügbar, da Gegner gegangen ist.',
    'match.waitingOpponent': 'Warte auf Antwort des Gegners...', 'match.changeTeams': 'TEAMS WECHSELN',
    'tournament.selectFormat': 'Turnierformat wählen:', 'tournament.globalCup': 'Global Cup', 'tournament.customCup': 'Eigener Cup',
    'tournament.inDevelopment': 'IN ENTWICKLUNG', 'tournament.onlineWorldCup': 'ONLINE WELTMEISTERSCHAFT',
    'tournament.multiplayerWorldCup': 'Multiplayer Weltmeisterschaften & K.-o.-Turniere', 'tournament.knockoutBrackets': '16-Team K.-o.-Runden',
    'tournament.knockoutBracketsSub': 'Echtzeit-Eliminierungsturniere', 'tournament.globalLeaderboards': 'Globale Saison-Bestenlisten',
    'tournament.globalLeaderboardsSub': 'Ranglistenpunkte und Trophäen gewinnen', 'tournament.exclusiveUnlockables': 'Exklusive Meister-Trikots & Bälle',
    'tournament.exclusiveUnlockablesSub': 'Spezielle Belohnungen für Champions', 'tournament.playOfflineNow': 'OFFLINE-WM JETZT SPIELEN',
    'tournament.selectYourTeam': 'WÄHLE DEIN TEAM', 'tournament.worldCupQualifiedSub': 'FIFA WM • 40 Qualifizierte Nationen (Gruppen A – J)',
    'tournament.searchCountry': 'Land oder Gruppe suchen...', 'tournament.qualifiedNations': 'Qualifizierte Nationen',
    'tournament.tapToSelect': 'Tippen zum Auswählen', 'tournament.selected': 'AUSGEWÄHLT', 'tournament.ovr': 'GES',
    'tournament.randomGroupDraw': 'Zufällige Gruppenauslosung beim Start', 'tournament.tapAnyCountryPrompt': 'TIPPE AUF EIN LAND, UM DEIN TEAM ZU WÄHLEN',
    'tournament.enterWorldCup': 'WM STARTEN (GRUPPEN A - J)', 'tournament.backToMenu': 'Hauptmenü',
    'tournament.forfeitMatch': 'SPIEL AUFGEBEN', 'tournament.continue': 'WEITER ZUR K.-O.-PHASE',
    'tournament.championTitle': '★ WELTMEISTER ★', 'tournament.worldChampions': 'WELTMEISTER',
    'tournament.winnerLiftsCup': 'Du hast die Weltmeisterschaft gewonnen!', 'tournament.freeKickCup': 'Freistoß-Weltmeisterschaft',
    'tournament.roundOf16': 'Achtelfinale', 'tournament.quarterFinals': 'Viertelfinale', 'tournament.semiFinal1': 'Halbfinale 1',
    'tournament.semiFinal2': 'Halbfinale 2', 'tournament.worldFinal': 'Weltmeisterschafts-Finale', 'tournament.awaitingFinal': 'Warte auf Finalist',
    'tournament.fixture': 'Spiel', 'tournament.ft': 'ENDE', 'tournament.tbd': 'OFFEN', 'tournament.cancelTournament': 'Turnier Abbrechen',
    'practice.selectDrill': 'Übung auswählen:', 'practice.freeKick': 'FREISTOSS',
    'practice.freeKickSub': 'Direktes Spiel • Mauer & Winkel', 'practice.instant': 'Sofort',
    'practice.penalty': 'ELFMETER', 'practice.penaltySub': '1v1 vs Torwart • Ohne Zeitlimit', 'practice.random': 'Zufall',
    'practice.exitTitle': 'TRAINING BEENDEN?', 'practice.exitSub': 'Du kannst jederzeit zum Hauptmenü zurückkehren.',
    'practice.exitButton': 'TRAINING BEENDEN', 'survival.title': 'Survival-Arena',
    'survival.subtitle': '3 Leben • Endlose Serien • Duelle', 'survival.arenaTitle': 'SURVIVAL-ARENA',
    'survival.onlineSurvivalTitle': 'ONLINE SURVIVAL 1V1',
    'survival.onlineSurvivalSubtitle': '3 Leben • Live 1v1 Duell • Endlos-Herausforderung',
    'survival.selectGameMode': 'Spielmodus wählen:', 'survival.offlineSurvivalBtn': 'OFFLINE SURVIVAL',
    'survival.onlineDuelBtn': 'ONLINE 1V1 DUELL', 'survival.rulesBtn': 'Regeln',
    'survival.rulesTitle': 'SURVIVAL-REGELN', 'survival.rulesSubtitle': 'Beachte diese 2 Regeln für maximale Torserien:',
    'survival.rule1Title': '3-Leben-System',
    'survival.rule1Desc': 'Jeder startet mit 3 Herzen. Fehlschuss oder Parade kostet 1 Leben. Wer zuerst 0 Leben hat, verliert!',
    'survival.rule2Title': 'Rundenbasiert & 100s Timer',
    'survival.rule2Desc': 'Abwechselnde Freistöße mit 100-Sekunden-Countdown. Triff, um deine Serie auszubauen!',
    'survival.backToRules': 'Zurück zu den Regeln', 'survival.howItWorks': 'So funktioniert es', 'survival.guideBadge': 'SURVIVAL-GUIDE',
    'survival.livesRemaining': 'Verbleibende Leben', 'survival.bestRecord': 'Allzeit-Rekord', 'survival.bestStreak': 'BESTE SERIE',
    'survival.startRun': 'Runde Starten', 'survival.personalRecord': 'Persönlicher Rekord', 'survival.goalStreak': 'TORSERIE',
    'survival.goalsStreak': 'TORSERIE', 'survival.kicks': 'Schüsse', 'survival.duel': 'SURVIVAL 1V1 DUELL',
    'survival.duelSub': 'Online-K.-o.-Duell', 'survival.runEnded': 'RUNDE BEENDET!',
    'survival.challengeComplete': 'Survival-Herausforderung Abgeschlossen', 'survival.finalGoalsStreak': 'Finale Torserie',
    'survival.challengeMode': 'Herausforderungs-Modus', 'survival.reviveExtraLife': 'WIEDERBELEBEN (+1 EXTRA-LEBEN)',
    'survival.endSurvivalTitle': 'SURVIVAL BEENDEN?', 'survival.endSurvival': 'BEENDEN', 'survival.endRun': 'RUNDE BEENDEN',
    'survival.concludeSub': 'Das Spiel wird sofort beendet.', 'survival.currentStreak': 'Aktuelle Serie:',
    'wager.title': 'Wett-Arenen', 'wager.subtitle': 'Wähle deinen Einsatz • Gewinner bekommt alle Münzen!',
    'wager.rookie': 'Anfänger-Arena', 'wager.pro': 'Profi-Arena', 'wager.champion': 'Champion-Arena', 'wager.legend': 'Legenden-Arena',
    'wager.entryFee': 'Eintrittsgebühr', 'wager.entry': 'EINTRITT', 'wager.prizePot': 'Preis-Pott', 'wager.winPot': 'GEWINNER-POTT',
    'wager.highRoller': 'High-Stakes Live-Duell', 'wager.bottomBanner': 'Erkunde Arenen • Hohe Einsätze, doppelte Gewinne!',
    'wager.tapToSelect': 'Tippen zum Wählen', 'wager.playWithCoins': 'Mit Münzen spielen', 'wager.needMoreCoins': 'Brauche mehr Münzen',
    'wager.forfeitWager': 'WETTE AUFGEBEN', 'wager.surrenderTitle': 'WETTE AUFGEBEN?',
    'wager.surrenderSub': 'Aufgeben bedeutet Verlust deines Einsatzes:', 'wager.surrender': 'AUFGEBEN', 'wager.victory': 'WETTGAMPF-SIEG!',
    'wager.coinDuelResults': 'Duell-Ergebnisse', 'wager.drawRefunded': 'UNENTSCHIEDEN • GEBÜHR ERSTATTET',
    'wager.arenaPot': 'Arena-Pott', 'wager.netResult': 'Netto-Ergebnis',
    'wager.opponentLeft': 'Gegner hat die Verbindung getrennt', 'wager.rematch': 'REVANCHE MIT EINSATZ',
    'targetSmash.title': 'ZIEL-SCHIESSEN', 'targetSmash.arcadeBadge': 'NEUER ARCADE-MODUS', 'targetSmash.trickshotSubtitle': 'Ziele & Effektschüsse',
    'targetSmash.selectStage': 'Level (1 - 10)', 'targetSmash.unlocked': 'Freigeschaltet', 'targetSmash.stage': 'Level',
    'targetSmash.objective': 'Ziel', 'targetSmash.highScore': 'Rekord', 'targetSmash.pts': 'PKT', 'targetSmash.distance': 'Distanz',
    'targetSmash.defendersWall': 'Abwehrmauer', 'targetSmash.players': 'Spieler', 'targetSmash.targetScore': 'Zielpunktzahl',
    'targetSmash.targetRequired': 'Erforderliche Punkte', 'targetSmash.playStage': 'LEVEL SPIELEN', 'targetSmash.stageLocked': 'LEVEL GESPERRT',
    'targetSmash.stageCleared': 'LEVEL GESCHAFFT!', 'targetSmash.stageFailed': 'LEVEL FEHLGESCHLAGEN', 'targetSmash.finalScore': 'Endpunktzahl',
    'targetSmash.coinsReward': 'Münzen-Belohnung', 'targetSmash.nextStage': 'NÄCHSTES LEVEL', 'targetSmash.retryStage': 'WIEDERHOLEN',
    'targetSmash.exitToSelect': 'ZUR LEVELAUSWAHL', 'divisions.title': 'Divisions-Liga', 'divisions.titleUpper': 'DIVISIONS-LIGA',
    'divisions.rank': 'Divisions-Rang', 'divisions.titleTarget': 'Titel-Ziel', 'divisions.titleClaimed': 'Titel Gewonnen!',
    'divisions.ptsForTrophy': 'Punkte für Meistertrophäe', 'divisions.seasonFinished': 'Saison Beendet',
    'divisions.promotionAchieved': 'Aufstieg Erreicht!', 'divisions.thisSeason': 'Diese Saison', 'divisions.matchesLeft': 'Verbleibende Spiele',
    'divisions.ptsNeeded': 'Benötigte Punkte', 'divisions.win': 'Sieg', 'divisions.draw': 'Unentschieden', 'divisions.loss': 'Niederlage',
    'divisions.pt': 'PKT', 'divisions.pts': 'PKT', 'divisions.allTime': 'Gesamtbilanz', 'divisions.matchesHistory': 'Spielverlauf',
    'divisions.match': 'Spiel', 'divisions.noMatchesYet': 'Noch keine Spiele in dieser Saison',
    'divisions.noMatchesSub': 'Starte deine Saison unten!', 'divisions.nextMatchChooseOpponent': 'Nächstes Spiel • Gegner Wählen',
    'divisions.whoDoYouWantToPlay': 'Wähle deinen nächsten Gegner:', 'divisions.teamsAvailable': 'Verfügbare Teams',
    'divisions.searchNationalTeam': 'Nationalmannschaft suchen...', 'divisions.playMatchVs': 'SPIEL GEGEN',
    'divisions.opponent': 'Gegner', 'divisions.opponentUpper': 'GEGNER', 'divisions.opponentConnected': 'Gegner Verbunden',
    'divisions.change': 'Ändern', 'divisions.chooseOpponent': 'Gegner Wählen', 'divisions.divShort': 'DIV', 'divisions.of': 'von',
    'divisions.continueTo': 'Weiter zu', 'divisions.next': 'Weiter', 'divisions.findingOpponent': 'Suche Divisions-Gegner...',
    'divisions.matchingWithOnline': 'Suche Spieler in deiner Division',
    'divisions.searchingActivePlayers': 'Suche auf Servern...', 'divisions.matchStartingIn': 'Spiel startet in',
    'divisions.cancelMatchmaking': 'Abbrechen', 'divisions.cancelSearch': 'Suche Abbrechen', 'divisions.wdl': 'S-U-N',
    'division.return': 'Zurück zu Divisionen', 'division.reward': 'Divisions-Belohnung', 'result.victory': 'SIEG!',
    'result.defeat': 'NIEDERLAGE', 'result.draw': 'UNENTSCHIEDEN', 'result.champion': 'WELTMEISTER!', 'result.prizeWon': 'Gewinn Erhalten',
    'result.streak': 'Aktuelle Serie', 'result.newRecord': 'NEUER REKORD!', 'result.coinsEarned': 'Verdiente Münzen',
    'result.finalScore': 'Endergebnis', 'result.totalScore': 'Gesamtpunkte', 'result.wonOnPenalties': 'SIEG IM ELFMETERSCHIESSEN',
    'result.lostOnPenalties': 'NIEDERLAGE IM ELFMETERSCHIESSEN', 'result.survivalVictory': 'SURVIVAL-SIEG!',
    'result.survivalDefeat': 'IN SURVIVAL AUSGESCHIEDEN', 'result.wagerResults': 'Wettspiel-Ergebnisse',
    'rematch.invitationTitle': 'Revanche Angefordert', 'rematch.invitationDesc': 'Gegner möchte eine Revanche!',
    'rematch.accept': 'Revanche Annehmen', 'rematch.decline': 'Ablehnen', 'rematch.starting': 'Starte Revanche...',
    'rematch.survivalRequested': 'Gegner fordert Survival-Revanche!',
    'rematch.survivalDesc': 'Annehmen, um direkt ins 1v1-Duell zurückzukehren!',
    'rematch.wagerChallenge': 'fordert dich zu einer Wett-Revanche heraus!',
    'stats.goals': 'Tore', 'stats.shots': 'Schüsse', 'status.live': 'LIVE', 'status.offline': 'OFFLINE',
    'status.winner': 'GEWINNER', 'status.eliminated': 'AUSGESCHIEDEN', 'status.survived': 'ÜBERLEBT', 'status.left': 'VERLASSEN',
    'status.disconnected': 'GETRENNT', 'store.title': 'Ausrüstungs-Shop', 'store.subtitle': '3D-BALLTEXTUREN & RASENMUSTER',
    'store.balls': 'Bälle', 'store.pitches': 'Rasen', 'store.ballStore': 'BALL-SHOP',
    'store.ballStoreDesc': '3D-Texturen & Pro-Modelle', 'store.pitchStore': 'STADION-SHOP',
    'store.pitchStoreDesc': 'Stadionrasen-Muster', 'store.selectCategory': 'KATEGORIE WÄHLEN',
    'store.unlockedAndEquipped': 'FREIGESCHALTET & AUSGERÜSTET', 'store.owned': 'Im Besitz', 'store.buyFor': 'Kaufen für',
    'store.notEnoughCoins': 'NICHT GENUG MÜNZEN!', 'store.needMore': 'BENÖTIGT', 'store.more': 'MEHR',
    'profile.title': 'Spielerprofil', 'profile.cloudStorageNotice': 'GESPEICHERT ÜBER CRAZYGAMES CLOUD & LOKAL',
    'replays.subtitle': 'Gespeicherte Tor-Highlights ansehen und verwalten', 'replays.savedReplays': 'GESPEICHERTE REPLAYS',
    'replays.savedHighlights': 'GESPEICHERTE HIGHLIGHTS', 'replays.clips': 'Clips', 'replays.savedClips': 'Gespeicherte Clips',
    'replays.noSavedReplays': 'NOCH KEINE REPLAYS', 'replays.noHighlightsTitle': 'KEINE HIGHLIGHTS',
    'replays.noHighlightsDesc': 'Triff im Spiel und tippe beim Replay auf SPEICHERN!', 'replays.playMatchNow': 'JETZT SPIELEN',
    'replays.emptyInstructions': 'Triff ein Tor und tippe oben rechts im Replay auf SPEICHERN!',
    'replays.savedHighlight': 'GESPEICHERTES HIGHLIGHT', 'replays.savedDate': 'DATUM', 'replays.shotDistance': 'SCHUSSDISTANZ',
    'replays.longestStrike': 'Weitester Schuss', 'replays.goalHighlights': 'Tor-Highlights', 'replays.watchReplay': 'REPLAY ANSEHEN',
    'replays.exitReplay': 'REPLAY VERLASSEN', 'replays.deleteReplay': 'Replay Löschen',
    'replays.confirmDelete': 'Dieses Highlight löschen?', 'replays.deleteAllConfirm': 'ALLE REPLAYS LÖSCHEN?',
    'replays.deleteAllDesc': 'Möchtest du wirklich alle Replays löschen?', 'ads.videoReward': 'VIDEO-BELOHNUNG',
    'ads.coinsReward': 'MÜNZEN-BELOHNUNG', 'ads.watchToEarn': 'Werbevideos für +50 Münzen ansehen',
    'ads.instantBoost': 'Sofortiger Münz-Boost', 'ads.integrationFinalizing': 'Werbeintegration wird finalisiert.',
    'ads.unlockAllItems': 'Schalte alle 50 Bälle und 50 Rasenmuster frei!', 'ads.loading': 'LADE WERBUNG...',
    'lang.title': 'Spracheinstellungen', 'lang.subtitle': 'Wähle deine bevorzugte Sprache (16 Sprachen verfügbar)',
    'lang.autoDetect': 'Automatisch Erkannte Sprache', 'lang.currentlyActive': 'DERZEIT AKTIV',
    'lang.sdkSyncTitle': 'CrazyGames-Synchronisation', 'lang.sdkSyncDesc': 'Die Spielsprache passt sich automatisch deinem Portal an',
    'lang.searchPlaceholder': 'Sprache oder Land suchen...', 'lang.tabAll': 'Alle (16)', 'lang.tabPopular': 'Beliebt',
    'lang.tabEurope': 'Europa', 'lang.tabAmericas': 'Amerika', 'lang.tabAsiaMe': 'Asien & NO',
    'lang.noMatches': 'Keine Sprachen gefunden', 'lang.noMatchesDesc': 'Versuche einen anderen Namen oder Region',
    'lang.resetFilters': 'Filter Zurücksetzen'
}

it = {
    'nav.store': 'Negozio', 'nav.profile': 'Profilo', 'nav.replays': 'Replay', 'nav.coins': 'Monete',
    'nav.language': 'Lingua', 'nav.bestStreak': 'Miglior Serie', 'nav.online': 'Online', 'nav.connecting': 'Connessione...',
    'game.title': 'FREE KICK LEGENDS', 'menu.quickPlay': 'PARTITA RAPIDA', 'menu.quickPlaySub': 'PARTITE ONLINE E OFFLINE',
    'menu.survivalMode': 'MODO SOPRAVVIVENZA', 'survival.threeLives': '3 VITE', 'survival.endlessStreak': 'Serie Infinita',
    'survival.best': 'Record', 'survival.streak': 'SERIE', 'survival.onlineAvailable': 'Sopravvivenza 1v1 Online Disponibile',
    'menu.wagerArena': 'ARENA SCOMMESSE', 'wager.betCoinsPot': 'Scommetti Monete • Chi Vince Prende Tutto',
    'wager.onlineDuel': 'Duello 1v1 con Scommessa Online', 'wager.duel': 'DUELLO', 'wager.arena': 'Arena', 'wager.bet': 'Puntata',
    'wager.winnerTakes': 'Il Vincitore Prende', 'wager.prizePot': 'Montepremi', 'menu.worldCup': 'COPPA DEL MONDO FIFA',
    'menu.tournamentFormat': 'Formato Torneo', 'menu.practice': 'ALLENAMENTO', 'menu.practiceSub': 'Allenamento Calci di Punizione',
    'menu.shop': 'NEGOZIO', 'menu.onlineMultiplayer': 'Multigiocatore Online Disponibile',
    'profile.savedReplaysStats': 'REPLAY E STATISTICHE', 'replays.title': 'Replay Salvati',
    'common.coins': 'MONETE', 'common.coinsUpper': 'MONETE', 'common.online': 'ONLINE', 'common.offline': 'OFFLINE',
    'common.back': 'INDIETRO', 'common.backToMenu': 'Torna al Menu', 'common.active': 'ATTIVO', 'common.done': 'FATTO E TORNA',
    'common.close': 'CHIUDI', 'common.gotIt': 'HO CAPITO', 'common.cancel': 'Annulla', 'common.continue': 'CONTINUA',
    'common.exit': 'ESCI', 'common.quit': 'ESCI', 'common.play': 'GIOCA', 'common.saved': 'SALVATO', 'common.goal': 'GOL',
    'common.goals': 'gol', 'common.pts': 'PTI', 'common.you': 'Tu', 'common.opponent': 'Avversario',
    'common.watchAdCoins': 'Guarda video per +50 monete gratis', 'currency.coins': 'MONETE',
    'btn.play': 'Gioca Ora', 'btn.select': 'Seleziona', 'btn.confirm': 'Conferma', 'btn.cancel': 'Annulla',
    'btn.close': 'Chiudi', 'btn.back': 'Indietro', 'btn.continue': 'Continua', 'btn.nextMatch': 'Prossima Partita',
    'btn.returnMenu': 'Menu Principale', 'btn.equip': 'Equipaggia', 'btn.equipped': 'Equipaggiato', 'btn.unlock': 'Sblocca',
    'btn.locked': 'Bloccato', 'btn.saveReplay': 'Salva Replay', 'btn.save': 'SALVA', 'btn.saved': 'SALVATO',
    'btn.skip': 'SALTA', 'btn.playAgain': 'Gioca Ancora', 'btn.watchAd': 'Guarda Video (+50 Monete)', 'btn.freeCoins': 'Monete Gratis',
    'hud.aim': 'Mira', 'hud.power': 'Potenza', 'hud.curve': 'Effetto', 'hud.kick': 'Tiro',
    'hud.stepAim': 'REGOLA LA MIRA', 'hud.stepPower': 'IMPOSTA LA POTENZA', 'hud.stepCurve': 'APPLICA L\'EFFETTO',
    'hud.stepKick': 'ESEGUI IL TIRO', 'hud.shoot': 'TIRA!', 'hud.tapToLock': 'TOCCA PER BLOCCARE',
    'hud.tapToKick': 'TOCCA PER TIRARE', 'hud.goal': 'GOL!', 'hud.saved': 'PARATA!', 'hud.missed': 'FUORI!',
    'hud.wallBlocked': 'BARRIERA HA RESPINTO!', 'hud.postHit': 'PALO!', 'hud.suddenDeath': 'SUDDEN DEATH',
    'hud.goldenGoal': 'GOLDEN GOL', 'hud.penaltyShootout': 'CALCI DI RIGORE', 'hud.turn': 'Turno',
    'hud.yourTurn': 'IL TUO TURNO', 'hud.oppTurn': 'TURNO AVVERSARIO', 'hud.aiThinking': 'IA STA PENSANDO...',
    'hud.aiAiming': 'IA STA MIRANDO...', 'hud.aiStriking': 'IA STA TIRANDO...', 'hud.timer': 'Tempo',
    'hud.matchOver': 'PARTITA FINITA', 'hud.rematch': 'Rivincita', 'hud.exitMatch': 'Esci dalla Partita',
    'hud.resume': 'Riprendi', 'hud.pause': 'Pausa', 'hud.yourTurnPenalty': 'TOCCA A TE TIRARE IL RIGORE',
    'hud.oppPenalty': 'L\'AVVERSARIO TIRA IL RIGORE...', 'hud.aiPenalty': 'L\'IA TIRA IL RIGORE...',
    'hud.playIn': 'GIOCA IN:', 'hud.ballTracking': 'SEGUI PALLA', 'hud.behindGoal': 'DIETRO LA PORTA',
    'hud.meter': 'INDICATORE', 'hud.aiGoalkeeper': 'PORTIERE IA', 'hud.aiStriker': 'ATTACCANTE IA',
    'hud.defenseSim': 'Simulazione Difensiva', 'hud.precisionFK': 'Punizione di Precisione', 'hud.aiming': 'MIRANDO',
    'hud.holdToCharge': 'TIENI PREMUTO PER CARICARE', 'hud.releaseToStrikeInstruction': 'TIENI SPAZIO / SCHERMO • RILASCIA PER TIRARE',
    'hud.weak': 'DEBOLE', 'hud.sweetSpot': 'PERFETTO', 'hud.max': 'MAX', 'hud.chargingPower': 'CARICAMENTO POTENZA...',
    'hud.replay': 'REPLAY', 'game.goal': 'GOL!', 'game.saved': 'PARATA',
    'quickPlay.selectMode': 'Seleziona modalità:', 'quickPlay.ranked': 'Classificata', 'quickPlay.vsAi': 'Vs IA / Locale',
    'country.selectTeams': 'SELEZIONE SQUADRE', 'country.nationalTeams': 'Squadre Nazionali', 'country.teamsAvailable': 'Squadre Disponibili',
    'country.tapToSelect': 'Tocca per scegliere / deselezionare', 'country.myTeam': 'MIA SQUADRA', 'country.opponent': 'AVVERSARIO',
    'country.continueToMatch': 'CONTINUA ALLA PARTITA', 'search.countries': 'Cerca nazione...', 'teamSelect.teams': 'Squadre',
    'teamSelect.searchPlaceholder': 'Cerca nazionale...', 'teamSelect.att': 'ATT', 'teamSelect.def': 'DIF',
    'team.selectNew': 'SCEGLI NUOVA SQUADRA', 'team.selectNewDesc': 'Scegli tra 120 nazionali di tutto il mondo',
    'online.matchTitle': 'PARTITA ONLINE', 'online.matchSubtitle': 'Connettiti e scegli le nazionali in tempo reale:',
    'online.createRoom': 'Crea Stanza Privata', 'online.joinRoom': 'Entra con Codice', 'online.joinRoomTitle': 'ENTRA IN STANZA PRIVATA',
    'online.roomCode': 'Codice Stanza', 'online.copyCode': 'Copia Codice', 'online.codeCopied': 'Copiato!',
    'online.shareCode': 'Condividi questo codice a 4 cifre con un amico:', 'online.enterCode': 'Inserisci il codice a 4 cifre:',
    'online.findMatch': 'Partita Rapida Online', 'online.searchingMatch': 'Ricerca avversari...', 'online.stillSearching': 'Ricerca giocatori attivi...',
    'online.retrySearch': 'Riprova', 'online.cancelSearch': 'Annulla Ricerca', 'online.cancelRoom': 'Annulla Stanza',
    'online.leaveRoom': 'Esci dalla Stanza', 'online.inviteLink': 'Copia Link di Invito', 'online.linkCopied': 'Link Copiato!',
    'online.lookingOpponent': 'Ricerca rivale mondiale...', 'online.pairingAuto': 'Abbinamento in corso...', 'online.ready': 'PRONTO',
    'online.bothSelected': 'Entrambi pronti! Inizio partita...', 'online.selectTeamBelow': 'Scegli la tua squadra sotto:',
    'online.lockedIn': 'CONFERMATO', 'online.selecting': 'Selezione...', 'online.choosing': 'Scelta nazionale...',
    'online.opponentLeft': 'L\'avversario ha lasciato la stanza', 'online.opponentLeftSub': 'Ritorno al menu a breve...',
    'online.roomCreated': 'STANZA CREATA', 'online.room': 'Stanza', 'online.host': 'Host', 'online.guest': 'Ospite',
    'online.firstTurn': 'Tiri per primo', 'online.secondTurn': 'L\'avversario tira per primo',
    'online.matchStartingIn': 'La partita inizia tra', 'online.kickoff': 'CALCIO D\'INIZIO!',
    'online.leaveMatchTitle': 'USCIRE DALLA PARTITA?', 'online.leaveMatchSub': 'Disconnettersi assegnerà la vittoria a tavolino al rivale.',
    'online.leaveMatch': 'ESCI DALLA PARTITA', 'online.leave': 'ESCI', 'online.returnToMenu': 'Torna al Menu',
    'online.returningToMenu': 'Tornando al Menu...', 'online.sessionDisconnected': 'Sessione Disconnessa',
    'online.yourCountry': 'TUA NAZIONALE', 'online.oppCountry': 'NAZIONALE AVVERSARIA',
    'online.waitingOpponent': 'In attesa della scelta avversaria...', 'online.waitingOpponentCode': 'In attesa dell\'amico con il codice...',
    'online.connectSub': 'Server multigiocatore 1v1 in tempo reale', 'modal.matchmaking': 'Ricerca Avversario...',
    'modal.matchmakingDesc': 'Ricerca su server globali', 'modal.searchingTime': 'Tempo Trascorso',
    'modal.opponentFound': 'AVVERSARIO TROVATO!', 'modal.connectingBot': 'Connessione al bot in 30s...',
    'modal.quitMatchSub': 'I progressi non saranno salvati.', 'modal.forfeitMatchTitle': 'ABBANDONARE?',
    'modal.forfeitMatchSub': 'Uscire ora conta come sconfitta automatica.', 'modal.forfeit': 'ABBANDONA',
    'match.opponentLeftTitle': 'L\'AVVERSARIO HA ABBANDONATO', 'match.opponentLeftDesc': 'Il tuo avversario si è disconnesso.',
    'match.playAgainUnavailable': 'Rivincita non disponibile perché l\'avversario è uscito.',
    'match.waitingOpponent': 'In attesa dell\'avversario...', 'match.changeTeams': 'CAMBIA SQUADRE',
    'tournament.selectFormat': 'Seleziona formato:', 'tournament.globalCup': 'Coppa Globale', 'tournament.customCup': 'Coppa Personalizzata',
    'tournament.inDevelopment': 'IN SVILUPPO', 'tournament.onlineWorldCup': 'COPPA DEL MONDO ONLINE',
    'tournament.multiplayerWorldCup': 'Coppe del Mondo & Tabelloni a Eliminazione', 'tournament.knockoutBrackets': 'Tabellone a 16 Squadre',
    'tournament.knockoutBracketsSub': 'Tornei a eliminazione diretta in tempo reale', 'tournament.globalLeaderboards': 'Classifiche Stagionali Globali',
    'tournament.globalLeaderboardsSub': 'Guadagna punti classifica e trofei', 'tournament.exclusiveUnlockables': 'Maglie e Palloni Esclusivi',
    'tournament.exclusiveUnlockablesSub': 'Ricompense speciali per i campioni', 'tournament.playOfflineNow': 'GIOCA MONDIALE OFFLINE',
    'tournament.selectYourTeam': 'SCEGLI LA TUA NAZIONALE', 'tournament.worldCupQualifiedSub': 'Coppa del Mondo FIFA • 40 Nazionali Qualificate (Gruppi A – J)',
    'tournament.searchCountry': 'Cerca nazione o gruppo...', 'tournament.qualifiedNations': 'Nazionali Qualificate',
    'tournament.tapToSelect': 'Tocca per Scegliere', 'tournament.selected': 'SELEZIONATO', 'tournament.ovr': 'TOT',
    'tournament.randomGroupDraw': 'Sorteggio casuale dei gironi all\'avvio', 'tournament.tapAnyCountryPrompt': 'TOCCA UNA NAZIONE PER SCEGLIERE IL TUO TEAM',
    'tournament.enterWorldCup': 'ENTRA NEL MONDIALE (GRUPPI A - J)', 'tournament.backToMenu': 'Torna al Menu',
    'tournament.forfeitMatch': 'ABBANDONA PARTITA', 'tournament.continue': 'CONTINUA ALLA FASE AD ELIMINAZIONE',
    'tournament.championTitle': '★ CAMPIONI DEL MONDO ★', 'tournament.worldChampions': 'CAMPIONI DEL MONDO',
    'tournament.winnerLiftsCup': 'Hai sollevato la Coppa del Mondo!', 'tournament.freeKickCup': 'Torneo Mondiale di Calci di Punizione',
    'tournament.roundOf16': 'Ottavi di Finale', 'tournament.quarterFinals': 'Quarti di Finale', 'tournament.semiFinal1': 'Semifinale 1',
    'tournament.semiFinal2': 'Semifinale 2', 'tournament.worldFinal': 'Finale della Coppa del Mondo', 'tournament.awaitingFinal': 'In attesa del finalista',
    'tournament.fixture': 'Partita', 'tournament.ft': 'FIN', 'tournament.tbd': 'DA DEFINIRE', 'tournament.cancelTournament': 'Annulla Torneo',
    'practice.selectDrill': 'Seleziona esercizio:', 'practice.freeKick': 'CALCIO DI PUNIZIONE',
    'practice.freeKickSub': 'Gioco istantaneo • Barriera e tiri a effetto', 'practice.instant': 'Istantaneo',
    'practice.penalty': 'RIGORE', 'practice.penaltySub': '1v1 vs Portiere • Senza tempo', 'practice.random': 'Casuale',
    'practice.exitTitle': 'USCIRE DALL\'ALLENAMENTO?', 'practice.exitSub': 'Puoi tornare al menu principale quando vuoi.',
    'practice.exitButton': 'ESCI DALL\'ALLENAMENTO', 'survival.title': 'Arena Sopravvivenza',
    'survival.subtitle': '3 Vite • Serie Infinite • Duelli', 'survival.arenaTitle': 'ARENA SOPRAVVIVENZA',
    'survival.onlineSurvivalTitle': 'SOPRAVVIVENZA 1V1 ONLINE',
    'survival.onlineSurvivalSubtitle': '3 Vite • Duello 1v1 dal Vivo • Sfida Serie Infinita',
    'survival.selectGameMode': 'Scegli la modalità:', 'survival.offlineSurvivalBtn': 'SOPRAVVIVENZA OFFLINE',
    'survival.onlineDuelBtn': 'DUELLO 1V1 ONLINE', 'survival.rulesBtn': 'Regole',
    'survival.rulesTitle': 'REGOLE DI SOPRAVVIVENZA', 'survival.rulesSubtitle': 'Segui queste 2 regole per battere il record:',
    'survival.rule1Title': 'Sistema a 3 Vite',
    'survival.rule1Desc': 'Entrambi iniziano con 3 cuori. Un tiro sbagliato o parato toglie 1 vita. Chi perde tutte le vite perde!',
    'survival.rule2Title': 'Duello a Turni e 100s Timer',
    'survival.rule2Desc': 'Punizioni alternate con timer di 100 secondi. Fai gol per allungare la serie e vincere!',
    'survival.backToRules': 'Torna alle Regole', 'survival.howItWorks': 'Come funziona', 'survival.guideBadge': 'GUIDA SOPRAVVIVENZA',
    'survival.livesRemaining': 'Vite Rimaste', 'survival.bestRecord': 'Miglior Record Storico', 'survival.bestStreak': 'MIGLIOR SERIE',
    'survival.startRun': 'Inizia Partita', 'survival.personalRecord': 'Record Personale', 'survival.goalStreak': 'SERIE DI GOL',
    'survival.goalsStreak': 'SERIE DI GOL', 'survival.kicks': 'Tiri', 'survival.duel': 'DUELLO 1V1 SOPRAVVIVENZA',
    'survival.duelSub': 'Eliminazione Diretta Online', 'survival.runEnded': 'FINE PARTITA!',
    'survival.challengeComplete': 'Sfida Sopravvivenza Completata', 'survival.finalGoalsStreak': 'Serie Finale di Gol',
    'survival.challengeMode': 'Modalità Sfida', 'survival.reviveExtraLife': 'REVIVE (+1 VITA EXTRA)',
    'survival.endSurvivalTitle': 'TERMINARE SOPRAVVIVENZA?', 'survival.endSurvival': 'TERMINA', 'survival.endRun': 'TERMINA PARTITA',
    'survival.concludeSub': 'La partita terminerà immediatamente.', 'survival.currentStreak': 'Serie attuale:',
    'wager.title': 'Arene Scommesse', 'wager.subtitle': 'Scegli la tua puntata • Chi vince prende tutto!',
    'wager.rookie': 'Arena Principiante', 'wager.pro': 'Arena Pro', 'wager.champion': 'Arena Campione', 'wager.legend': 'Arena Leggenda',
    'wager.entryFee': 'Quota di Ingresso', 'wager.entry': 'INGRESSO', 'wager.prizePot': 'Montepremi', 'wager.winPot': 'PREMIO VINCITORE',
    'wager.highRoller': 'Duello ad Alte Puntate', 'wager.bottomBanner': 'Esplora le arene • Puntate alte, vincite raddoppiate!',
    'wager.tapToSelect': 'Tocca per scegliere', 'wager.playWithCoins': 'Gioca con le monete', 'wager.needMoreCoins': 'Servono più monete',
    'wager.forfeitWager': 'ABBANDONA SCOMMESSA', 'wager.surrenderTitle': 'ABBANDONARE LA SCOMMESSA?',
    'wager.surrenderSub': 'Abbandonare comporterà la perdita della tua puntata:', 'wager.surrender': 'ABBANDONA',
    'wager.victory': 'VITTORIA NELLA SCOMMESSA!', 'wager.coinDuelResults': 'Risultati del Duello',
    'wager.drawRefunded': 'PAREGGIO • QUOTA RIMBORSATA', 'wager.arenaPot': 'Montepremi Arena', 'wager.netResult': 'Risultato Netto',
    'wager.opponentLeft': 'L\'avversario si è disconnesso', 'wager.rematch': 'RIVINCITA CON SCOMMESSA',
    'targetSmash.title': 'TIRO AL BERSAGLIO', 'targetSmash.arcadeBadge': 'NUOVA MODALITÀ ARCADE',
    'targetSmash.trickshotSubtitle': 'Bersagli e Tiri ad Effetto', 'targetSmash.selectStage': 'Livello (1 - 10)',
    'targetSmash.unlocked': 'Sbloccato', 'targetSmash.stage': 'Livello', 'targetSmash.objective': 'Obiettivo',
    'targetSmash.highScore': 'Record', 'targetSmash.pts': 'PTI', 'targetSmash.distance': 'Distanza',
    'targetSmash.defendersWall': 'Barriera Difensiva', 'targetSmash.players': 'Giocatori', 'targetSmash.targetScore': 'Punteggio Obiettivo',
    'targetSmash.targetRequired': 'Punteggio Richiesto', 'targetSmash.playStage': 'GIOCA LIVELLO', 'targetSmash.stageLocked': 'LIVELLO BLOCCATO',
    'targetSmash.stageCleared': 'LIVELLO SUPERATO!', 'targetSmash.stageFailed': 'LIVELLO FALLITO', 'targetSmash.finalScore': 'Punteggio Finale',
    'targetSmash.coinsReward': 'Ricompensa Monete', 'targetSmash.nextStage': 'PROSSIMO LIVELLO', 'targetSmash.retryStage': 'RIPROVA',
    'targetSmash.exitToSelect': 'TORNA AI LIVELLI', 'divisions.title': 'Lega Divisioni', 'divisions.titleUpper': 'LEGA DIVISIONI',
    'divisions.rank': 'Posizione in Divisione', 'divisions.titleTarget': 'Obiettivo Titolo', 'divisions.titleClaimed': 'Titolo Conquistato!',
    'divisions.ptsForTrophy': 'Punti per il Trofeo', 'divisions.seasonFinished': 'Stagione Finita',
    'divisions.promotionAchieved': 'Promozione Ottenuta!', 'divisions.thisSeason': 'Questa Stagione',
    'divisions.matchesLeft': 'Partite Rimaste', 'divisions.ptsNeeded': 'Punti Necessari', 'divisions.win': 'Vittoria',
    'divisions.draw': 'Pareggio', 'divisions.loss': 'Sconfitta', 'divisions.pt': 'PT', 'divisions.pts': 'PTI',
    'divisions.allTime': 'Bilancio Storico', 'divisions.matchesHistory': 'Cronologia Partite', 'divisions.match': 'Partita',
    'divisions.noMatchesYet': 'Nessuna partita giocata in questa stagione', 'divisions.noMatchesSub': 'Inizia la tua stagione qui sotto!',
    'divisions.nextMatchChooseOpponent': 'Prossima Partita • Scegli Avversario', 'divisions.whoDoYouWantToPlay': 'Scegli il tuo prossimo rivale:',
    'divisions.teamsAvailable': 'Squadre Disponibili', 'divisions.searchNationalTeam': 'Cerca squadra nazionale...',
    'divisions.playMatchVs': 'GIOCA PARTITA CONTRO', 'divisions.opponent': 'Avversario', 'divisions.opponentUpper': 'AVVERSARIO',
    'divisions.opponentConnected': 'Avversario Connesso', 'divisions.change': 'Cambia', 'divisions.chooseOpponent': 'Scegli Avversario',
    'divisions.divShort': 'DIV', 'divisions.of': 'di', 'divisions.continueTo': 'Continua a', 'divisions.next': 'Avanti',
    'divisions.findingOpponent': 'Ricerca Avversario di Divisione...', 'divisions.matchingWithOnline': 'Ricerca tra i giocatori della tua divisione',
    'divisions.searchingActivePlayers': 'Ricerca su server di divisione...', 'divisions.matchStartingIn': 'La partita inizia tra',
    'divisions.cancelMatchmaking': 'Annulla', 'divisions.cancelSearch': 'Annulla Ricerca', 'divisions.wdl': 'V-P-S',
    'division.return': 'Torna a Divisioni', 'division.reward': 'Ricompensa di Divisione', 'result.victory': 'VITTORIA!',
    'result.defeat': 'SCONFITTA', 'result.draw': 'PAREGGIO', 'result.champion': 'CAMPIONE DEL MONDO!', 'result.prizeWon': 'Premio Vinto',
    'result.streak': 'Serie Attuale', 'result.newRecord': 'NUOVO RECORD!', 'result.coinsEarned': 'Monete Guadagnate',
    'result.finalScore': 'Punteggio Finale', 'result.totalScore': 'Punteggio Totale', 'result.wonOnPenalties': 'VITTORIA AI RIGORI',
    'result.lostOnPenalties': 'SCONFITTA AI RIGORI', 'result.survivalVictory': 'VITTORIA IN SOPRAVVIVENZA!',
    'result.survivalDefeat': 'ELIMINATO IN SOPRAVVIVENZA', 'result.wagerResults': 'Risultati della Scommessa',
    'rematch.invitationTitle': 'Rivincita Richiesta', 'rematch.invitationDesc': 'L\'avversario vuole giocare la rivincita!',
    'rematch.accept': 'Accetta Rivincita', 'rematch.decline': 'Rifiuta', 'rematch.starting': 'Avvio Rivincita...',
    'rematch.survivalRequested': 'L\'avversario richiede la Rivincita di Sopravvivenza!',
    'rematch.survivalDesc': 'Accetta per tornare subito al Duello 1v1!',
    'rematch.wagerChallenge': 'ti sfida a una Rivincita con Scommessa!', 'stats.goals': 'Gol', 'stats.shots': 'Tiri',
    'status.live': 'DAL VIVO', 'status.offline': 'OFFLINE', 'status.winner': 'VINCITORE', 'status.eliminated': 'ELIMINATO',
    'status.survived': 'SOPRAVVISSUTO', 'status.left': 'HA ABBANDONATO', 'status.disconnected': 'DISCONNESSO',
    'store.title': 'Negozio Equipaggiamento', 'store.subtitle': 'TEXTURE 3D DI PALLONI E CAMPI',
    'store.balls': 'Palloni', 'store.pitches': 'Campi', 'store.ballStore': 'NEGOZIO PALLONI',
    'store.ballStoreDesc': 'Texture 3D & Modelli Pro', 'store.pitchStore': 'NEGOZIO STADI',
    'store.pitchStoreDesc': 'Tagli del Manto Erboso da Stadio', 'store.selectCategory': 'SELEZIONA CATEGORIA',
    'store.unlockedAndEquipped': 'SBLOCCATO ED EQUIPAGGIATO', 'store.owned': 'Posseduto', 'store.buyFor': 'Acquista per',
    'store.notEnoughCoins': 'NON HAI ABBASTANZA MONETE!', 'store.needMore': 'MANCANO', 'store.more': 'IN PIÙ',
    'profile.title': 'Profilo Giocatore', 'profile.cloudStorageNotice': 'SALVATO SU CLOUD CRAZYGAMES E LOCALE',
    'replays.subtitle': 'Guarda e gestisci i tuoi migliori gol salvati', 'replays.savedReplays': 'REPLAY SALVATI',
    'replays.savedHighlights': 'MOMENTI MIGLIORI SALVATI', 'replays.clips': 'Video', 'replays.savedClips': 'Clip Salvate',
    'replays.noSavedReplays': 'NESSUN REPLAY SALVATO', 'replays.noHighlightsTitle': 'NESSUNA AZIONE SALVATA',
    'replays.noHighlightsDesc': 'Segna un gol in qualsiasi partita e tocca SALVA nel replay!',
    'replays.playMatchNow': 'GIOCA SUBITO', 'replays.emptyInstructions': 'Fai gol e tocca SALVA in alto a destra nel replay per conservarlo qui!',
    'replays.savedHighlight': 'AZIONE SALVATA', 'replays.savedDate': 'DATA', 'replays.shotDistance': 'DISTANZA DEL TIRO',
    'replays.longestStrike': 'Tiro Più Lontano', 'replays.goalHighlights': 'Momenti Salienti', 'replays.watchReplay': 'GUARDA REPLAY',
    'replays.exitReplay': 'ESCI DAL REPLAY', 'replays.deleteReplay': 'Elimina Replay', 'replays.confirmDelete': 'Vuoi eliminare questa azione salvata?',
    'replays.deleteAllConfirm': 'ELIMINARE TUTTI I REPLAY?', 'replays.deleteAllDesc': 'Sei sicuro di voler cancellare tutti i replay?',
    'ads.videoReward': 'RICOMPENSA VIDEO', 'ads.coinsReward': 'RICOMPENSA MONETE', 'ads.watchToEarn': 'Guarda video per guadagnare +50 monete',
    'ads.instantBoost': 'Incremento Istantaneo di Monete', 'ads.integrationFinalizing': 'L\'integrazione pubblicitaria è in fase di completamento.',
    'ads.unlockAllItems': 'Sblocca tutti i 50 palloni e i 50 manti erbosi!', 'ads.loading': 'CARICAMENTO PUBBLICITÀ...',
    'lang.title': 'Impostazioni Lingua', 'lang.subtitle': 'Scegli la tua lingua (16 lingue supportate)',
    'lang.autoDetect': 'Lingua Rilevata Automaticamente', 'lang.currentlyActive': 'ATTUALMENTE ATTIVA',
    'lang.sdkSyncTitle': 'Sincronizzazione CrazyGames', 'lang.sdkSyncDesc': 'La lingua del gioco si sincronizza automaticamente con il tuo portale',
    'lang.searchPlaceholder': 'Cerca lingua o nazione...', 'lang.tabAll': 'Tutte (16)', 'lang.tabPopular': 'Popolari',
    'lang.tabEurope': 'Europa', 'lang.tabAmericas': 'Americhe', 'lang.tabAsiaMe': 'Asia & MO',
    'lang.noMatches': 'Nessuna lingua trovata', 'lang.noMatchesDesc': 'Prova a digitare un altro nome di lingua o nazione',
    'lang.resetFilters': 'Reimposta Filtri'
}

print("DE and IT loaded.")
