# -*- coding: utf-8 -*-
# Arabic (ar) & Simplified Chinese (zh)

ar = {
    'nav.store': 'المتجر', 'nav.profile': 'الملف الشخصي', 'nav.replays': 'الإعادة', 'nav.coins': 'العملات',
    'nav.language': 'اللغة', 'nav.bestStreak': 'أفضل سلسلة', 'nav.online': 'أونلاين', 'nav.connecting': 'جارٍ الاتصال...',
    'game.title': 'أساطير الضربات الحرة', 'menu.quickPlay': 'مباراة سريعة', 'menu.quickPlaySub': 'مباريات أونلاين وأوفلاين',
    'menu.survivalMode': 'طور البقاء', 'survival.threeLives': '3 محاولات', 'survival.endlessStreak': 'سلسلة لا نهائية',
    'survival.best': 'الأفضل', 'survival.streak': 'السلسلة', 'survival.onlineAvailable': 'تحدي البقاء 1 ضد 1 أونلاين متاح',
    'menu.wagerArena': 'ساحة الرهان', 'wager.betCoinsPot': 'راهن بالعملات • الفائز يأخذ كل شيء',
    'wager.onlineDuel': 'مبارزة رهان 1 ضد 1 أونلاين', 'wager.duel': 'مبارزة', 'wager.arena': 'الساحة', 'wager.bet': 'الرهان',
    'wager.winnerTakes': 'الفائز يحصل على', 'wager.prizePot': 'مجموع الجوائز', 'menu.worldCup': 'كأس العالم FIFA',
    'menu.tournamentFormat': 'نظام البطولة', 'menu.practice': 'تدريب', 'menu.practiceSub': 'تدريب الضربات الحرة',
    'menu.shop': 'المتجر', 'menu.onlineMultiplayer': 'اللعب الجماعي أونلاين متاح',
    'profile.savedReplaysStats': 'الإعادات والإحصائيات', 'replays.title': 'الإعادات المحفوظة',
    'common.coins': 'عملات', 'common.coinsUpper': 'عملات', 'common.online': 'أونلاين', 'common.offline': 'أوفلاين',
    'common.back': 'رجوع', 'common.backToMenu': 'العودة للقائمة', 'common.active': 'نشط', 'common.done': 'تم',
    'common.close': 'إغلاق', 'common.gotIt': 'فهمت', 'common.cancel': 'إلغاء', 'common.continue': 'متابعة',
    'common.exit': 'خروج', 'common.quit': 'إنهاء', 'common.play': 'لعب', 'common.saved': 'تم الحفظ', 'common.goal': 'هدف',
    'common.goals': 'أهداف', 'common.pts': 'نقاط', 'common.you': 'أنت', 'common.opponent': 'الخصم',
    'common.watchAdCoins': 'شاهد إعلاناً للحصول على +50 عملة مجاناً', 'currency.coins': 'عملات',
    'btn.play': 'العب الآن', 'btn.select': 'تحديد', 'btn.confirm': 'تأكيد', 'btn.cancel': 'إلغاء',
    'btn.close': 'إغلاق', 'btn.back': 'رجوع', 'btn.continue': 'متابعة', 'btn.nextMatch': 'المباراة التالية',
    'btn.returnMenu': 'القائمة الرئيسية', 'btn.equip': 'تجهيز', 'btn.equipped': 'مجهّز', 'btn.unlock': 'فتح',
    'btn.locked': 'مقفل', 'btn.saveReplay': 'حفظ الإعادة', 'btn.save': 'حفظ', 'btn.saved': 'تم الحفظ',
    'btn.skip': 'تخطي', 'btn.playAgain': 'العب مجدداً', 'btn.watchAd': 'مشاهدة فيديو (+50 عملة)', 'btn.freeCoins': 'عملات مجانية',
    'hud.aim': 'التصويب', 'hud.power': 'القوة', 'hud.curve': 'الدوران', 'hud.kick': 'تسديد',
    'hud.stepAim': 'اضبط زاوية التسديد', 'hud.stepPower': 'حدد قوة التسديد', 'hud.stepCurve': 'طبق دوران الكرة',
    'hud.stepKick': 'سدد الكرة', 'hud.shoot': 'تسديد!', 'hud.tapToLock': 'انقر للتثبيت',
    'hud.tapToKick': 'انقر للتسديد', 'hud.goal': 'هدف!', 'hud.saved': 'تصدي رائع!', 'hud.missed': 'خارج المرمى!',
    'hud.wallBlocked': 'الحائط صد الكرة!', 'hud.postHit': 'في القائم!', 'hud.suddenDeath': 'الموت المفاجئ',
    'hud.goldenGoal': 'الهدف الذهبي', 'hud.penaltyShootout': 'ركلات الترجيح', 'hud.turn': 'الدور',
    'hud.yourTurn': 'دورك الآن', 'hud.oppTurn': 'دور الخصم', 'hud.aiThinking': 'الذكاء الاصطناعي يفكر...',
    'hud.aiAiming': 'الذكاء الاصطناعي يصوب...', 'hud.aiStriking': 'الذكاء الاصطناعي يسدد...', 'hud.timer': 'الوقت',
    'hud.matchOver': 'انتهت المباراة', 'hud.rematch': 'مباراة ثأرية', 'hud.exitMatch': 'مغادرة المباراة',
    'hud.resume': 'استئناف', 'hud.pause': 'إيقاف مؤقت', 'hud.yourTurnPenalty': 'دورك لتسديد ركلة الجزاء',
    'hud.oppPenalty': 'الخصم يسدد ركلة الجزاء...', 'hud.aiPenalty': 'الذكاء الاصطناعي يسدد ركلة الجزاء...',
    'hud.playIn': 'زاوية الكاميرا:', 'hud.ballTracking': 'تتبع الكرة', 'hud.behindGoal': 'خلف المرمى',
    'hud.meter': 'المقياس', 'hud.aiGoalkeeper': 'حارس الذكاء الاصطناعي', 'hud.aiStriker': 'مهاجم الذكاء الاصطناعي',
    'hud.defenseSim': 'محاكاة الدفاع', 'hud.precisionFK': 'ضربة حرة دقيقة', 'hud.aiming': 'جارٍ التصويب',
    'hud.holdToCharge': 'اضغط مطولاً لزيادة القوة', 'hud.releaseToStrikeInstruction': 'اضغط باستمرار على المسافة / الشاشة • اترك للتسديد',
    'hud.weak': 'ضعيف', 'hud.sweetSpot': 'مثالي', 'hud.max': 'الحد الأقصى', 'hud.chargingPower': 'جارٍ شحن القوة...',
    'hud.replay': 'الإعادة', 'game.goal': 'هدف!', 'game.saved': 'تصدي',
    'quickPlay.selectMode': 'اختر نوع المباراة:', 'quickPlay.ranked': 'مصنف', 'quickPlay.vsAi': 'ضد الذكاء الاصطناعي / محلي',
    'country.selectTeams': 'اختيار الفرق', 'country.nationalTeams': 'المنتخبات الوطنية', 'country.teamsAvailable': 'المنتخبات المتاحة',
    'country.tapToSelect': 'انقر للاختيار', 'country.myTeam': 'فريقي', 'country.opponent': 'الخصم',
    'country.continueToMatch': 'الانتقال إلى المباراة', 'search.countries': 'ابحث عن دولة...', 'teamSelect.teams': 'الفرق',
    'teamSelect.searchPlaceholder': 'ابحث عن منتخب...', 'teamSelect.att': 'هجوم', 'teamSelect.def': 'دفاع',
    'team.selectNew': 'اختر فريقاً جديداً', 'team.selectNewDesc': 'اختر من بين 120 منتخباً وطنياً حول العالم',
    'online.matchTitle': 'مباراة أونلاين', 'online.matchSubtitle': 'اتصل مباشرة واختر منتخبك مباشرة:',
    'online.createRoom': 'إنشاء غرفة خاصة', 'online.joinRoom': 'الانضمام بواسطة رمز', 'online.joinRoomTitle': 'الانضمام إلى غرفة',
    'online.roomCode': 'رمز الغرفة', 'online.copyCode': 'نسخ الرمز', 'online.codeCopied': 'تم النسخ!',
    'online.shareCode': 'شارك هذا الرمز المكون من 4 أرقام مع صديقك:', 'online.enterCode': 'أدخل رمز الغرفة المكون من 4 أرقام:',
    'online.findMatch': 'بحث سريع عن خصم', 'online.searchingMatch': 'جارٍ البحث عن خصم...', 'online.stillSearching': 'جارٍ البحث عن لاعبين نشطين...',
    'online.retrySearch': 'إعادة المحاولة', 'online.cancelSearch': 'إلغاء البحث', 'online.cancelRoom': 'إلغاء الغرفة',
    'online.leaveRoom': 'مغادرة الغرفة', 'online.inviteLink': 'نسخ رابط الدعوة', 'online.linkCopied': 'تم نسخ الرابط!',
    'online.lookingOpponent': 'جارٍ البحث عن منافس حول العالم...', 'online.pairingAuto': 'جارٍ الاتصال باللاعب...', 'online.ready': 'جاهز',
    'online.bothSelected': 'كلاكما جاهز! تبدأ المباراة...', 'online.selectTeamBelow': 'اختر فريقك من الأسفل:',
    'online.lockedIn': 'تم التأكيد', 'online.selecting': 'جارٍ الاختيار...', 'online.choosing': 'يختار المنتخب...',
    'online.opponentLeft': 'غادر الخصم الغرفة', 'online.opponentLeftSub': 'العودة إلى القائمة خلال لحظات...',
    'online.roomCreated': 'تم إنشاء الغرفة', 'online.room': 'غرفة', 'online.host': 'المضيف', 'online.guest': 'الضيف',
    'online.firstTurn': 'أنت تسدد أولاً', 'online.secondTurn': 'الخصم يسدد أولاً',
    'online.matchStartingIn': 'تبدأ المباراة خلال', 'online.kickoff': 'ضربة البداية!',
    'online.leaveMatchTitle': 'مغادرة المباراة؟', 'online.leaveMatchSub': 'المغادرة الآن ستعتبر فوزاً سهلاً لخصمك.',
    'online.leaveMatch': 'مغادرة المباراة', 'online.leave': 'مغادرة', 'online.returnToMenu': 'القائمة الرئيسية',
    'online.returningToMenu': 'جارٍ العودة للقائمة...', 'online.sessionDisconnected': 'تم قطع الاتصال',
    'online.yourCountry': 'منتخبك', 'online.oppCountry': 'منتخب الخصم',
    'online.waitingOpponent': 'في انتظار اختيار الخصم...', 'online.waitingOpponentCode': 'في انتظار انضمام الصديق...',
    'online.connectSub': 'سيرفرات مباريات 1 ضد 1 مباشرة حول العالم', 'modal.matchmaking': 'جارٍ البحث عن خصم...',
    'modal.matchmakingDesc': 'البحث عبر السيرفرات العالمية', 'modal.searchingTime': 'وقت البحث',
    'modal.opponentFound': 'تم العثور على خصم!', 'modal.connectingBot': 'الاتصال بالبوت بعد 30 ثانية...',
    'modal.quitMatchSub': 'لن يتم حفظ تقدم المباراة الحالية.', 'modal.forfeitMatchTitle': 'هل تريد الاستسلام؟',
    'modal.forfeitMatchSub': 'الخروج الآن يعتبر هزيمة تلقائية.', 'modal.forfeit': 'استسلام',
    'match.opponentLeftTitle': 'غادر الخصم المباراة', 'match.opponentLeftDesc': 'انقطع اتصال خصمك بالمباراة.',
    'match.playAgainUnavailable': 'لا يمكن إعادة اللعب لأن الخصم غادر.',
    'match.waitingOpponent': 'في انتظار رد الخصم...', 'match.changeTeams': 'تغيير الفرق',
    'tournament.selectFormat': 'اختر نظام البطولة:', 'tournament.globalCup': 'الكأس العالمي', 'tournament.customCup': 'كأس مخصص',
    'tournament.inDevelopment': 'قيد التطوير', 'tournament.onlineWorldCup': 'كأس العالم أونلاين',
    'tournament.multiplayerWorldCup': 'كؤوس العالم ومباريات خروج المغلوب الجماعية', 'tournament.knockoutBrackets': 'أدوار إقصائية لـ 16 فريقاً',
    'tournament.knockoutBracketsSub': 'بطولات خروج المغلوب المباشرة', 'tournament.globalLeaderboards': 'لوحة صدارة المواسم العالمية',
    'tournament.globalLeaderboardsSub': 'احصل على نقاط التصنيف والكؤوس', 'tournament.exclusiveUnlockables': 'قمصان وكرات حصرية للأبطال',
    'tournament.exclusiveUnlockablesSub': 'مكافآت مميزة للفائزين بالبطولة', 'tournament.playOfflineNow': 'العب كأس العالم أوفلاين',
    'tournament.selectYourTeam': 'اختر منتخبك', 'tournament.worldCupQualifiedSub': 'كأس العالم FIFA • 40 منتخباً متأهلاً (المجموعات A – J)',
    'tournament.searchCountry': 'ابحث عن دولة أو مجموعة...', 'tournament.qualifiedNations': 'المنتخبات المتأهلة',
    'tournament.tapToSelect': 'انقر للاختيار', 'tournament.selected': 'تم الاختيار', 'tournament.ovr': 'المستوى',
    'tournament.randomGroupDraw': 'قرعة عشوائية للمجموعات عند البدء', 'tournament.tapAnyCountryPrompt': 'انقر على أي دولة لاختيار فريقك',
    'tournament.enterWorldCup': 'دخول كأس العالم (المجموعات A - J)', 'tournament.backToMenu': 'القائمة الرئيسية',
    'tournament.forfeitMatch': 'الانسحاب من المباراة', 'tournament.continue': 'الانتقال إلى الأدوار الإقصائية',
    'tournament.championTitle': '★ أبطال العالم ★', 'tournament.worldChampions': 'بطل العالم',
    'tournament.winnerLiftsCup': 'لقد رفعت كأس العالم عالياً!', 'tournament.freeKickCup': 'بطولة العالم للضربات الحرة',
    'tournament.roundOf16': 'دور الـ 16', 'tournament.quarterFinals': 'ربع النهائي', 'tournament.semiFinal1': 'نصف النهائي 1',
    'tournament.semiFinal2': 'نصف النهائي 2', 'tournament.worldFinal': 'نهائي كأس العالم', 'tournament.awaitingFinal': 'في انتظار الطرف الآخر',
    'tournament.fixture': 'المواجهة', 'tournament.ft': 'نهاية', 'tournament.tbd': 'يحدد لاحقاً', 'tournament.cancelTournament': 'إلغاء البطولة',
    'practice.selectDrill': 'اختر نوع التدريب:', 'practice.freeKick': 'ضربة حرة',
    'practice.freeKickSub': 'لعب فوري • الحائط البشري والزوايا الصعبة', 'practice.instant': 'فوري',
    'practice.penalty': 'ركلة جزاء', 'practice.penaltySub': '1 ضد 1 أمام الحارس • بدون وقت محدد', 'practice.random': 'عشوائي',
    'practice.exitTitle': 'مغادرة التدريب؟', 'practice.exitSub': 'يمكنك العودة للقائمة الرئيسية في أي وقت.',
    'practice.exitButton': 'إنهاء التدريب', 'survival.title': 'ساحة البقاء',
    'survival.subtitle': '3 محاولات • سلاسل أهداف لا نهائية • مبارزات', 'survival.arenaTitle': 'ساحة البقاء',
    'survival.onlineSurvivalTitle': 'تحدي البقاء 1 ضد 1 أونلاين',
    'survival.onlineSurvivalSubtitle': '3 محاولات • مبارزة 1 ضد 1 مباشرة • تحدي أطول سلسلة أهداف',
    'survival.selectGameMode': 'اختر طور اللعب:', 'survival.offlineSurvivalBtn': 'طور البقاء أوفلاين',
    'survival.onlineDuelBtn': 'مبارزة 1 ضد 1 أونلاين', 'survival.rulesBtn': 'القوانين',
    'survival.rulesTitle': 'قواعد طور البقاء', 'survival.rulesSubtitle': 'اتبع هاتين القاعدتين لتحقيق أعلى رقم قياسي:',
    'survival.rule1Title': 'نظام الـ 3 محاولات',
    'survival.rule1Desc': 'يبدأ كل لاعب بـ 3 قلوب. إهدار التسديدة أو تصدي الحارس يخصم قلباً. من ينفد منه القلوب أولاً يخسر!',
    'survival.rule2Title': 'تسديد بالتناوب ومؤقت 100 ثانية',
    'survival.rule2Desc': 'تسديد الضربات الحرة بالتناوب مع مؤقت 100 ثانية. سجل الأهداف لزيادة سلسلة انتصاراتك!',
    'survival.backToRules': 'العودة للقواعد', 'survival.howItWorks': 'كيف يعمل', 'survival.guideBadge': 'دليل البقاء',
    'survival.livesRemaining': 'المحاولات المتبقية', 'survival.bestRecord': 'الرقم القياسي التاريخي', 'survival.bestStreak': 'أفضل سلسلة',
    'survival.startRun': 'بدء المحاولة', 'survival.personalRecord': 'رقمك القياسي', 'survival.goalStreak': 'سلسلة الأهداف',
    'survival.goalsStreak': 'سلسلة الأهداف', 'survival.kicks': 'التسديدات', 'survival.duel': 'مبارزة البقاء 1 ضد 1',
    'survival.duelSub': 'مواجهة إقصائية أونلاين', 'survival.runEnded': 'انتهت المحاولة!',
    'survival.challengeComplete': 'اكتمل تحدي البقاء', 'survival.finalGoalsStreak': 'سلسلة الأهداف النهائية',
    'survival.challengeMode': 'طور التحدي', 'survival.reviveExtraLife': 'إنعاش (+1 محاولة إضافية)',
    'survival.endSurvivalTitle': 'إنهاء طور البقاء؟', 'survival.endSurvival': 'إنهاء', 'survival.endRun': 'إنهاء المحاولة',
    'survival.concludeSub': 'سيتم إيقاف المباراة فوراً.', 'survival.currentStreak': 'السلسلة الحالية:',
    'wager.title': 'ساحات الرهان', 'wager.subtitle': 'اختر قيمة الرهان • الفائز يأخذ كل العملات!',
    'wager.rookie': 'ساحة المبتدئين', 'wager.pro': 'ساحة المحترفين', 'wager.champion': 'ساحة الأبطال', 'wager.legend': 'ساحة الأساطير',
    'wager.entryFee': 'رسوم الدخول', 'wager.entry': 'دخول', 'wager.prizePot': 'مجموع الجوائز', 'wager.winPot': 'جائزة الفائز',
    'wager.highRoller': 'مبارزة الرهانات العالية', 'wager.bottomBanner': 'استكشف الساحات • رهانات أعلى، أرباح مضاعفة!',
    'wager.tapToSelect': 'انقر للاختيار', 'wager.playWithCoins': 'العب بالعملات', 'wager.needMoreCoins': 'تحتاج المزيد من العملات',
    'wager.forfeitWager': 'الانسحاب من الرهان', 'wager.surrenderTitle': 'هل تريد الانسحاب؟',
    'wager.surrenderSub': 'الانسحاب سيكلفك خسارة العملات المرهونة:', 'wager.surrender': 'استسلام', 'wager.victory': 'انتصار في الرهان!',
    'wager.coinDuelResults': 'نتائج المبارزة', 'wager.drawRefunded': 'تعادل • تم استرداد رسوم الدخول',
    'wager.arenaPot': 'مجموع الساحة', 'wager.netResult': 'الربح الصافي',
    'wager.opponentLeft': 'غادر الخصم الساحة', 'wager.rematch': 'إعادة برهان',
    'targetSmash.title': 'إصابة الأهداف', 'targetSmash.arcadeBadge': 'طور أركيد جديد',
    'targetSmash.trickshotSubtitle': 'إصابة الأهداف والتسديدات المقوسة', 'targetSmash.selectStage': 'المرحلة (1 - 10)',
    'targetSmash.unlocked': 'مفتوح', 'targetSmash.stage': 'مرحلة', 'targetSmash.objective': 'الهدف',
    'targetSmash.highScore': 'الرقم القياسي', 'targetSmash.pts': 'نقاط', 'targetSmash.distance': 'المسافة',
    'targetSmash.defendersWall': 'حائط الصد', 'targetSmash.players': 'لاعبين', 'targetSmash.targetScore': 'النقاط المطلوبة',
    'targetSmash.targetRequired': 'النقاط اللازمة', 'targetSmash.playStage': 'لعب المرحلة', 'targetSmash.stageLocked': 'المرحلة مغلقة',
    'targetSmash.stageCleared': 'تم اجتياز المرحلة!', 'targetSmash.stageFailed': 'فشلت المرحلة', 'targetSmash.finalScore': 'النتيجة النهائية',
    'targetSmash.coinsReward': 'مكافأة العملات', 'targetSmash.nextStage': 'المرحلة التالية', 'targetSmash.retryStage': 'إعادة المحاولة',
    'targetSmash.exitToSelect': 'إلى قائمة المراحل', 'divisions.title': 'دوري الدرجات', 'divisions.titleUpper': 'دوري الدرجات',
    'divisions.rank': 'ترتيب الدرجة', 'divisions.titleTarget': 'هدف اللقب', 'divisions.titleClaimed': 'تم حسم اللقب!',
    'divisions.ptsForTrophy': 'نقاط الفوز بالكأس', 'divisions.seasonFinished': 'انتهى الموسم',
    'divisions.promotionAchieved': 'تم الصعود بنجاح!', 'divisions.thisSeason': 'هذا الموسم',
    'divisions.matchesLeft': 'المباريات المتبقية', 'divisions.ptsNeeded': 'النقاط المطلوبة', 'divisions.win': 'فوز',
    'divisions.draw': 'تعادل', 'divisions.loss': 'خسارة', 'divisions.pt': 'نقطة', 'divisions.pts': 'نقاط',
    'divisions.allTime': 'السجل التاريخي', 'divisions.matchesHistory': 'سجل المباريات', 'divisions.match': 'مباراة',
    'divisions.noMatchesYet': 'لم تلعب أي مباراة في هذا الموسم بعد', 'divisions.noMatchesSub': 'ابدأ موسمك من الأسفل!',
    'divisions.nextMatchChooseOpponent': 'المباراة القادمة • اختر الخصم', 'divisions.whoDoYouWantToPlay': 'اختر خصمك القادم:',
    'divisions.teamsAvailable': 'المنتخبات المتاحة', 'divisions.searchNationalTeam': 'ابحث عن منتخب وطني...',
    'divisions.playMatchVs': 'العب مباراة ضد', 'divisions.opponent': 'الخصم', 'divisions.opponentUpper': 'الخصم',
    'divisions.opponentConnected': 'تم اتصال الخصم', 'divisions.change': 'تغيير', 'divisions.chooseOpponent': 'اختيار الخصم',
    'divisions.divShort': 'درجة', 'divisions.of': 'من', 'divisions.continueTo': 'الانتقال إلى', 'divisions.next': 'التالي',
    'divisions.findingOpponent': 'جارٍ البحث عن منافس في الدرجة...', 'divisions.matchingWithOnline': 'مطابقة مع لاعبين في نفس درجتك',
    'divisions.searchingActivePlayers': 'جارٍ البحث في سيرفرات الدوري...', 'divisions.matchStartingIn': 'تبدأ المباراة خلال',
    'divisions.cancelMatchmaking': 'إلغاء', 'divisions.cancelSearch': 'إلغاء البحث', 'divisions.wdl': 'ف-ت-خ',
    'division.return': 'العودة للدوري', 'division.reward': 'مكافأة الدرجة', 'result.victory': 'انتصار!',
    'result.defeat': 'هزيمة', 'result.draw': 'تعادل', 'result.champion': 'بطل العالم!', 'result.prizeWon': 'الجائزة المحصلة',
    'result.streak': 'السلسلة الحالية', 'result.newRecord': 'رقم قياسي جديد!', 'result.coinsEarned': 'العملات المكتسبة',
    'result.finalScore': 'النتيجة النهائية', 'result.totalScore': 'مجموع النقاط', 'result.wonOnPenalties': 'فوز بركلات الترجيح',
    'result.lostOnPenalties': 'خسارة بركلات الترجيح', 'result.survivalVictory': 'فوز في طور البقاء!',
    'result.survivalDefeat': 'تم الإقصاء من طور البقاء', 'result.wagerResults': 'نتائج الرهان',
    'rematch.invitationTitle': 'طلب مباراة ثأرية', 'rematch.invitationDesc': 'الخصم يريد خوض مباراة أخرى!',
    'rematch.accept': 'قبول التحدي', 'rematch.decline': 'رفض', 'rematch.starting': 'بدء المباراة الثأرية...',
    'rematch.survivalRequested': 'الخصم يطلب إعادة تحدي البقاء!',
    'rematch.survivalDesc': 'اقبل للعودة فوراً لمبارزة 1 ضد 1!',
    'rematch.wagerChallenge': 'يتحداك في مباراة رهان جديدة!', 'stats.goals': 'الأهداف', 'stats.shots': 'التسديدات',
    'status.live': 'مباشر', 'status.offline': 'أوفلاين', 'status.winner': 'الفائز', 'status.eliminated': 'تم إقصاؤه',
    'status.survived': 'نجا', 'status.left': 'غادر', 'status.disconnected': 'انقطع الاتصال',
    'store.title': 'متجر المعدات', 'store.subtitle': 'كرات ثلاثية الأبعاد وأنماط عشب الملاعب',
    'store.balls': 'الكرات', 'store.pitches': 'الملاعب', 'store.ballStore': 'متجر الكرات',
    'store.ballStoreDesc': 'تصاميم ثلاثية الأبعاد وكرات احترافية', 'store.pitchStore': 'متجر الملاعب',
    'store.pitchStoreDesc': 'قصات عشب الملاعب العالمية', 'store.selectCategory': 'اختر الفئة',
    'store.unlockedAndEquipped': 'مفتوح ومجهز', 'store.owned': 'مملوك', 'store.buyFor': 'شراء مقابل',
    'store.notEnoughCoins': 'العملات غير كافية!', 'store.needMore': 'تحتاج إلى', 'store.more': 'إضافية',
    'profile.title': 'ملف اللاعب', 'profile.cloudStorageNotice': 'حفظ تلقائي على سحابة CRAZYGAMES ومحلياً',
    'replays.subtitle': 'شاهد ونظم أفضل أهدافك الرائعة المسجلة', 'replays.savedReplays': 'الإعادات المحفوظة',
    'replays.savedHighlights': 'أبرز اللقطات المحفوظة', 'replays.clips': 'مقاطع', 'replays.savedClips': 'مقاطع محفوظة',
    'replays.noSavedReplays': 'لا توجد إعادات محفوظة حتى الآن', 'replays.noHighlightsTitle': 'لا توجد لقطات',
    'replays.noHighlightsDesc': 'سجل هدفاً رائعاً في المباراة وانقر على حفظ أثناء الإعادة!',
    'replays.playMatchNow': 'العب مباراة الآن', 'replays.emptyInstructions': 'سجل هدفاً مميزاً واضغط على حفظ في أعلى يمين شاشة الإعادة لتجده هنا!',
    'replays.savedHighlight': 'لقطة محفوظة', 'replays.savedDate': 'التاريخ', 'replays.shotDistance': 'مسافة التسديدة',
    'replays.longestStrike': 'أبعد هدف', 'replays.goalHighlights': 'أبرز الأهداف', 'replays.watchReplay': 'مشاهدة الإعادة',
    'replays.exitReplay': 'الخروج من الإعادة', 'replays.deleteReplay': 'حذف الإعادة',
    'replays.confirmDelete': 'هل تريد حذف هذه اللقطة المحفوظة؟', 'replays.deleteAllConfirm': 'حذف جميع الإعادات؟',
    'replays.deleteAllDesc': 'هل أنت متأكد من رغبتك في مسح سجل الإعادات بالكامل؟', 'ads.videoReward': 'مكافأة الفيديو',
    'ads.coinsReward': 'مكافأة العملات', 'ads.watchToEarn': 'شاهد إعلانات فيديو لكسب +50 عملة',
    'ads.instantBoost': 'تعزيز فوري للعملات', 'ads.integrationFinalizing': 'جارٍ تجهيز نظام الإعلانات.',
    'ads.unlockAllItems': 'افتح جميع الكرات الخمسين وأنماط العشب الخمسين!', 'ads.loading': 'جارٍ تحميل الإعلان...',
    'lang.title': 'إعدادات اللغة', 'lang.subtitle': 'اختر لغتك المفضلة (تدعم اللعبة 16 لغة عالمية)',
    'lang.autoDetect': 'اللغة المكتشفة تلقائياً', 'lang.currentlyActive': 'نشطة حالياً',
    'lang.sdkSyncTitle': 'مزامنة CrazyGames', 'lang.sdkSyncDesc': 'تتطابق لغة اللعبة تلقائياً مع حسابك في المنصة',
    'lang.searchPlaceholder': 'ابحث عن لغة أو دولة...', 'lang.tabAll': 'الكل (16)', 'lang.tabPopular': 'شائعة',
    'lang.tabEurope': 'أوروبا', 'lang.tabAmericas': 'الأمريكتان', 'lang.tabAsiaMe': 'آسيا والشرق الأوسط',
    'lang.noMatches': 'لم يتم العثور على لغات مطابقة', 'lang.noMatchesDesc': 'جرب كتابة اسم لغة أو دولة أخرى',
    'lang.resetFilters': 'إعادة ضبط الفلاتر'
}

zh = {
    'nav.store': '商店', 'nav.profile': '个人资料', 'nav.replays': '精彩回放', 'nav.coins': '金币',
    'nav.language': '语言', 'nav.bestStreak': '最高连胜', 'nav.online': '在线', 'nav.connecting': '连接中...',
    'game.title': '任意球传奇', 'menu.quickPlay': '快速比赛', 'menu.quickPlaySub': '在线与离线对战',
    'menu.survivalMode': '生存模式', 'survival.threeLives': '3条命', 'survival.endlessStreak': '无尽连进挑战',
    'survival.best': '纪录', 'survival.streak': '连胜', 'survival.onlineAvailable': '支持在线1v1生存对决',
    'menu.wagerArena': '下注竞技场', 'wager.betCoinsPot': '押注金币 • 胜者通吃',
    'wager.onlineDuel': '在线1v1金币下注对决', 'wager.duel': '对决', 'wager.arena': '竞技场', 'wager.bet': '赌注',
    'wager.winnerTakes': '胜者获得', 'wager.prizePot': '总奖池', 'menu.worldCup': 'FIFA世界杯',
    'menu.tournamentFormat': '杯赛赛制', 'menu.practice': '训练场', 'menu.practiceSub': '任意球特训',
    'menu.shop': '商店', 'menu.onlineMultiplayer': '支持在线多人对战',
    'profile.savedReplaysStats': '回放与战绩', 'replays.title': '已保存的回放',
    'common.coins': '金币', 'common.coinsUpper': '金币', 'common.online': '在线', 'common.offline': '离线',
    'common.back': '返回', 'common.backToMenu': '返回主菜单', 'common.active': '当前使用', 'common.done': '完成',
    'common.close': '关闭', 'common.gotIt': '明白', 'common.cancel': '取消', 'common.continue': '继续',
    'common.exit': '退出', 'common.quit': '退出游戏', 'common.play': '开始', 'common.saved': '已保存', 'common.goal': '进球',
    'common.goals': '球', 'common.pts': '分', 'common.you': '你', 'common.opponent': '对手',
    'common.watchAdCoins': '观看视频广告获得 +50 免费金币', 'currency.coins': '金币',
    'btn.play': '立即开赛', 'btn.select': '选择', 'btn.confirm': '确认', 'btn.cancel': '取消',
    'btn.close': '关闭', 'btn.back': '返回', 'btn.continue': '继续', 'btn.nextMatch': '下一场比赛',
    'btn.returnMenu': '主菜单', 'btn.equip': '装备', 'btn.equipped': '已装备', 'btn.unlock': '解锁',
    'btn.locked': '未解锁', 'btn.saveReplay': '保存回放', 'btn.save': '保存', 'btn.saved': '已保存',
    'btn.skip': '跳过', 'btn.playAgain': '再来一局', 'btn.watchAd': '观看视频 (+50金币)', 'btn.freeCoins': '免费金币',
    'hud.aim': '瞄准', 'hud.power': '力度', 'hud.curve': '弧度', 'hud.kick': '射门',
    'hud.stepAim': '调整射门角度', 'hud.stepPower': '锁定击球力度', 'hud.stepCurve': '施加旋转弧线',
    'hud.stepKick': '起脚射门', 'hud.shoot': '射门！', 'hud.tapToLock': '点击以锁定',
    'hud.tapToKick': '点击以射门', 'hud.goal': '进球得分！', 'hud.saved': '扑救！', 'hud.missed': '偏出门框！',
    'hud.wallBlocked': '人墙挡出！', 'hud.postHit': '击中门柱！', 'hud.suddenDeath': '金球决胜',
    'hud.goldenGoal': '金球制胜', 'hud.penaltyShootout': '点球大战', 'hud.turn': '回合',
    'hud.yourTurn': '轮到你射门', 'hud.oppTurn': '轮到对手', 'hud.aiThinking': 'AI正在思考...',
    'hud.aiAiming': 'AI正在瞄准...', 'hud.aiStriking': 'AI正在起脚...', 'hud.timer': '计时',
    'hud.matchOver': '比赛结束', 'hud.rematch': '再战一局', 'hud.exitMatch': '退出比赛',
    'hud.resume': '继续比赛', 'hud.pause': '暂停', 'hud.yourTurnPenalty': '你主罚点球',
    'hud.oppPenalty': '对手主罚点球...', 'hud.aiPenalty': 'AI主罚点球...',
    'hud.playIn': '视角模式:', 'hud.ballTracking': '球体追踪', 'hud.behindGoal': '球门后方',
    'hud.meter': '仪表盘', 'hud.aiGoalkeeper': 'AI门将', 'hud.aiStriker': 'AI前锋',
    'hud.defenseSim': '防守模拟', 'hud.precisionFK': '精准任意球', 'hud.aiming': '瞄准中',
    'hud.holdToCharge': '按住以蓄力', 'hud.releaseToStrikeInstruction': '按住空格键 / 屏幕 • 松开即可射门',
    'hud.weak': '太轻', 'hud.sweetSpot': '完美', 'hud.max': '最大', 'hud.chargingPower': '蓄力中...',
    'hud.replay': '回放', 'game.goal': '进球！', 'game.saved': '扑救',
    'quickPlay.selectMode': '选择比赛模式:', 'quickPlay.ranked': '排位赛', 'quickPlay.vsAi': '对战AI / 本地',
    'country.selectTeams': '挑选球队', 'country.nationalTeams': '国家代表队', 'country.teamsAvailable': '可选球队',
    'country.tapToSelect': '点击以选择', 'country.myTeam': '我的球队', 'country.opponent': '对手球队',
    'country.continueToMatch': '进入比赛', 'search.countries': '搜索国家...', 'teamSelect.teams': '球队',
    'teamSelect.searchPlaceholder': '搜索国家队...', 'teamSelect.att': '进攻', 'teamSelect.def': '防守',
    'team.selectNew': '选择新球队', 'team.selectNewDesc': '从全球120支国家代表队中自由挑选',
    'online.matchTitle': '在线比赛', 'online.matchSubtitle': '实时联机并挑选参赛国家队:',
    'online.createRoom': '创建私密房间', 'online.joinRoom': '输入代码加入', 'online.joinRoomTitle': '加入房间',
    'online.roomCode': '房间代码', 'online.copyCode': '复制代码', 'online.codeCopied': '已复制！',
    'online.shareCode': '将此4位代码分享给你的好友:', 'online.enterCode': '输入4位房间代码:',
    'online.findMatch': '快速在线匹配', 'online.searchingMatch': '正在寻找对手...', 'online.stillSearching': '正在搜索活跃玩家...',
    'online.retrySearch': '重试搜索', 'online.cancelSearch': '取消搜索', 'online.cancelRoom': '取消房间',
    'online.leaveRoom': '离开房间', 'online.inviteLink': '复制邀请链接', 'online.linkCopied': '邀请链接已复制！',
    'online.lookingOpponent': '正在全球寻找对手...', 'online.pairingAuto': '正在连接玩家...', 'online.ready': '已准备',
    'online.bothSelected': '双方就绪！比赛开始...', 'online.selectTeamBelow': '请在下方选择你的球队:',
    'online.lockedIn': '已锁定', 'online.selecting': '选择中...', 'online.choosing': '正在挑选国家队...',
    'online.opponentLeft': '对手已退出房间', 'online.opponentLeftSub': '即将返回主菜单...',
    'online.roomCreated': '房间已创建', 'online.room': '房间', 'online.host': '房主', 'online.guest': '访客',
    'online.firstTurn': '你先踢', 'online.secondTurn': '对手先踢',
    'online.matchStartingIn': '比赛开始倒计时', 'online.kickoff': '开球！',
    'online.leaveMatchTitle': '确认离开比赛？', 'online.leaveMatchSub': '中途退出将判定对手直接获胜。',
    'online.leaveMatch': '离开比赛', 'online.leave': '离开', 'online.returnToMenu': '返回主菜单',
    'online.returningToMenu': '正在返回菜单...', 'online.sessionDisconnected': '连接已中断',
    'online.yourCountry': '你的国家队', 'online.oppCountry': '对手国家队',
    'online.waitingOpponent': '等待对手选队...', 'online.waitingOpponentCode': '等待好友输入代码...',
    'online.connectSub': '全球实时1v1多人对战服务器', 'modal.matchmaking': '正在匹配对手...',
    'modal.matchmakingDesc': '正在搜索全球服务器', 'modal.searchingTime': '匹配耗时',
    'modal.opponentFound': '找到对手！', 'modal.connectingBot': '30秒后将连接机器人...',
    'modal.quitMatchSub': '当前比赛进度将不会被保存。', 'modal.forfeitMatchTitle': '确认认输？',
    'modal.forfeitMatchSub': '现在退出将被判定为自动失败。', 'modal.forfeit': '认输',
    'match.opponentLeftTitle': '对手已离开比赛', 'match.opponentLeftDesc': '你的对手已断开连接。',
    'match.playAgainUnavailable': '对手已离开，无法再次对战。',
    'match.waitingOpponent': '等待对手应战...', 'match.changeTeams': '更换球队',
    'tournament.selectFormat': '选择赛制:', 'tournament.globalCup': '全球杯', 'tournament.customCup': '自定义杯赛',
    'tournament.inDevelopment': '开发中', 'tournament.onlineWorldCup': '在线世界杯',
    'tournament.multiplayerWorldCup': '多人世界杯与淘汰赛对阵', 'tournament.knockoutBrackets': '16强淘汰赛对阵图',
    'tournament.knockoutBracketsSub': '实时匹配淘汰杯赛', 'tournament.globalLeaderboards': '全球赛季排行榜',
    'tournament.globalLeaderboardsSub': '赢取积分和冠军奖杯', 'tournament.exclusiveUnlockables': '专属冠军球衣与足球',
    'tournament.exclusiveUnlockablesSub': '为冠军打造的荣耀奖励', 'tournament.playOfflineNow': '单机体验世界杯',
    'tournament.selectYourTeam': '选择你的球队', 'tournament.worldCupQualifiedSub': 'FIFA世界杯 • 40支入围决赛圈国家队（A组 – J组）',
    'tournament.searchCountry': '搜索国家或小组...', 'tournament.qualifiedNations': '入围国家队',
    'tournament.tapToSelect': '点击以选择', 'tournament.selected': '已选择', 'tournament.ovr': '总评',
    'tournament.randomGroupDraw': '开赛时随机分组抽签', 'tournament.tapAnyCountryPrompt': '点击国家选择你的队伍',
    'tournament.enterWorldCup': '征战世界杯（A - J组）', 'tournament.backToMenu': '主菜单',
    'tournament.forfeitMatch': '放弃比赛', 'tournament.continue': '晋级淘汰赛',
    'tournament.championTitle': '★ 世界冠军 ★', 'tournament.worldChampions': '世界冠军',
    'tournament.winnerLiftsCup': '你捧起了至高无上的大力神杯！', 'tournament.freeKickCup': '世界任意球锦标赛',
    'tournament.roundOf16': '1/8 决赛', 'tournament.quarterFinals': '1/4 决赛', 'tournament.semiFinal1': '半决赛 1',
    'tournament.semiFinal2': '半决赛 2', 'tournament.worldFinal': '世界杯决赛', 'tournament.awaitingFinal': '等待决赛对手',
    'tournament.fixture': '赛程', 'tournament.ft': '完场', 'tournament.tbd': '待定', 'tournament.cancelTournament': '取消赛事',
    'practice.selectDrill': '选择特训科目:', 'practice.freeKick': '任意球特训',
    'practice.freeKickSub': '即时练习 • 破解人墙与死角', 'practice.instant': '即时',
    'practice.penalty': '点球练习', 'practice.penaltySub': '1v1面对门将 • 无时间限制', 'practice.random': '随机',
    'practice.exitTitle': '退出训练？', 'practice.exitSub': '你可以随时返回主菜单。',
    'practice.exitButton': '退出训练', 'survival.title': '生存竞技场',
    'survival.subtitle': '3条命 • 极限连进 • 实时对决', 'survival.arenaTitle': '生存竞技场',
    'survival.onlineSurvivalTitle': '在线 1v1 生存对决',
    'survival.onlineSurvivalSubtitle': '3条命 • 实时1v1 • 挑战最高连续进球纪录',
    'survival.selectGameMode': '选择游戏模式:', 'survival.offlineSurvivalBtn': '单机生存模式',
    'survival.onlineDuelBtn': '在线 1v1 对决', 'survival.rulesBtn': '规则说明',
    'survival.rulesTitle': '生存模式规则', 'survival.rulesSubtitle': '遵循2大核心规则，挑战极限连胜:',
    'survival.rule1Title': '3生命值机制',
    'survival.rule1Desc': '每位玩家初始拥有3颗红心。射偏或被扑救扣除1条命。生命先归零者失败！',
    'survival.rule2Title': '轮流主罚与100秒限时',
    'survival.rule2Desc': '100秒倒计时内交替罚球。持续进球刷新你的最高连进纪录！',
    'survival.backToRules': '返回规则', 'survival.howItWorks': '玩法说明', 'survival.guideBadge': '生存指南',
    'survival.livesRemaining': '剩余生命', 'survival.bestRecord': '历史最佳纪录', 'survival.bestStreak': '最高连进',
    'survival.startRun': '开始挑战', 'survival.personalRecord': '个人最佳', 'survival.goalStreak': '连续进球',
    'survival.goalsStreak': '连续进球', 'survival.kicks': '射门次数', 'survival.duel': '生存 1v1 对决',
    'survival.duelSub': '在线淘汰锦标赛', 'survival.runEnded': '挑战结束！',
    'survival.challengeComplete': '生存挑战完成', 'survival.finalGoalsStreak': '最终连进成绩',
    'survival.challengeMode': '挑战模式', 'survival.reviveExtraLife': '复活 (+1条额外生命)',
    'survival.endSurvivalTitle': '结束生存模式？', 'survival.endSurvival': '结束', 'survival.endRun': '结束本次挑战',
    'survival.concludeSub': '比赛将立即终止。', 'survival.currentStreak': '当前连进:',
    'wager.title': '下注竞技场', 'wager.subtitle': '选择押注额度 • 胜者独揽全部金币！',
    'wager.rookie': '新秀竞技场', 'wager.pro': '职业竞技场', 'wager.champion': '冠军竞技场', 'wager.legend': '传奇竞技场',
    'wager.entryFee': '入场门票', 'wager.entry': '入场', 'wager.prizePot': '奖池总额', 'wager.winPot': '胜者奖金',
    'wager.highRoller': '高额押注实时对决', 'wager.bottomBanner': '探索竞技场 • 更高下注，双倍收益！',
    'wager.tapToSelect': '点击选择', 'wager.playWithCoins': '使用金币开战', 'wager.needMoreCoins': '金币不足',
    'wager.forfeitWager': '放弃下注', 'wager.surrenderTitle': '确认放弃下注？',
    'wager.surrenderSub': '认输将导致失去全部已下注金币:', 'wager.surrender': '认输', 'wager.victory': '押注大获全胜！',
    'wager.coinDuelResults': '对决结算', 'wager.drawRefunded': '平局 • 全额退还押注',
    'wager.arenaPot': '奖池总计', 'wager.netResult': '净收益',
    'wager.opponentLeft': '对手退出了竞技场', 'wager.rematch': '押注再战',
    'targetSmash.title': '靶心粉碎者', 'targetSmash.arcadeBadge': '全新街机模式',
    'targetSmash.trickshotSubtitle': '打靶射门与弧线特技', 'targetSmash.selectStage': '关卡 (1 - 10)',
    'targetSmash.unlocked': '已解锁', 'targetSmash.stage': '关卡', 'targetSmash.objective': '目标',
    'targetSmash.highScore': '最高分', 'targetSmash.pts': '分', 'targetSmash.distance': '距离',
    'targetSmash.defendersWall': '防守人墙', 'targetSmash.players': '人数', 'targetSmash.targetScore': '目标分数',
    'targetSmash.targetRequired': '通关所需分数', 'targetSmash.playStage': '挑战此关', 'targetSmash.stageLocked': '关卡锁定',
    'targetSmash.stageCleared': '成功通关！', 'targetSmash.stageFailed': '闯关失败', 'targetSmash.finalScore': '最终得分',
    'targetSmash.coinsReward': '金币奖励', 'targetSmash.nextStage': '下一关', 'targetSmash.retryStage': '重试',
    'targetSmash.exitToSelect': '返回关卡列表', 'divisions.title': '段位联赛', 'divisions.titleUpper': '段位联赛',
    'divisions.rank': '段位排名', 'divisions.titleTarget': '冠军目标', 'divisions.titleClaimed': '已夺取冠军！',
    'divisions.ptsForTrophy': '夺冠所需积分', 'divisions.seasonFinished': '赛季结束',
    'divisions.promotionAchieved': '晋级成功！', 'divisions.thisSeason': '本赛季',
    'divisions.matchesLeft': '剩余场次', 'divisions.ptsNeeded': '所需积分', 'divisions.win': '胜',
    'divisions.draw': '平', 'divisions.loss': '负', 'divisions.pt': '分', 'divisions.pts': '分',
    'divisions.allTime': '生涯总战绩', 'divisions.matchesHistory': '历史战报', 'divisions.match': '比赛',
    'divisions.noMatchesYet': '本赛季尚未进行任何比赛', 'divisions.noMatchesSub': '点击下方开启你的赛季！',
    'divisions.nextMatchChooseOpponent': '下一战 • 挑选对手', 'divisions.whoDoYouWantToPlay': '选择你下一场的对手:',
    'divisions.teamsAvailable': '可选球队', 'divisions.searchNationalTeam': '搜索国家代表队...',
    'divisions.playMatchVs': '开赛对阵', 'divisions.opponent': '对手', 'divisions.opponentUpper': '对手',
    'divisions.opponentConnected': '对手已连接', 'divisions.change': '更换', 'divisions.chooseOpponent': '挑选对手',
    'divisions.divShort': '段位', 'divisions.of': '/', 'divisions.continueTo': '晋级至', 'divisions.next': '下一步',
    'divisions.findingOpponent': '正在搜索同段位对手...', 'divisions.matchingWithOnline': '正在匹配同分段在线玩家',
    'divisions.searchingActivePlayers': '正在检索联赛服务器...', 'divisions.matchStartingIn': '比赛开始倒计时',
    'divisions.cancelMatchmaking': '取消', 'divisions.cancelSearch': '取消搜索', 'divisions.wdl': '胜-平-负',
    'division.return': '返回联赛', 'division.reward': '段位奖励', 'result.victory': '获胜！',
    'result.defeat': '失利', 'result.draw': '平局', 'result.champion': '世界之巅！冠军！', 'result.prizeWon': '赢得奖金',
    'result.streak': '当前连胜', 'result.newRecord': '刷新纪录！', 'result.coinsEarned': '获得金币',
    'result.finalScore': '最终比分', 'result.totalScore': '总积分', 'result.wonOnPenalties': '点球大战获胜',
    'result.lostOnPenalties': '点球大战失利', 'result.survivalVictory': '生存模式获胜！',
    'result.survivalDefeat': '生存模式被淘汰', 'result.wagerResults': '押注结果',
    'rematch.invitationTitle': '再战申请', 'rematch.invitationDesc': '对手请求与你再来一局！',
    'rematch.accept': '接受再战', 'rematch.decline': '拒绝', 'rematch.starting': '正在开启再战...',
    'rematch.survivalRequested': '对手请求进行生存模式再战！',
    'rematch.survivalDesc': '接受后立即重返1v1对决！',
    'rematch.wagerChallenge': '向你发起了押注再战邀请！', 'stats.goals': '进球数', 'stats.shots': '射门数',
    'status.live': 'LIVE', 'status.offline': '离线', 'status.winner': '胜者', 'status.eliminated': '已淘汰',
    'status.survived': '成功存活', 'status.left': '已离开', 'status.disconnected': '已断开',
    'store.title': '装备商店', 'store.subtitle': '3D足球纹理与球场草坪图案',
    'store.balls': '足球', 'store.pitches': '球场', 'store.ballStore': '足球专区',
    'store.ballStoreDesc': '3D纹理与专业比赛用球', 'store.pitchStore': '球场专区',
    'store.pitchStoreDesc': '顶级专业草坪剪裁花纹', 'store.selectCategory': '选择类别',
    'store.unlockedAndEquipped': '已解锁并装备', 'store.owned': '已拥有', 'store.buyFor': '购买价格',
    'store.notEnoughCoins': '金币不足！', 'store.needMore': '还需', 'store.more': '金币',
    'profile.title': '个人资料', 'profile.cloudStorageNotice': '已同步至CRAZYGAMES云端及本地',
    'replays.subtitle': '查看并管理你保存的精彩进球瞬间', 'replays.savedReplays': '已保存的回放',
    'replays.savedHighlights': '精彩瞬间收藏', 'replays.clips': '片段', 'replays.savedClips': '已存录像',
    'replays.noSavedReplays': '暂无保存的回放', 'replays.noHighlightsTitle': '暂无精彩瞬间',
    'replays.noHighlightsDesc': '在比赛中打入进球，并在回放时点击右上角保存！',
    'replays.playMatchNow': '立即开赛', 'replays.emptyInstructions': '踢出精彩进球，点击回放画面右上角的“保存”即可收录！',
    'replays.savedHighlight': '精彩进球', 'replays.savedDate': '日期', 'replays.shotDistance': '射门距离',
    'replays.longestStrike': '最远进球', 'replays.goalHighlights': '进球集锦', 'replays.watchReplay': '观看回放',
    'replays.exitReplay': '退出回放', 'replays.deleteReplay': '删除回放',
    'replays.confirmDelete': '确认删除该进球片段吗？', 'replays.deleteAllConfirm': '清空所有回放？',
    'replays.deleteAllDesc': '你确定要清空全部保存的回放录像吗？', 'ads.videoReward': '视频激励奖励',
    'ads.coinsReward': '金币奖励', 'ads.watchToEarn': '观看视频广告获得 +50 金币',
    'ads.instantBoost': '金币即时补给', 'ads.integrationFinalizing': '广告系统准备就绪。',
    'ads.unlockAllItems': '解锁全部50款足球与50款草坪皮肤！', 'ads.loading': '正在加载广告...',
    'lang.title': '语言设置', 'lang.subtitle': '选择你的首选语言（支持全球16种主流语言）',
    'lang.autoDetect': '自动检测语言', 'lang.currentlyActive': '当前启用',
    'lang.sdkSyncTitle': 'CrazyGames 同步', 'lang.sdkSyncDesc': '游戏语言将自动与你的CrazyGames平台偏好同步',
    'lang.searchPlaceholder': '搜索语言或国家...', 'lang.tabAll': '全部 (16)', 'lang.tabPopular': '热门',
    'lang.tabEurope': '欧洲', 'lang.tabAmericas': '美洲', 'lang.tabAsiaMe': '亚洲与中东',
    'lang.noMatches': '未找到匹配的语言', 'lang.noMatchesDesc': '请尝试输入其他语言名称或国家',
    'lang.resetFilters': '重置筛选'
}

print("AR and ZH loaded.")
