# -*- coding: utf-8 -*-
# Group 1: es, pt, fr, de, it

es = {
    'nav.store': 'Tienda', 'nav.profile': 'Perfil', 'nav.replays': 'Repeticiones', 'nav.coins': 'Monedas',
    'nav.language': 'Idioma', 'nav.bestStreak': 'Mejor Racha', 'nav.online': 'En Línea', 'nav.connecting': 'Conectando...',
    'game.title': 'FREE KICK LEGENDS', 'menu.quickPlay': 'PARTIDO RÁPIDO', 'menu.quickPlaySub': 'PARTIDOS ONLINE Y OFFLINE',
    'menu.survivalMode': 'MODO SUPERVIVENCIA', 'survival.threeLives': '3 VIDAS', 'survival.endlessStreak': 'Racha Infinita',
    'survival.best': 'Récord', 'survival.streak': 'RACHA', 'survival.onlineAvailable': 'Supervivencia 1vs1 Online Disponible',
    'menu.wagerArena': 'ARENA DE APUESTAS', 'wager.betCoinsPot': 'Apuesta Monedas • El Ganador se Lleva Todo',
    'wager.onlineDuel': 'Duelo Online 1vs1 con Apuesta', 'wager.duel': 'DUELO', 'wager.arena': 'Arena', 'wager.bet': 'Apuesta',
    'wager.winnerTakes': 'El Ganador se Lleva', 'wager.prizePot': 'Bote del Premio', 'menu.worldCup': 'COPA DEL MUNDO FIFA',
    'menu.tournamentFormat': 'Formato de Torneo', 'menu.practice': 'ENTRENAMIENTO', 'menu.practiceSub': 'Práctica de Tiros Libres',
    'menu.shop': 'TIENDA', 'menu.onlineMultiplayer': 'Multijugador Online Disponible',
    'profile.savedReplaysStats': 'REPETICIONES Y ESTADÍSTICAS', 'replays.title': 'Repeticiones Guardadas',
    'common.coins': 'MONEDAS', 'common.coinsUpper': 'MONEDAS', 'common.online': 'ONLINE', 'common.offline': 'OFFLINE',
    'common.back': 'VOLVER', 'common.backToMenu': 'Volver al Menú', 'common.active': 'ACTIVO', 'common.done': 'LISTO Y VOLVER',
    'common.close': 'CERRAR', 'common.gotIt': 'ENTENDIDO', 'common.cancel': 'Cancelar', 'common.continue': 'CONTINUAR',
    'common.exit': 'SALIR', 'common.quit': 'SALIR', 'common.play': 'JUGAR', 'common.saved': 'GUARDADO', 'common.goal': 'GOL',
    'common.goals': 'goles', 'common.pts': 'PTS', 'common.you': 'Tú', 'common.opponent': 'Rival',
    'common.watchAdCoins': 'Ver anuncio para ganar +50 monedas', 'currency.coins': 'MONEDAS',
    'btn.play': 'Jugar Ahora', 'btn.select': 'Seleccionar', 'btn.confirm': 'Confirmar', 'btn.cancel': 'Cancelar',
    'btn.close': 'Cerrar', 'btn.back': 'Volver', 'btn.continue': 'Continuar', 'btn.nextMatch': 'Siguiente Partido',
    'btn.returnMenu': 'Volver al Menú', 'btn.equip': 'Equipar', 'btn.equipped': 'Equipado', 'btn.unlock': 'Desbloquear',
    'btn.locked': 'Bloqueado', 'btn.saveReplay': 'Guardar Repetición', 'btn.save': 'GUARDAR', 'btn.saved': 'GUARDADO',
    'btn.skip': 'SALTAR', 'btn.playAgain': 'Jugar de Nuevo', 'btn.watchAd': 'Ver Anuncio (+50 Monedas)', 'btn.freeCoins': 'Monedas Gratis',
    'hud.aim': 'Apuntar', 'hud.power': 'Potencia', 'hud.curve': 'Efecto', 'hud.kick': 'Disparo',
    'hud.stepAim': 'AJUSTA EL ÁNGULO', 'hud.stepPower': 'FIJA LA POTENCIA', 'hud.stepCurve': 'APLICA EFECTO AL BALÓN',
    'hud.stepKick': 'EJECUTA EL DISPARO', 'hud.shoot': '¡DISPARA!', 'hud.tapToLock': 'TOCA PARA FIJAR',
    'hud.tapToKick': 'TOCA PARA DISPARAR', 'hud.goal': '¡GOL!', 'hud.saved': '¡PARADA!', 'hud.missed': '¡FALLADO!',
    'hud.wallBlocked': '¡BARRERA BLOQUEÓ!', 'hud.postHit': '¡AL PALO!', 'hud.suddenDeath': 'MUERTE SÚBITA',
    'hud.goldenGoal': 'GOL DE ORO', 'hud.penaltyShootout': 'TANDA DE PENALTIS', 'hud.turn': 'Turno',
    'hud.yourTurn': 'TU TURNO', 'hud.oppTurn': 'TURNO DEL RIVAL', 'hud.aiThinking': 'IA PENSANDO...',
    'hud.aiAiming': 'IA APUNTANDO...', 'hud.aiStriking': 'IA DISPARANDO...', 'hud.timer': 'Tiempo de Juego',
    'hud.matchOver': 'FIN DEL PARTIDO', 'hud.rematch': 'Revancha', 'hud.exitMatch': 'Salir del Partido',
    'hud.resume': 'Reanudar', 'hud.pause': 'Pausa', 'hud.yourTurnPenalty': 'TU TURNO PARA DISPARAR',
    'hud.oppPenalty': 'EL RIVAL ESTÁ DISPARANDO...', 'hud.aiPenalty': 'LA IA ESTÁ DISPARANDO...',
    'hud.playIn': 'JUGAR EN:', 'hud.ballTracking': 'SEGUIMIENTO DE BALÓN', 'hud.behindGoal': 'DETRÁS DE LA PORTERÍA',
    'hud.meter': 'MEDIDOR', 'hud.aiGoalkeeper': 'PORTERO IA', 'hud.aiStriker': 'DELANTERO IA',
    'hud.defenseSim': 'Simulación Defensiva', 'hud.precisionFK': 'Tiro Libre de Precisión', 'hud.aiming': 'APUNTANDO',
    'hud.holdToCharge': 'MANTÉN PARA CARGAR POTENCIA', 'hud.releaseToStrikeInstruction': 'MANTÉN ESPACIO / PANTALLA • SUELTA PARA DISPARAR',
    'hud.weak': 'DÉBIL', 'hud.sweetSpot': 'PUNTO EXACTO', 'hud.max': 'MÁX', 'hud.chargingPower': 'CARGANDO POTENCIA...',
    'hud.replay': 'REPETICIÓN', 'game.goal': '¡GOL!', 'game.saved': 'PARADA',
    'quickPlay.selectMode': 'Selecciona modo de partido:', 'quickPlay.ranked': 'Clasificatorio', 'quickPlay.vsAi': 'Vs IA / Local',
    'country.selectTeams': 'SELECCIONA EQUIPOS', 'country.nationalTeams': 'Selecciones Nacionales', 'country.teamsAvailable': 'Equipos Disponibles',
    'country.tapToSelect': 'Toca una tarjeta para elegir / deseleccionar', 'country.myTeam': 'MI EQUIPO', 'country.opponent': 'RIVAL',
    'country.continueToMatch': 'CONTINUAR AL PARTIDO', 'search.countries': 'Buscar país...', 'teamSelect.teams': 'Equipos',
    'teamSelect.searchPlaceholder': 'Buscar selección nacional...', 'teamSelect.att': 'DEL', 'teamSelect.def': 'DEF',
    'team.selectNew': 'SELECCIONAR NUEVO EQUIPO', 'team.selectNewDesc': 'Elige tu país entre 120 selecciones del mundo',
    'online.matchTitle': 'PARTIDO ONLINE', 'online.matchSubtitle': 'Conéctate y elige selección en tiempo real:',
    'online.createRoom': 'Crear Sala Privada', 'online.joinRoom': 'Unirse con Código', 'online.joinRoomTitle': 'UNIRSE A SALA PRIVADA',
    'online.roomCode': 'Código de Sala', 'online.copyCode': 'Copiar Código', 'online.codeCopied': '¡Copiado!',
    'online.shareCode': 'Comparte este código de 4 dígitos con tu amigo:', 'online.enterCode': 'Introduce el código de 4 dígitos:',
    'online.findMatch': 'Emparejamiento Rápido', 'online.searchingMatch': 'Buscando rivales...', 'online.stillSearching': 'Buscando jugadores activos...',
    'online.retrySearch': 'Reintentar Búsqueda', 'online.cancelSearch': 'Cancelar Búsqueda', 'online.cancelRoom': 'Cancelar Sala',
    'online.leaveRoom': 'Salir de la Sala', 'online.inviteLink': 'Copiar Enlace de Invitación', 'online.linkCopied': '¡Enlace Copiado!',
    'online.lookingOpponent': 'Buscando rival en el mundo...', 'online.pairingAuto': 'Emparejando con jugador...', 'online.ready': 'LISTO',
    'online.bothSelected': '¡Ambos listos! Comenzando partido...', 'online.selectTeamBelow': 'Elige tu equipo abajo:',
    'online.lockedIn': 'CONFIRMADO', 'online.selecting': 'Eligiendo...', 'online.choosing': 'Eligiendo selección...',
    'online.opponentLeft': 'El rival ha abandonado la sala', 'online.opponentLeftSub': 'Regresando al menú en unos momentos...',
    'online.roomCreated': 'SALA CREADA', 'online.room': 'Sala', 'online.host': 'Anfitrión', 'online.guest': 'Invitado',
    'online.firstTurn': 'Tú disparas primero', 'online.secondTurn': 'El rival dispara primero',
    'online.matchStartingIn': 'El Partido Comienza En', 'online.kickoff': '¡SAQUE INICIAL!',
    'online.leaveMatchTitle': '¿ABANDONAR PARTIDO?', 'online.leaveMatchSub': 'Desconectarte otorgará la victoria por abandono a tu rival.',
    'online.leaveMatch': 'ABANDONAR', 'online.leave': 'SALIR', 'online.returnToMenu': 'Volver al Menú',
    'online.returningToMenu': 'Volviendo al Menú...', 'online.sessionDisconnected': 'Sesión Desconectada',
    'online.yourCountry': 'TU SELECCIÓN', 'online.oppCountry': 'SELECCIÓN RIVAL',
    'online.waitingOpponent': 'Esperando a que el rival elija...', 'online.waitingOpponentCode': 'Esperando a que tu amigo se una...',
    'online.connectSub': 'Servidores multijugador 1vs1 en tiempo real', 'modal.matchmaking': 'Buscando Rival...',
    'modal.matchmakingDesc': 'Buscando oponentes en servidores globales', 'modal.searchingTime': 'Tiempo de Búsqueda',
    'modal.opponentFound': '¡RIVAL ENCONTRADO!', 'modal.connectingBot': 'Conectando con bot en 30s...',
    'modal.quitMatchSub': 'El progreso actual no se guardará.', 'modal.forfeitMatchTitle': '¿RENDIRSE?',
    'modal.forfeitMatchSub': 'Salir ahora cuenta como derrota automática.', 'modal.forfeit': 'RENDIRSE',
    'match.opponentLeftTitle': 'EL RIVAL HA SALIDO', 'match.opponentLeftDesc': 'Tu rival se desconectó o volvió al menú.',
    'match.playAgainUnavailable': 'Jugar de nuevo no está disponible porque el rival salió.',
    'match.waitingOpponent': 'Esperando respuesta del rival...', 'match.changeTeams': 'CAMBIAR EQUIPOS',
    'tournament.selectFormat': 'Selecciona formato:', 'tournament.globalCup': 'Copa Global', 'tournament.customCup': 'Copa Personalizada',
    'tournament.inDevelopment': 'EN DESARROLLO', 'tournament.onlineWorldCup': 'COPA MUNDIAL ONLINE',
    'tournament.multiplayerWorldCup': 'Copas Mundiales y Cuadros Eliminatorios', 'tournament.knockoutBrackets': 'Eliminatorias de 16 Equipos',
    'tournament.knockoutBracketsSub': 'Torneos de eliminación en tiempo real', 'tournament.globalLeaderboards': 'Clasificaciones Globales',
    'tournament.globalLeaderboardsSub': 'Gana puntos de ranking y trofeos', 'tournament.exclusiveUnlockables': 'Equipaciones y Balones Exclusivos',
    'tournament.exclusiveUnlockablesSub': 'Recompensas especiales para campeones', 'tournament.playOfflineNow': 'JUGAR COPA DEL MUNDO OFFLINE',
    'tournament.selectYourTeam': 'ELIGE TU SELECCIÓN', 'tournament.worldCupQualifiedSub': 'Copa Mundial FIFA • 40 Naciones Clasificadas (Grupos A – J)',
    'tournament.searchCountry': 'Buscar país o grupo...', 'tournament.qualifiedNations': 'Naciones Clasificadas',
    'tournament.tapToSelect': 'Toca para Elegir', 'tournament.selected': 'SELECCIONADO', 'tournament.ovr': 'MED',
    'tournament.randomGroupDraw': 'Sorteo de grupos al entrar al torneo', 'tournament.tapAnyCountryPrompt': 'TOCA UN PAÍS PARA ELEGIR TU EQUIPO',
    'tournament.enterWorldCup': 'ENTRAR AL MUNDIAL (GRUPOS A - J)', 'tournament.backToMenu': 'Volver al Menú',
    'tournament.forfeitMatch': 'RENDIR PARTIDO', 'tournament.continue': 'CONTINUAR A ELIMINATORIAS',
    'tournament.championTitle': '★ CAMPEONES DEL MUNDO ★', 'tournament.worldChampions': 'CAMPEONES DEL MUNDO',
    'tournament.winnerLiftsCup': '¡Has levantado el Trofeo de la Copa Mundial!', 'tournament.freeKickCup': 'Torneo de Tiros Libres Mundial',
    'tournament.roundOf16': 'Octavos de Final', 'tournament.quarterFinals': 'Cuartos de Final', 'tournament.semiFinal1': 'Semifinal 1',
    'tournament.semiFinal2': 'Semifinal 2', 'tournament.worldFinal': 'Gran Final Mundial', 'tournament.awaitingFinal': 'Esperando Finalista',
    'tournament.fixture': 'Partido', 'tournament.ft': 'FIN', 'tournament.tbd': 'POR DEFINIR', 'tournament.cancelTournament': 'Cancelar Torneo',
    'practice.selectDrill': 'Selecciona ejercicio de entrenamiento:', 'practice.freeKick': 'TIRO LIBRE',
    'practice.freeKickSub': 'Juego instantáneo • Barrera y ángulos', 'practice.instant': 'Directo',
    'practice.penalty': 'PENALTI', 'practice.penaltySub': '1vs1 vs Portero • Sin tiempo', 'practice.random': 'Aleatorio',
    'practice.exitTitle': '¿SALIR DEL ENTRENAMIENTO?', 'practice.exitSub': 'Puedes volver al menú principal en cualquier momento.',
    'practice.exitButton': 'SALIR DEL ENTRENAMIENTO', 'survival.title': 'Arena de Supervivencia',
    'survival.subtitle': '3 Vidas • Rachas Ilimitadas • Duelos', 'survival.arenaTitle': 'ARENA DE SUPERVIVENCIA',
    'survival.onlineSurvivalTitle': 'SUPERVIVENCIA 1VS1 ONLINE',
    'survival.onlineSurvivalSubtitle': '3 Vidas • Duelo 1vs1 • Desafío de Racha Infinita',
    'survival.selectGameMode': 'Elige tu modo de juego:', 'survival.offlineSurvivalBtn': 'SUPERVIVENCIA OFFLINE',
    'survival.onlineDuelBtn': 'DUELO ONLINE 1VS1', 'survival.rulesBtn': 'Reglas',
    'survival.rulesTitle': 'REGLAS DE SUPERVIVENCIA', 'survival.rulesSubtitle': 'Sigue estas 2 mecánicas para maximizar tu racha de goles:',
    'survival.rule1Title': 'Sistema de 3 Vidas',
    'survival.rule1Desc': 'Ambos jugadores empiezan con 3 corazones. Un tiro fallado o parado resta 1 vida. ¡El primero en perder sus 3 vidas pierde!',
    'survival.rule2Title': 'Duelo por Turnos y 100s',
    'survival.rule2Desc': 'Tiros libres alternos con cuenta atrás de 100 segundos. ¡Marca goles para ampliar tu racha y ganar!',
    'survival.backToRules': 'Volver a Reglas', 'survival.howItWorks': 'Cómo funciona', 'survival.guideBadge': 'GUÍA DE SUPERVIVENCIA',
    'survival.livesRemaining': 'Vidas Restantes', 'survival.bestRecord': 'Mejor Récord Histórico', 'survival.bestStreak': 'MEJOR RACHA',
    'survival.startRun': 'Comenzar Intento', 'survival.personalRecord': 'Récord Personal', 'survival.goalStreak': 'RACHA DE GOLES',
    'survival.goalsStreak': 'RACHA DE GOLES', 'survival.kicks': 'Tiros', 'survival.duel': 'DUELO DE SUPERVIVENCIA 1VS1',
    'survival.duelSub': 'Duelo de Eliminación Online', 'survival.runEnded': '¡FIN DEL INTENTO!',
    'survival.challengeComplete': 'Desafío de Supervivencia Completado', 'survival.finalGoalsStreak': 'Racha Final de Goles',
    'survival.challengeMode': 'Modo Desafío', 'survival.reviveExtraLife': 'REVIVIR (+1 VIDA EXTRA)',
    'survival.endSurvivalTitle': '¿TERMINAR SUPERVIVENCIA?', 'survival.endSurvival': 'TERMINAR', 'survival.endRun': 'TERMINAR INTENTO',
    'survival.concludeSub': 'La partida finalizará inmediatamente.', 'survival.currentStreak': 'Racha actual:',
    'wager.title': 'Arenas de Apuestas', 'wager.subtitle': 'Elige tu apuesta • ¡El ganador se lleva todas las monedas!',
    'wager.rookie': 'Arena Novato', 'wager.pro': 'Arena Profesional', 'wager.champion': 'Arena Campeón', 'wager.legend': 'Arena Leyenda',
    'wager.entryFee': 'Cuota de Entrada', 'wager.entry': 'ENTRADA', 'wager.prizePot': 'Bote del Premio', 'wager.winPot': 'BOTE GANADOR',
    'wager.highRoller': 'Duelo de Altas Apuestas', 'wager.bottomBanner': 'Explora las arenas • ¡Apuestas altas, recompensas dobles!',
    'wager.tapToSelect': 'Toca para seleccionar', 'wager.playWithCoins': 'Jugar con monedas', 'wager.needMoreCoins': 'Necesitas más monedas',
    'wager.forfeitWager': 'ABANDONAR APUESTA', 'wager.surrenderTitle': '¿RENDIRSE EN LA APUESTA?',
    'wager.surrenderSub': 'Rendirse significará perder tu apuesta:', 'wager.surrender': 'RENDIRSE', 'wager.victory': '¡VICTORIA EN APUESTA!',
    'wager.coinDuelResults': 'Resultados del Duelo', 'wager.drawRefunded': 'EMPATE • ENTRADA REEMBOLSADA',
    'wager.arenaPot': 'Bote de la Arena', 'wager.netResult': 'Resultado Neto',
    'wager.opponentLeft': 'El rival se desconectó o salió de la arena', 'wager.rematch': 'REVANCHA CON APUESTA',
    'targetSmash.title': 'TIRO AL BLANCO', 'targetSmash.arcadeBadge': 'NUEVO MODO ARCADE', 'targetSmash.trickshotSubtitle': 'Dianas y Tiros con Efecto',
    'targetSmash.selectStage': 'Elige Nivel (1 - 10)', 'targetSmash.unlocked': 'Desbloqueado', 'targetSmash.stage': 'Nivel',
    'targetSmash.objective': 'Objetivo', 'targetSmash.highScore': 'Récord', 'targetSmash.pts': 'PTS', 'targetSmash.distance': 'Distancia',
    'targetSmash.defendersWall': 'Barrera Defensiva', 'targetSmash.players': 'Jugadores', 'targetSmash.targetScore': 'Puntuación Objetivo',
    'targetSmash.targetRequired': 'Objetivo Requerido', 'targetSmash.playStage': 'JUGAR NIVEL', 'targetSmash.stageLocked': 'NIVEL BLOQUEADO',
    'targetSmash.stageCleared': '¡NIVEL SUPERADO!', 'targetSmash.stageFailed': 'NIVEL NO SUPERADO', 'targetSmash.finalScore': 'Puntuación Final',
    'targetSmash.coinsReward': 'Recompensa de Monedas', 'targetSmash.nextStage': 'SIGUIENTE NIVEL', 'targetSmash.retryStage': 'REINTENTAR',
    'targetSmash.exitToSelect': 'VOLVER A NIVELES', 'divisions.title': 'Liga de Divisiones', 'divisions.titleUpper': 'LIGA DE DIVISIONES',
    'divisions.rank': 'Rango de División', 'divisions.titleTarget': 'Objetivo de Título', 'divisions.titleClaimed': '¡Título Conseguido!',
    'divisions.ptsForTrophy': 'Puntos para el Trofeo de Campeón', 'divisions.seasonFinished': 'Temporada Finalizada',
    'divisions.promotionAchieved': '¡Ascenso Conseguido!', 'divisions.thisSeason': 'Esta Temporada', 'divisions.matchesLeft': 'Partidos Restantes',
    'divisions.ptsNeeded': 'Puntos Necesarios', 'divisions.win': 'Victoria', 'divisions.draw': 'Empate', 'divisions.loss': 'Derrota',
    'divisions.pt': 'PT', 'divisions.pts': 'PTS', 'divisions.allTime': 'Récord Histórico', 'divisions.matchesHistory': 'Historial de Partidos',
    'divisions.match': 'Partido', 'divisions.noMatchesYet': 'Aún no hay partidos jugados esta temporada',
    'divisions.noMatchesSub': '¡Comienza tu campaña de división abajo!', 'divisions.nextMatchChooseOpponent': 'Siguiente Partido • Elige Rival',
    'divisions.whoDoYouWantToPlay': 'Elige a tu próximo rival:', 'divisions.teamsAvailable': 'Equipos Disponibles',
    'divisions.searchNationalTeam': 'Buscar selección nacional...', 'divisions.playMatchVs': 'JUGAR PARTIDO CONTRA',
    'divisions.opponent': 'Rival', 'divisions.opponentUpper': 'RIVAL', 'divisions.opponentConnected': 'Rival Conectado',
    'divisions.change': 'Cambiar', 'divisions.chooseOpponent': 'Elegir Rival', 'divisions.divShort': 'DIV', 'divisions.of': 'de',
    'divisions.continueTo': 'Continuar a', 'divisions.next': 'Siguiente', 'divisions.findingOpponent': 'Buscando Rival de División...',
    'divisions.matchingWithOnline': 'Emparejando con jugadores en tu división',
    'divisions.searchingActivePlayers': 'Buscando en servidores de divisiones...', 'divisions.matchStartingIn': 'El partido comienza en',
    'divisions.cancelMatchmaking': 'Cancelar Emparejamiento', 'divisions.cancelSearch': 'Cancelar Búsqueda', 'divisions.wdl': 'V-E-D',
    'division.return': 'Volver a Divisiones', 'division.reward': 'Recompensa de División', 'result.victory': '¡VICTORIA!',
    'result.defeat': 'DERROTA', 'result.draw': 'EMPATE', 'result.champion': '¡CAMPEÓN DEL MUNDO!', 'result.prizeWon': 'Premio Ganado',
    'result.streak': 'Racha Actual', 'result.newRecord': '¡NUEVO RÉCORD!', 'result.coinsEarned': 'Monedas Ganadas',
    'result.finalScore': 'Resultado Final', 'result.totalScore': 'Puntuación Total', 'result.wonOnPenalties': 'VICTORIA EN PENALTIS',
    'result.lostOnPenalties': 'DERROTA EN PENALTIS', 'result.survivalVictory': '¡VICTORIA EN SUPERVIVENCIA!',
    'result.survivalDefeat': 'ELIMINADO EN SUPERVIVENCIA', 'result.wagerResults': 'Resultados de la Apuesta',
    'rematch.invitationTitle': 'Revancha Solicitada', 'rematch.invitationDesc': '¡El rival quiere jugar la revancha!',
    'rematch.accept': 'Aceptar Revancha', 'rematch.decline': 'Rechazar', 'rematch.starting': 'Iniciando Revancha...',
    'rematch.survivalRequested': '¡El rival solicitó Revancha de Supervivencia!',
    'rematch.survivalDesc': '¡Acepta para volver de inmediato al Duelo 1vs1!', 'rematch.wagerChallenge': '¡te desafía a una Revancha con Apuesta!',
    'stats.goals': 'Goles', 'stats.shots': 'Disparos', 'status.live': 'EN VIVO', 'status.offline': 'DESCONECTADO',
    'status.winner': 'GANADOR', 'status.eliminated': 'ELIMINADO', 'status.survived': 'SOBREVIVIÓ', 'status.left': 'SALIÓ',
    'status.disconnected': 'DESCONECTADO', 'store.title': 'Tienda de Equipamiento', 'store.subtitle': 'TEXTURAS 3D DE BALONES Y CÉSPED',
    'store.balls': 'Balones', 'store.pitches': 'Céspedes', 'store.ballStore': 'TIENDA DE BALONES',
    'store.ballStoreDesc': 'Texturas 3D y Modelos Pro', 'store.pitchStore': 'TIENDA DE ESTADIOS',
    'store.pitchStoreDesc': 'Cortes de Césped de Estadio', 'store.selectCategory': 'SELECCIONA CATEGORÍA',
    'store.unlockedAndEquipped': 'DESBLOQUEADO Y EQUIPADO', 'store.owned': 'En Propiedad', 'store.buyFor': 'Comprar por',
    'store.notEnoughCoins': '¡NO TIENES SUFICIENTES MONEDAS!', 'store.needMore': 'FALTAN', 'store.more': 'MÁS',
    'profile.title': 'Perfil de Jugador', 'profile.cloudStorageNotice': 'GUARDADO EN LA NUBE CRAZYGAMES Y LOCAL',
    'replays.subtitle': 'Mira y gestiona tus mejores goles guardados', 'replays.savedReplays': 'REPETICIONES GUARDADAS',
    'replays.savedHighlights': 'MEJORES JUGADAS GUARDADAS', 'replays.clips': 'Vídeos', 'replays.savedClips': 'Clips Guardados',
    'replays.noSavedReplays': 'AÚN NO HAY REPETICIONES', 'replays.noHighlightsTitle': 'SIN JUGADAS GUARDADAS',
    'replays.noHighlightsDesc': '¡Marca un gol en cualquier partido y toca GUARDAR en la repetición para almacenarlo!',
    'replays.playMatchNow': 'JUGAR UN PARTIDO AHORA',
    'replays.emptyInstructions': '¡Marca un gol y presiona GUARDAR arriba a la derecha en la repetición para guardarlo aquí!',
    'replays.savedHighlight': 'JUGADA GUARDADA', 'replays.savedDate': 'FECHA GUARDADA', 'replays.shotDistance': 'DISTANCIA DEL TIRO',
    'replays.longestStrike': 'Tiro Más Lejano', 'replays.goalHighlights': 'Momentos Destacados', 'replays.watchReplay': 'VER REPETICIÓN',
    'replays.exitReplay': 'SALIR DE REPETICIÓN', 'replays.deleteReplay': 'Eliminar Repetición',
    'replays.confirmDelete': '¿Eliminar este gol guardado?', 'replays.deleteAllConfirm': '¿ELIMINAR TODAS?',
    'replays.deleteAllDesc': '¿Seguro que deseas borrar todas las repeticiones?', 'ads.videoReward': 'RECOMPENSA EN VÍDEO',
    'ads.coinsReward': 'RECOMPENSA EN MONEDAS', 'ads.watchToEarn': 'Mira anuncios en vídeo para ganar +50 monedas',
    'ads.instantBoost': 'Impulso Instantáneo de Monedas', 'ads.integrationFinalizing': 'La integración de anuncios se está finalizando.',
    'ads.unlockAllItems': '¡Desbloquea los 50 balones y 50 céspedes de estadio!', 'ads.loading': 'CARGANDO ANUNCIO...',
    'lang.title': 'Ajustes de Idioma', 'lang.subtitle': 'Elige tu idioma preferido (16 idiomas globales disponibles)',
    'lang.autoDetect': 'Idioma Detectado Automáticamente', 'lang.currentlyActive': 'ACTIVO ACTUALMENTE',
    'lang.sdkSyncTitle': 'Sincronización CrazyGames', 'lang.sdkSyncDesc': 'El juego se sincroniza con el idioma preferido de tu portal',
    'lang.searchPlaceholder': 'Buscar idioma o país...', 'lang.tabAll': 'Todos (16)', 'lang.tabPopular': 'Populares',
    'lang.tabEurope': 'Europa', 'lang.tabAmericas': 'América', 'lang.tabAsiaMe': 'Asia y OM',
    'lang.noMatches': 'No se encontraron idiomas', 'lang.noMatchesDesc': 'Prueba buscando con otro nombre o región',
    'lang.resetFilters': 'Restablecer Filtros'
}

print(f"Group 1 ES loaded ({len(es)} keys)")
