# -*- coding: utf-8 -*-
# Japanese (ja) & Korean (ko)

ja = {
    'nav.store': 'ショップ', 'nav.profile': 'プロフィール', 'nav.replays': 'リプレイ', 'nav.coins': 'コイン',
    'nav.language': '言語', 'nav.bestStreak': '最高連勝', 'nav.online': 'オンライン', 'nav.connecting': '接続中...',
    'game.title': 'FREE KICK LEGENDS', 'menu.quickPlay': 'クイックプレイ', 'menu.quickPlaySub': 'オンライン＆オフライン対戦',
    'menu.survivalMode': 'サバイバルモード', 'survival.threeLives': 'ライフ3', 'survival.endlessStreak': 'エンドレス連勝',
    'survival.best': '最高記録', 'survival.streak': '連続記録', 'survival.onlineAvailable': 'オンライン1v1サバイバル対戦対応',
    'menu.wagerArena': '賭けアリーナ', 'wager.betCoinsPot': 'コインを賭ける • 勝者総取り',
    'wager.onlineDuel': 'オンライン1v1コイン賭けバトル', 'wager.duel': 'デュエル', 'wager.arena': 'アリーナ', 'wager.bet': '賭け金',
    'wager.winnerTakes': '勝者総取り', 'wager.prizePot': '賞金総額', 'menu.worldCup': 'FIFA ワールドカップ',
    'menu.tournamentFormat': 'トーナメント形式', 'menu.practice': 'トレーニング', 'menu.practiceSub': 'フリーキック練習',
    'menu.shop': 'ショップ', 'menu.onlineMultiplayer': 'オンラインマルチプレイ対応',
    'profile.savedReplaysStats': 'リプレイ＆戦績', 'replays.title': '保存したリプレイ',
    'common.coins': 'コイン', 'common.coinsUpper': 'コイン', 'common.online': 'オンライン', 'common.offline': 'オフライン',
    'common.back': '戻る', 'common.backToMenu': 'メニューに戻る', 'common.active': '有効', 'common.done': '完了',
    'common.close': '閉じる', 'common.gotIt': '了解', 'common.cancel': 'キャンセル', 'common.continue': '続ける',
    'common.exit': '退出', 'common.quit': '終了', 'common.play': 'プレイ', 'common.saved': '保存済み', 'common.goal': 'ゴール',
    'common.goals': 'ゴール', 'common.pts': 'PTS', 'common.you': 'あなた', 'common.opponent': '対戦相手',
    'common.watchAdCoins': '広告動画を見て+50無料コイン獲得', 'currency.coins': 'コイン',
    'btn.play': '今すぐプレイ', 'btn.select': '選択', 'btn.confirm': '決定', 'btn.cancel': 'キャンセル',
    'btn.close': '閉じる', 'btn.back': '戻る', 'btn.continue': '続ける', 'btn.nextMatch': '次の試合',
    'btn.returnMenu': 'メインメニュー', 'btn.equip': '装備する', 'btn.equipped': '装備中', 'btn.unlock': '解放する',
    'btn.locked': 'ロック中', 'btn.saveReplay': 'リプレイを保存', 'btn.save': '保存', 'btn.saved': '保存済み',
    'btn.skip': 'スキップ', 'btn.playAgain': 'もう一度プレイ', 'btn.watchAd': '動画を見る (+50コイン)', 'btn.freeCoins': '無料コイン',
    'hud.aim': 'エイム', 'hud.power': 'パワー', 'hud.curve': 'カーブ', 'hud.kick': 'シュート',
    'hud.stepAim': 'シュート角度を調整', 'hud.stepPower': 'パワーを決定', 'hud.stepCurve': 'カーブをかける',
    'hud.stepKick': 'シュートを放つ', 'hud.shoot': 'シュート！', 'hud.tapToLock': 'タップして決定',
    'hud.tapToKick': 'タップしてシュート', 'hud.goal': 'ゴール！', 'hud.saved': 'セーブ！', 'hud.missed': '枠外！',
    'hud.wallBlocked': '壁にブロックされた！', 'hud.postHit': 'ポスト直撃！', 'hud.suddenDeath': 'サドンデス',
    'hud.goldenGoal': 'ゴールデンゴール', 'hud.penaltyShootout': 'PK戦', 'hud.turn': 'ターン',
    'hud.yourTurn': 'あなたの番です', 'hud.oppTurn': '相手の番です', 'hud.aiThinking': 'AIが考慮中...',
    'hud.aiAiming': 'AIが照準中...', 'hud.aiStriking': 'AIがシュート中...', 'hud.timer': '残り時間',
    'hud.matchOver': '試合終了', 'hud.rematch': '再戦', 'hud.exitMatch': '試合を抜ける',
    'hud.resume': '再開', 'hud.pause': '一時停止', 'hud.yourTurnPenalty': 'あなたがPKを蹴ります',
    'hud.oppPenalty': '相手がPKを蹴ります...', 'hud.aiPenalty': 'AIがPKを蹴ります...',
    'hud.playIn': 'カメラ視点:', 'hud.ballTracking': 'ボール追従', 'hud.behindGoal': 'ゴール裏視点',
    'hud.meter': 'メーター', 'hud.aiGoalkeeper': 'AIゴールキーパー', 'hud.aiStriker': 'AIストライカー',
    'hud.defenseSim': '守備シミュレーション', 'hud.precisionFK': 'プレシジョンフリーキック', 'hud.aiming': 'エイム中',
    'hud.holdToCharge': '長押しでパワーチャージ', 'hud.releaseToStrikeInstruction': 'スペース / 画面を長押し • 離してシュート',
    'hud.weak': '弱い', 'hud.sweetSpot': '完璧', 'hud.max': 'MAX', 'hud.chargingPower': 'パワーチャージ中...',
    'hud.replay': 'リプレイ', 'game.goal': 'ゴール！', 'game.saved': 'セーブ',
    'quickPlay.selectMode': '試合モードを選択:', 'quickPlay.ranked': 'ランクマッチ', 'quickPlay.vsAi': 'VS AI / ローカル',
    'country.selectTeams': 'チーム選択', 'country.nationalTeams': '代表チーム', 'country.teamsAvailable': '利用可能な国',
    'country.tapToSelect': 'タップして選択', 'country.myTeam': 'マイチーム', 'country.opponent': '対戦相手',
    'country.continueToMatch': '試合へ進む', 'search.countries': '国名を検索...', 'teamSelect.teams': 'チーム',
    'teamSelect.searchPlaceholder': '代表チームを検索...', 'teamSelect.att': '攻撃', 'teamSelect.def': '守備',
    'team.selectNew': '新しいチームを選択', 'team.selectNewDesc': '世界120カ国の代表チームから選択',
    'online.matchTitle': 'オンライン対戦', 'online.matchSubtitle': 'リアルタイムで接続して代表チームを選択:',
    'online.createRoom': 'プライベートルーム作成', 'online.joinRoom': 'コードで参加', 'online.joinRoomTitle': 'ルームに参加',
    'online.roomCode': 'ルームコード', 'online.copyCode': 'コードをコピー', 'online.codeCopied': 'コピー完了！',
    'online.shareCode': 'この4桁コードを友達に共有:', 'online.enterCode': '4桁のコードを入力:',
    'online.findMatch': 'クイックマッチ検索', 'online.searchingMatch': '対戦相手を検索中...', 'online.stillSearching': 'プレイヤーを探しています...',
    'online.retrySearch': '再検索', 'online.cancelSearch': '検索をキャンセル', 'online.cancelRoom': 'ルームをキャンセル',
    'online.leaveRoom': 'ルームを退出', 'online.inviteLink': '招待リンクをコピー', 'online.linkCopied': 'リンクをコピーしました！',
    'online.lookingOpponent': '世界中のライバルを検索中...', 'online.pairingAuto': 'プレイヤーと接続中...', 'online.ready': '準備完了',
    'online.bothSelected': '両者準備完了！試合開始...', 'online.selectTeamBelow': '下からチームを選択してください:',
    'online.lockedIn': '確定', 'online.selecting': '選択中...', 'online.choosing': '国を選択中...',
    'online.opponentLeft': '対戦相手がルームを退出しました', 'online.opponentLeftSub': 'メニューに戻ります...',
    'online.roomCreated': 'ルーム作成完了', 'online.room': 'ルーム', 'online.host': 'ホスト', 'online.guest': 'ゲスト',
    'online.firstTurn': 'あなたが先攻です', 'online.secondTurn': '相手が先攻です',
    'online.matchStartingIn': '試合開始まで', 'online.kickoff': 'キックオフ！',
    'online.leaveMatchTitle': '試合を退出しますか？', 'online.leaveMatchSub': '途中で退出すると相手の不戦勝となります。',
    'online.leaveMatch': '試合を退出', 'online.leave': '退出', 'online.returnToMenu': 'メニューに戻る',
    'online.returningToMenu': 'メニューへ移動中...', 'online.sessionDisconnected': '切断されました',
    'online.yourCountry': 'あなたの代表国', 'online.oppCountry': '相手の代表国',
    'online.waitingOpponent': '相手のチーム選択を待っています...', 'online.waitingOpponentCode': 'コード入力待ち...',
    'online.connectSub': '全世界リアルタイム1v1マルチプレイサーバー', 'modal.matchmaking': '対戦相手を検索中...',
    'modal.matchmakingDesc': 'グローバルサーバーを検索中', 'modal.searchingTime': '検索時間',
    'modal.opponentFound': '対戦相手が見つかりました！', 'modal.connectingBot': '30秒でボットとマッチング...',
    'modal.quitMatchSub': '試合の進行状況は保存されません。', 'modal.forfeitMatchTitle': '降伏しますか？',
    'modal.forfeitMatchSub': '今退出すると敗北扱いになります。', 'modal.forfeit': '降伏する',
    'match.opponentLeftTitle': '相手が退出しました', 'match.opponentLeftDesc': '対戦相手の接続が切れました。',
    'match.playAgainUnavailable': '相手が退出したため再戦できません。',
    'match.waitingOpponent': '相手の応答を待っています...', 'match.changeTeams': 'チームを変更',
    'tournament.selectFormat': '形式を選択:', 'tournament.globalCup': 'グローバルカップ', 'tournament.customCup': 'カスタムカップ',
    'tournament.inDevelopment': '開発中', 'tournament.onlineWorldCup': 'オンラインワールドカップ',
    'tournament.multiplayerWorldCup': 'マルチプレイワールドカップ＆トーナメント', 'tournament.knockoutBrackets': '16チーム勝ち抜き戦',
    'tournament.knockoutBracketsSub': 'リアルタイムトーナメントマッチ', 'tournament.globalLeaderboards': 'グローバルシーズンランキング',
    'tournament.globalLeaderboardsSub': 'ランクポイントとトロフィーを獲得', 'tournament.exclusiveUnlockables': '限定チャンピオンユニフォーム＆ボール',
    'tournament.exclusiveUnlockablesSub': '優勝者限定のスペシャルリワード', 'tournament.playOfflineNow': 'オフラインワールドカップをプレイ',
    'tournament.selectYourTeam': '代表チームを選択', 'tournament.worldCupQualifiedSub': 'FIFAワールドカップ • 出場40カ国（グループA〜J）',
    'tournament.searchCountry': '国名またはグループを検索...', 'tournament.qualifiedNations': '出場国一覧',
    'tournament.tapToSelect': 'タップして選択', 'tournament.selected': '選択済み', 'tournament.ovr': 'OVR',
    'tournament.randomGroupDraw': '開始時にグループをランダム抽選', 'tournament.tapAnyCountryPrompt': '国をタップしてチームを選択',
    'tournament.enterWorldCup': 'ワールドカップ本大会へ進む（グループA-J）', 'tournament.backToMenu': 'メインメニュー',
    'tournament.forfeitMatch': '試合を棄権', 'tournament.continue': '決勝トーナメントへ進む',
    'tournament.championTitle': '★ 世界王者 ★', 'tournament.worldChampions': '世界チャンピオン',
    'tournament.winnerLiftsCup': 'ワールドカップトロフィーを掲げました！', 'tournament.freeKickCup': 'フリーキック世界大会',
    'tournament.roundOf16': 'ラウンド16', 'tournament.quarterFinals': '準々決勝', 'tournament.semiFinal1': '準決勝 1',
    'tournament.semiFinal2': '準決勝 2', 'tournament.worldFinal': 'ワールドカップ決勝', 'tournament.awaitingFinal': '決勝進出者待ち',
    'tournament.fixture': '対戦カード', 'tournament.ft': '試合終了', 'tournament.tbd': '未定', 'tournament.cancelTournament': 'トーナメント中止',
    'practice.selectDrill': '練習メニューを選択:', 'practice.freeKick': 'フリーキック',
    'practice.freeKickSub': '即時プレイ • 壁とコースの狙い撃ち', 'practice.instant': '即時',
    'practice.penalty': 'ペナルティキック', 'practice.penaltySub': 'GKと1対1 • 時間無制限', 'practice.random': 'ランダム',
    'practice.exitTitle': '練習を終了しますか？', 'practice.exitSub': 'いつでもメインメニューに戻れます。',
    'practice.exitButton': '練習を終了', 'survival.title': 'サバイバルアリーナ',
    'survival.subtitle': 'ライフ3 • 無限連勝 • デュエル', 'survival.arenaTitle': 'サバイバルアリーナ',
    'survival.onlineSurvivalTitle': 'オンライン 1v1 サバイバル',
    'survival.onlineSurvivalSubtitle': 'ライフ3 • リアルタイム1v1 • 無限ゴール記録チャレンジ',
    'survival.selectGameMode': 'ゲームモードを選択:', 'survival.offlineSurvivalBtn': 'オフライン サバイバル',
    'survival.onlineDuelBtn': 'オンライン 1v1 デュエル', 'survival.rulesBtn': 'ルール',
    'survival.rulesTitle': 'サバイバルルール', 'survival.rulesSubtitle': '最高記録を狙うための2つのルール:',
    'survival.rule1Title': '3ライフ制',
    'survival.rule1Desc': 'お互いハート3つからスタート。枠外やGKセーブでライフが1減少。先にライフが0になった方の負け！',
    'survival.rule2Title': '交互キック＆100秒タイマー',
    'survival.rule2Desc': '100秒カウントダウンで交互にフリーキック。ゴールを決めて連勝を伸ばそう！',
    'survival.backToRules': 'ルールへ戻る', 'survival.howItWorks': '遊び方', 'survival.guideBadge': 'サバイバルガイド',
    'survival.livesRemaining': '残りライフ', 'survival.bestRecord': '歴代最高記録', 'survival.bestStreak': '最高連勝',
    'survival.startRun': '挑戦スタート', 'survival.personalRecord': '自己ベスト', 'survival.goalStreak': '連続ゴール数',
    'survival.goalsStreak': '連続ゴール数', 'survival.kicks': 'キック数', 'survival.duel': 'サバイバル 1v1 デュエル',
    'survival.duelSub': 'オンラインノックアウトマッチ', 'survival.runEnded': '挑戦終了！',
    'survival.challengeComplete': 'サバイバルチャレンジ終了', 'survival.finalGoalsStreak': '最終ゴール記録',
    'survival.challengeMode': 'チャレンジモード', 'survival.reviveExtraLife': 'コンティニュー (+1ライフ回復)',
    'survival.endSurvivalTitle': 'サバイバルを終了しますか？', 'survival.endSurvival': '終了', 'survival.endRun': '挑戦を終了',
    'survival.concludeSub': '試合を直ちに終了します。', 'survival.currentStreak': '現在の連勝:',
    'wager.title': '賭けアリーナ', 'wager.subtitle': '賭け金を選択 • 勝者が全コイン総取り！',
    'wager.rookie': 'ルーキーアリーナ', 'wager.pro': 'プロアリーナ', 'wager.champion': 'チャンピオンアリーナ', 'wager.legend': 'レジェンドアリーナ',
    'wager.entryFee': '参加費', 'wager.entry': '参加', 'wager.prizePot': '賞金総額', 'wager.winPot': '勝利報酬',
    'wager.highRoller': 'ハイステークスデュエル', 'wager.bottomBanner': 'アリーナに挑戦 • 高い賭け金で2倍の報酬！',
    'wager.tapToSelect': 'タップして選択', 'wager.playWithCoins': 'コインで勝負', 'wager.needMoreCoins': 'コインが不足しています',
    'wager.forfeitWager': '勝負を降りる', 'wager.surrenderTitle': '降伏しますか？',
    'wager.surrenderSub': '降伏すると賭けたコインを失います:', 'wager.surrender': '降伏する', 'wager.victory': '賭けマッチ勝利！',
    'wager.coinDuelResults': 'デュエル結果', 'wager.drawRefunded': '引き分け • 参加費返還',
    'wager.arenaPot': 'アリーナ総額', 'wager.netResult': '純獲得額',
    'wager.opponentLeft': '相手がアリーナから退出しました', 'wager.rematch': '賭け再戦',
    'targetSmash.title': 'ターゲットスマッシュ', 'targetSmash.arcadeBadge': '新アーケードモード',
    'targetSmash.trickshotSubtitle': '的当て＆トリックスマッシュ', 'targetSmash.selectStage': 'ステージ (1 - 10)',
    'targetSmash.unlocked': '解放済み', 'targetSmash.stage': 'ステージ', 'targetSmash.objective': '目標',
    'targetSmash.highScore': 'ハイスコア', 'targetSmash.pts': 'PTS', 'targetSmash.distance': '距離',
    'targetSmash.defendersWall': '守備の壁', 'targetSmash.players': '人数', 'targetSmash.targetScore': '目標スコア',
    'targetSmash.targetRequired': '必要スコア', 'targetSmash.playStage': 'ステージをプレイ', 'targetSmash.stageLocked': 'ロック中',
    'targetSmash.stageCleared': 'ステージクリア！', 'targetSmash.stageFailed': 'ステージ失敗', 'targetSmash.finalScore': '最終スコア',
    'targetSmash.coinsReward': '獲得コイン', 'targetSmash.nextStage': '次のステージ', 'targetSmash.retryStage': 'リトライ',
    'targetSmash.exitToSelect': 'ステージ選択へ', 'divisions.title': 'ディビジョンリーグ', 'divisions.titleUpper': 'ディビジョンリーグ',
    'divisions.rank': 'ディビジョン順位', 'divisions.titleTarget': 'タイトル目標', 'divisions.titleClaimed': 'タイトル獲得！',
    'divisions.ptsForTrophy': 'トロフィーに必要な勝ち点', 'divisions.seasonFinished': 'シーズン終了',
    'divisions.promotionAchieved': '昇格達成！', 'divisions.thisSeason': '今シーズン',
    'divisions.matchesLeft': '残り試合数', 'divisions.ptsNeeded': '必要勝ち点', 'divisions.win': '勝',
    'divisions.draw': '分', 'divisions.loss': '敗', 'divisions.pt': '点', 'divisions.pts': '点',
    'divisions.allTime': '通算成績', 'divisions.matchesHistory': '対戦履歴', 'divisions.match': '試合',
    'divisions.noMatchesYet': '今シーズンはまだ試合がありません', 'divisions.noMatchesSub': '下からシーズンを開始しましょう！',
    'divisions.nextMatchChooseOpponent': '次の試合 • 相手を選択', 'divisions.whoDoYouWantToPlay': '対戦相手を選択:',
    'divisions.teamsAvailable': '利用可能なチーム', 'divisions.searchNationalTeam': '代表チームを検索...',
    'divisions.playMatchVs': '対戦する:', 'divisions.opponent': '対戦相手', 'divisions.opponentUpper': '対戦相手',
    'divisions.opponentConnected': '相手接続完了', 'divisions.change': '変更', 'divisions.chooseOpponent': '対戦相手を選ぶ',
    'divisions.divShort': 'DIV', 'divisions.of': '/', 'divisions.continueTo': '次へ:', 'divisions.next': '次へ',
    'divisions.findingOpponent': 'ディビジョンの対戦相手を検索中...', 'divisions.matchingWithOnline': '同ディビジョンのプレイヤーとマッチング中',
    'divisions.searchingActivePlayers': 'サーバー内を検索中...', 'divisions.matchStartingIn': '試合開始まで',
    'divisions.cancelMatchmaking': 'キャンセル', 'divisions.cancelSearch': '検索キャンセル', 'divisions.wdl': '勝-分-敗',
    'division.return': 'ディビジョン一覧に戻る', 'division.reward': 'ディビジョン報酬', 'result.victory': '勝利！',
    'result.defeat': '敗北', 'result.draw': '引き分け', 'result.champion': '世界王者誕生！', 'result.prizeWon': '獲得賞金',
    'result.streak': '現在の連勝', 'result.newRecord': '新記録達成！', 'result.coinsEarned': '獲得コイン',
    'result.finalScore': '最終スコア', 'result.totalScore': '合計スコア', 'result.wonOnPenalties': 'PK戦勝利',
    'result.lostOnPenalties': 'PK戦敗北', 'result.survivalVictory': 'サバイバル勝利！',
    'result.survivalDefeat': 'サバイバル敗退', 'result.wagerResults': '賭けマッチ結果',
    'rematch.invitationTitle': '再戦リクエスト', 'rematch.invitationDesc': '対戦相手が再戦を申し込んでいます！',
    'rematch.accept': '再戦を受ける', 'rematch.decline': '拒否する', 'rematch.starting': '再戦を開始中...',
    'rematch.survivalRequested': '相手がサバイバル再戦を要求しています！',
    'rematch.survivalDesc': '承諾してすぐに1v1バトルへ戻ろう！',
    'rematch.wagerChallenge': 'が賭けマッチの再戦を挑んできました！', 'stats.goals': 'ゴール数', 'stats.shots': 'シュート数',
    'status.live': 'LIVE', 'status.offline': 'オフライン', 'status.winner': '勝者', 'status.eliminated': '敗退',
    'status.survived': '生存', 'status.left': '退出', 'status.disconnected': '切断',
    'store.title': '装備ショップ', 'store.subtitle': '3Dボールスキン＆スタジアム芝パターン',
    'store.balls': 'ボール', 'store.pitches': '芝生', 'store.ballStore': 'ボールショップ',
    'store.ballStoreDesc': '3Dスキン＆プロモデル', 'store.pitchStore': 'スタジアムショップ',
    'store.pitchStoreDesc': 'スタジアムの芝刈りパターン', 'store.selectCategory': 'カテゴリー選択',
    'store.unlockedAndEquipped': '解放＆装備済み', 'store.owned': '所持中', 'store.buyFor': '購入:',
    'store.notEnoughCoins': 'コインが足りません！', 'store.needMore': 'あと', 'store.more': '必要',
    'profile.title': 'プレイヤープロフィール', 'profile.cloudStorageNotice': 'CRAZYGAMES クラウド＆ローカルに保存',
    'replays.subtitle': '保存した最高のゴールハイライトを再生・管理', 'replays.savedReplays': '保存したリプレイ',
    'replays.savedHighlights': '保存済みハイライト', 'replays.clips': 'クリップ', 'replays.savedClips': '保存済みクリップ',
    'replays.noSavedReplays': 'リプレイはまだありません', 'replays.noHighlightsTitle': 'ハイライトがありません',
    'replays.noHighlightsDesc': '試合でゴールを決めて、リプレイ画面で「保存」をタップ！',
    'replays.playMatchNow': '今すぐ試合をする', 'replays.emptyInstructions': 'ゴールを決めてリプレイ右上の「保存」をタップするとここに記録されます！',
    'replays.savedHighlight': '保存されたハイライト', 'replays.savedDate': '日時', 'replays.shotDistance': 'シュート距離',
    'replays.longestStrike': '最長ゴール', 'replays.goalHighlights': 'ゴール集', 'replays.watchReplay': 'リプレイを見る',
    'replays.exitReplay': 'リプレイを閉じる', 'replays.deleteReplay': 'リプレイを削除',
    'replays.confirmDelete': 'このハイライトを削除しますか？', 'replays.deleteAllConfirm': '全てのリプレイを削除しますか？',
    'replays.deleteAllDesc': '保存したすべてのリプレイを消去してもよろしいですか？', 'ads.videoReward': '動画リワード',
    'ads.coinsReward': 'コインリワード', 'ads.watchToEarn': '広告動画を見て+50コイン獲得',
    'ads.instantBoost': 'コイン即時ブースト', 'ads.integrationFinalizing': '広告統合の準備中です。',
    'ads.unlockAllItems': '50種類のボールと50種類の芝生を全てアンロックしよう！', 'ads.loading': '広告を読み込み中...',
    'lang.title': '言語設定', 'lang.subtitle': '言語を選択してください（全16言語対応）',
    'lang.autoDetect': '自動検出された言語', 'lang.currentlyActive': '現在選択中',
    'lang.sdkSyncTitle': 'CrazyGames 同期', 'lang.sdkSyncDesc': 'ゲーム内の言語はCrazyGamesの設定と自動連動します',
    'lang.searchPlaceholder': '言語または国名を検索...', 'lang.tabAll': 'すべて (16)', 'lang.tabPopular': '人気',
    'lang.tabEurope': 'ヨーロッパ', 'lang.tabAmericas': 'アメリカ', 'lang.tabAsiaMe': 'アジア＆中東',
    'lang.noMatches': '該当する言語が見つかりません', 'lang.noMatchesDesc': '別の言語名や国名でお試しください',
    'lang.resetFilters': 'フィルターをリセット'
}

ko = {
    'nav.store': '상점', 'nav.profile': '프로필', 'nav.replays': '다시보기', 'nav.coins': '코인',
    'nav.language': '언어', 'nav.bestStreak': '최고 연승', 'nav.online': '온라인', 'nav.connecting': '연결 중...',
    'game.title': 'FREE KICK LEGENDS', 'menu.quickPlay': '빠른 경기', 'menu.quickPlaySub': '온라인 및 오프라인 경기',
    'menu.survivalMode': '서바이벌 모드', 'survival.threeLives': '목숨 3개', 'survival.endlessStreak': '무한 연속 득점',
    'survival.best': '최고 기록', 'survival.streak': '연속 기록', 'survival.onlineAvailable': '온라인 1대1 서바이벌 가능',
    'menu.wagerArena': '베팅 아레나', 'wager.betCoinsPot': '코인 베팅 • 승자 독식',
    'wager.onlineDuel': '온라인 1대1 코인 베팅전', 'wager.duel': '결투', 'wager.arena': '아레나', 'wager.bet': '베팅금',
    'wager.winnerTakes': '승자 총 획득', 'wager.prizePot': '총 상금', 'menu.worldCup': 'FIFA 월드컵',
    'menu.tournamentFormat': '토너먼트 방식', 'menu.practice': '연습장', 'menu.practiceSub': '프리킥 훈련',
    'menu.shop': '상점', 'menu.onlineMultiplayer': '온라인 멀티플레이 가능',
    'profile.savedReplaysStats': '다시보기 및 전적', 'replays.title': '저장된 다시보기',
    'common.coins': '코인', 'common.coinsUpper': '코인', 'common.online': '온라인', 'common.offline': '오프라인',
    'common.back': '뒤로', 'common.backToMenu': '메뉴로 돌아가기', 'common.active': '활성', 'common.done': '완료',
    'common.close': '닫기', 'common.gotIt': '확인', 'common.cancel': '취소', 'common.continue': '계속하기',
    'common.exit': '나가기', 'common.quit': '종료', 'common.play': '플레이', 'common.saved': '저장됨', 'common.goal': '골',
    'common.goals': '골', 'common.pts': 'PTS', 'common.you': '나', 'common.opponent': '상대방',
    'common.watchAdCoins': '광고 시청하고 +50 무료 코인 받기', 'currency.coins': '코인',
    'btn.play': '지금 플레이', 'btn.select': '선택', 'btn.confirm': '확인', 'btn.cancel': '취소',
    'btn.close': '닫기', 'btn.back': '뒤로', 'btn.continue': '계속', 'btn.nextMatch': '다음 경기',
    'btn.returnMenu': '메인 메뉴', 'btn.equip': '장착', 'btn.equipped': '장착됨', 'btn.unlock': '잠금 해제',
    'btn.locked': '잠김', 'btn.saveReplay': '리플레이 저장', 'btn.save': '저장', 'btn.saved': '저장됨',
    'btn.skip': '건너뛰기', 'btn.playAgain': '다시 플레이', 'btn.watchAd': '동영상 시청 (+50 코인)', 'btn.freeCoins': '무료 코인',
    'hud.aim': '조준', 'hud.power': '파워', 'hud.curve': '감아차기', 'hud.kick': '슈팅',
    'hud.stepAim': '슈팅 각도 조절', 'hud.stepPower': '파워 설정', 'hud.stepCurve': '스핀 및 회전 적용',
    'hud.stepKick': '슈팅 실행', 'hud.shoot': '슛!', 'hud.tapToLock': '터치하여 고정',
    'hud.tapToKick': '터치하여 슈팅', 'hud.goal': '골!', 'hud.saved': '선방!', 'hud.missed': '빗나감!',
    'hud.wallBlocked': '수비벽에 막힘!', 'hud.postHit': '골대 강타!', 'hud.suddenDeath': '서든데스',
    'hud.goldenGoal': '골든골', 'hud.penaltyShootout': '승부차기', 'hud.turn': '턴',
    'hud.yourTurn': '내 차례', 'hud.oppTurn': '상대방 차례', 'hud.aiThinking': 'AI 생각 중...',
    'hud.aiAiming': 'AI 조준 중...', 'hud.aiStriking': 'AI 슈팅 중...', 'hud.timer': '남은 시간',
    'hud.matchOver': '경기 종료', 'hud.rematch': '재대결', 'hud.exitMatch': '경기 나가기',
    'hud.resume': '이어하기', 'hud.pause': '일시정지', 'hud.yourTurnPenalty': '내 패널티킥 차례',
    'hud.oppPenalty': '상대방이 패널티킥을 찹니다...', 'hud.aiPenalty': 'AI가 패널티킥을 찹니다...',
    'hud.playIn': '카메라 시점:', 'hud.ballTracking': '볼 추적', 'hud.behindGoal': '골대 뒤 시점',
    'hud.meter': '게이지', 'hud.aiGoalkeeper': 'AI 골키퍼', 'hud.aiStriker': 'AI 공격수',
    'hud.defenseSim': '수비 시뮬레이션', 'hud.precisionFK': '정밀 프리킥', 'hud.aiming': '조준 중',
    'hud.holdToCharge': '길게 눌러 파워 충전', 'hud.releaseToStrikeInstruction': '스페이스바 / 화면 길게 누르기 • 손을 떼면 슈팅',
    'hud.weak': '약함', 'hud.sweetSpot': '완벽', 'hud.max': '최대', 'hud.chargingPower': '파워 충전 중...',
    'hud.replay': '리플레이', 'game.goal': '골!', 'game.saved': '선방',
    'quickPlay.selectMode': '경기 모드 선택:', 'quickPlay.ranked': '랭크전', 'quickPlay.vsAi': 'VS AI / 로컬',
    'country.selectTeams': '팀 선택', 'country.nationalTeams': '국가대표팀', 'country.teamsAvailable': '선택 가능한 국가',
    'country.tapToSelect': '터치하여 선택', 'country.myTeam': '내 팀', 'country.opponent': '상대팀',
    'country.continueToMatch': '경기 시작하기', 'search.countries': '국가 검색...', 'teamSelect.teams': '팀',
    'teamSelect.searchPlaceholder': '대표팀 검색...', 'teamSelect.att': '공격', 'teamSelect.def': '수비',
    'team.selectNew': '새로운 팀 선택', 'team.selectNewDesc': '전 세계 120개 국가대표팀 중 선택',
    'online.matchTitle': '온라인 경기', 'online.matchSubtitle': '실시간으로 접속하여 팀을 선택하세요:',
    'online.createRoom': '비공개 방 만들기', 'online.joinRoom': '코드로 참가', 'online.joinRoomTitle': '방 참가하기',
    'online.roomCode': '방 코드', 'online.copyCode': '코드 복사', 'online.codeCopied': '복사 완료!',
    'online.shareCode': '친구에게 4자리 코드를 공유하세요:', 'online.enterCode': '4자리 코드 입력:',
    'online.findMatch': '빠른 매칭', 'online.searchingMatch': '상대 찾는 중...', 'online.stillSearching': '접속 중인 플레이어 검색 중...',
    'online.retrySearch': '다시 찾기', 'online.cancelSearch': '검색 취소', 'online.cancelRoom': '방 취소',
    'online.leaveRoom': '방 나가기', 'online.inviteLink': '초대 링크 복사', 'online.linkCopied': '링크 복사 완료!',
    'online.lookingOpponent': '전 세계의 상대를 찾는 중...', 'online.pairingAuto': '플레이어 연결 중...', 'online.ready': '준비 완료',
    'online.bothSelected': '양측 준비 완료! 경기 시작...', 'online.selectTeamBelow': '아래에서 팀을 선택하세요:',
    'online.lockedIn': '확정', 'online.selecting': '선택 중...', 'online.choosing': '대표팀 고르는 중...',
    'online.opponentLeft': '상대방이 방을 나갔습니다', 'online.opponentLeftSub': '곧 메뉴로 돌아갑니다...',
    'online.roomCreated': '방 생성 완료', 'online.room': '방', 'online.host': '방장', 'online.guest': '참가자',
    'online.firstTurn': '내가 선축입니다', 'online.secondTurn': '상대방이 선축입니다',
    'online.matchStartingIn': '경기 시작까지', 'online.kickoff': '킥오프!',
    'online.leaveMatchTitle': '경기를 나가시겠습니까?', 'online.leaveMatchSub': '중도 포기 시 상대방의 부전승으로 처리됩니다.',
    'online.leaveMatch': '경기 나가기', 'online.leave': '나가기', 'online.returnToMenu': '메뉴로 돌아가기',
    'online.returningToMenu': '메뉴로 이동 중...', 'online.sessionDisconnected': '연결이 끊어졌습니다',
    'online.yourCountry': '나의 대표팀', 'online.oppCountry': '상대 대표팀',
    'online.waitingOpponent': '상대방의 팀 선택 대기 중...', 'online.waitingOpponentCode': '코드 입력 대기 중...',
    'online.connectSub': '글로벌 실시간 1대1 멀티플레이 서버', 'modal.matchmaking': '상대방 찾는 중...',
    'modal.matchmakingDesc': '글로벌 서버 검색 중', 'modal.searchingTime': '경과 시간',
    'modal.opponentFound': '상대 발견!', 'modal.connectingBot': '30초 내 봇과 연결됩니다...',
    'modal.quitMatchSub': '현재 경기 기록은 저장되지 않습니다.', 'modal.forfeitMatchTitle': '기권하시겠습니까?',
    'modal.forfeitMatchSub': '지금 나가면 패배로 기록됩니다.', 'modal.forfeit': '기권하기',
    'match.opponentLeftTitle': '상대방이 나갔습니다', 'match.opponentLeftDesc': '상대 플레이어의 접속이 끊어졌습니다.',
    'match.playAgainUnavailable': '상대방이 나가서 재대결할 수 없습니다.',
    'match.waitingOpponent': '상대방의 응답을 기다리는 중...', 'match.changeTeams': '팀 변경',
    'tournament.selectFormat': '토너먼트 방식 선택:', 'tournament.globalCup': '글로벌 컵', 'tournament.customCup': '커스텀 컵',
    'tournament.inDevelopment': '개발 중', 'tournament.onlineWorldCup': '온라인 월드컵',
    'tournament.multiplayerWorldCup': '멀티플레이 월드컵 및 토너먼트 대진표', 'tournament.knockoutBrackets': '16강 토너먼트 대진표',
    'tournament.knockoutBracketsSub': '실시간 토너먼트 매치', 'tournament.globalLeaderboards': '글로벌 시즌 랭킹',
    'tournament.globalLeaderboardsSub': '랭킹 점수와 트로피 획득', 'tournament.exclusiveUnlockables': '챔피언 전용 유니폼 및 공',
    'tournament.exclusiveUnlockablesSub': '우승자만을 위한 특별 보상', 'tournament.playOfflineNow': '오프라인 월드컵 플레이',
    'tournament.selectYourTeam': '대표팀 선택', 'tournament.worldCupQualifiedSub': 'FIFA 월드컵 • 40개 본선 진출국 (A ~ J조)',
    'tournament.searchCountry': '국가 또는 조 검색...', 'tournament.qualifiedNations': '본선 진출국',
    'tournament.tapToSelect': '터치하여 선택', 'tournament.selected': '선택됨', 'tournament.ovr': 'OVR',
    'tournament.randomGroupDraw': '시작 시 무작위 조 추첨', 'tournament.tapAnyCountryPrompt': '국가를 터치하여 팀을 고르세요',
    'tournament.enterWorldCup': '월드컵 참가 (A - J조)', 'tournament.backToMenu': '메인 메뉴',
    'tournament.forfeitMatch': '경기 기권', 'tournament.continue': '토너먼트 본선 진출',
    'tournament.championTitle': '★ 세계 챔피언 ★', 'tournament.worldChampions': '월드 챔피언',
    'tournament.winnerLiftsCup': '월드컵 트로피를 들어올렸습니다!', 'tournament.freeKickCup': '프리킥 세계 선수권 대회',
    'tournament.roundOf16': '16강전', 'tournament.quarterFinals': '8강전', 'tournament.semiFinal1': '준결승 1',
    'tournament.semiFinal2': '준결승 2', 'tournament.worldFinal': '월드컵 결승전', 'tournament.awaitingFinal': '결승 상대 대기 중',
    'tournament.fixture': '대진표', 'tournament.ft': '종료', 'tournament.tbd': '미정', 'tournament.cancelTournament': '토너먼트 취소',
    'practice.selectDrill': '훈련 선택:', 'practice.freeKick': '프리킥',
    'practice.freeKickSub': '빠른 연습 • 수비벽 및 코너 공략', 'practice.instant': '즉시',
    'practice.penalty': '패널티킥', 'practice.penaltySub': '골키퍼와 1대1 • 시간 무제한', 'practice.random': '무작위',
    'practice.exitTitle': '훈련을 종료하시겠습니까?', 'practice.exitSub': '언제든지 메인 메뉴로 돌아갈 수 있습니다.',
    'practice.exitButton': '훈련 종료', 'survival.title': '서바이벌 아레나',
    'survival.subtitle': '목숨 3개 • 무한 연속 득점 • 결투', 'survival.arenaTitle': '서바이벌 아레나',
    'survival.onlineSurvivalTitle': '온라인 1대1 서바이벌',
    'survival.onlineSurvivalSubtitle': '목숨 3개 • 실시간 1대1 대결 • 무한 골 기록 도전',
    'survival.selectGameMode': '게임 모드 선택:', 'survival.offlineSurvivalBtn': '오프라인 서바이벌',
    'survival.onlineDuelBtn': '온라인 1대1 결투', 'survival.rulesBtn': '규칙',
    'survival.rulesTitle': '서바이벌 규칙', 'survival.rulesSubtitle': '최고 기록 달성을 위한 2가지 규칙:',
    'survival.rule1Title': '3목숨 시스템',
    'survival.rule1Desc': '하트 3개로 시작합니다. 실축하거나 선방에 막히면 목숨 1개가 차감됩니다. 먼저 목숨이 다하면 패배!',
    'survival.rule2Title': '교대 슈팅 및 100초 타이머',
    'survival.rule2Desc': '100초 제한시간 동안 번갈아가며 프리킥을 찹니다. 골을 넣어 연승 기록을 이어가세요!',
    'survival.backToRules': '규칙으로 돌아가기', 'survival.howItWorks': '진행 방식', 'survival.guideBadge': '서바이벌 가이드',
    'survival.livesRemaining': '남은 목숨', 'survival.bestRecord': '역대 최고 기록', 'survival.bestStreak': '최고 연속 득점',
    'survival.startRun': '도전 시작', 'survival.personalRecord': '개인 최고 기록', 'survival.goalStreak': '연속 골 기록',
    'survival.goalsStreak': '연속 골 기록', 'survival.kicks': '슈팅 수', 'survival.duel': '서바이벌 1대1 결투',
    'survival.duelSub': '온라인 토너먼트 매치', 'survival.runEnded': '도전 종료!',
    'survival.challengeComplete': '서바이벌 도전 완료', 'survival.finalGoalsStreak': '최종 연속 골 기록',
    'survival.challengeMode': '도전 모드', 'survival.reviveExtraLife': '부활하기 (+1 추가 목숨)',
    'survival.endSurvivalTitle': '서바이벌을 종료하시겠습니까?', 'survival.endSurvival': '종료', 'survival.endRun': '도전 종료',
    'survival.concludeSub': '경기가 즉시 중단됩니다.', 'survival.currentStreak': '현재 연속 득점:',
    'wager.title': '베팅 아레나', 'wager.subtitle': '베팅금 선택 • 승자가 모든 코인을 독식합니다!',
    'wager.rookie': '루키 아레나', 'wager.pro': '프로 아레나', 'wager.champion': '챔피언 아레나', 'wager.legend': '레전드 아레나',
    'wager.entryFee': '참가비', 'wager.entry': '입장', 'wager.prizePot': '총 상금', 'wager.winPot': '우승 상금',
    'wager.highRoller': '고액 베팅 실시간 결투', 'wager.bottomBanner': '아레나 탐색 • 높은 베팅금, 2배의 상금!',
    'wager.tapToSelect': '터치하여 선택', 'wager.playWithCoins': '코인으로 플레이', 'wager.needMoreCoins': '코인이 부족합니다',
    'wager.forfeitWager': '베팅 포기', 'wager.surrenderTitle': '기권하시겠습니까?',
    'wager.surrenderSub': '기권하면 베팅한 코인을 모두 잃게 됩니다:', 'wager.surrender': '기권하기', 'wager.victory': '베팅 매치 승리!',
    'wager.coinDuelResults': '결투 결과', 'wager.drawRefunded': '무승부 • 참가비 환불',
    'wager.arenaPot': '아레나 상금', 'wager.netResult': '순수익',
    'wager.opponentLeft': '상대방이 아레나를 나갔습니다', 'wager.rematch': '베팅 재대결',
    'targetSmash.title': '타겟 스매시', 'targetSmash.arcadeBadge': '신규 아케이드 모드',
    'targetSmash.trickshotSubtitle': '타겟 맞히기 & 스핀 트릭샷', 'targetSmash.selectStage': '스테이지 (1 - 10)',
    'targetSmash.unlocked': '잠금 해제됨', 'targetSmash.stage': '스테이지', 'targetSmash.objective': '목표',
    'targetSmash.highScore': '최고 점수', 'targetSmash.pts': 'PTS', 'targetSmash.distance': '거리',
    'targetSmash.defendersWall': '수비벽', 'targetSmash.players': '수비수', 'targetSmash.targetScore': '목표 점수',
    'targetSmash.targetRequired': '필요 점수', 'targetSmash.playStage': '스테이지 플레이', 'targetSmash.stageLocked': '잠긴 스테이지',
    'targetSmash.stageCleared': '스테이지 클리어!', 'targetSmash.stageFailed': '스테이지 실패', 'targetSmash.finalScore': '최종 점수',
    'targetSmash.coinsReward': '코인 보상', 'targetSmash.nextStage': '다음 스테이지', 'targetSmash.retryStage': '다시 시도',
    'targetSmash.exitToSelect': '스테이지 선택으로', 'divisions.title': '디비전 리그', 'divisions.titleUpper': '디비전 리그',
    'divisions.rank': '디비전 순위', 'divisions.titleTarget': '우승 목표', 'divisions.titleClaimed': '우승 달성!',
    'divisions.ptsForTrophy': '우승 트로피 필요 승점', 'divisions.seasonFinished': '시즌 종료',
    'divisions.promotionAchieved': '승격 달성!', 'divisions.thisSeason': '이번 시즌',
    'divisions.matchesLeft': '남은 경기', 'divisions.ptsNeeded': '필요 승점', 'divisions.win': '승',
    'divisions.draw': '무', 'divisions.loss': '패', 'divisions.pt': '점', 'divisions.pts': '점',
    'divisions.allTime': '통산 전적', 'divisions.matchesHistory': '경기 기록', 'divisions.match': '경기',
    'divisions.noMatchesYet': '이번 시즌 진행된 경기가 없습니다', 'divisions.noMatchesSub': '아래에서 새 시즌을 시작하세요!',
    'divisions.nextMatchChooseOpponent': '다음 경기 • 상대 선택', 'divisions.whoDoYouWantToPlay': '대결할 상대를 선택하세요:',
    'divisions.teamsAvailable': '선택 가능한 팀', 'divisions.searchNationalTeam': '국가대표팀 검색...',
    'divisions.playMatchVs': '경기 시작 VS', 'divisions.opponent': '상대방', 'divisions.opponentUpper': '상대방',
    'divisions.opponentConnected': '상대 연결됨', 'divisions.change': '변경', 'divisions.chooseOpponent': '상대 선택',
    'divisions.divShort': 'DIV', 'divisions.of': '/', 'divisions.continueTo': '다음 디비전:', 'divisions.next': '다음',
    'divisions.findingOpponent': '디비전 상대 검색 중...', 'divisions.matchingWithOnline': '같은 디비전 플레이어와 매칭 중',
    'divisions.searchingActivePlayers': '서버 탐색 중...', 'divisions.matchStartingIn': '경기 시작까지',
    'divisions.cancelMatchmaking': '취소', 'divisions.cancelSearch': '검색 취소', 'divisions.wdl': '승-무-패',
    'division.return': '디비전으로 돌아가기', 'division.reward': '디비전 보상', 'result.victory': '승리!',
    'result.defeat': '패배', 'result.draw': '무승부', 'result.champion': '세계 챔피언 등극!', 'result.prizeWon': '획득 상금',
    'result.streak': '현재 연승', 'result.newRecord': '새로운 기록!', 'result.coinsEarned': '획득 코인',
    'result.finalScore': '최종 스코어', 'result.totalScore': '총 점수', 'result.wonOnPenalties': '승부차기 승리',
    'result.lostOnPenalties': '승부차기 패배', 'result.survivalVictory': '서바이벌 승리!',
    'result.survivalDefeat': '서바이벌 탈락', 'result.wagerResults': '베팅 결과',
    'rematch.invitationTitle': '재대결 신청', 'rematch.invitationDesc': '상대방이 재대결을 원합니다!',
    'rematch.accept': '재대결 수락', 'rematch.decline': '거절', 'rematch.starting': '재대결 준비 중...',
    'rematch.survivalRequested': '상대방이 서바이벌 재대결을 요청했습니다!',
    'rematch.survivalDesc': '수락하고 즉시 1대1 대결로 복귀하세요!',
    'rematch.wagerChallenge': '님이 베팅 재대결을 신청했습니다!', 'stats.goals': '골', 'stats.shots': '슈팅',
    'status.live': 'LIVE', 'status.offline': '오프라인', 'status.winner': '승자', 'status.eliminated': '탈락',
    'status.survived': '생존', 'status.left': '퇴장', 'status.disconnected': '연결 끊김',
    'store.title': '장비 상점', 'store.subtitle': '3D 축구공 스킨 & 경기장 잔디 패턴',
    'store.balls': '축구공', 'store.pitches': '잔디', 'store.ballStore': '공 상점',
    'store.ballStoreDesc': '3D 텍스처 & 프로 모델', 'store.pitchStore': '스타디움 상점',
    'store.pitchStoreDesc': '스타디움 잔디 깎기 패턴', 'store.selectCategory': '카테고리 선택',
    'store.unlockedAndEquipped': '잠금 해제 및 장착됨', 'store.owned': '보유 중', 'store.buyFor': '구매 가격:',
    'store.notEnoughCoins': '코인이 부족합니다!', 'store.needMore': '필요한 코인', 'store.more': '개 더 필요',
    'profile.title': '플레이어 프로필', 'profile.cloudStorageNotice': 'CRAZYGAMES 클라우드 및 로컬 자동 저장',
    'replays.subtitle': '저장된 멋진 골 명장면을 감상하고 관리하세요', 'replays.savedReplays': '저장된 다시보기',
    'replays.savedHighlights': '저장된 하이라이트', 'replays.clips': '영상', 'replays.savedClips': '저장된 클립',
    'replays.noSavedReplays': '저장된 다시보기가 없습니다', 'replays.noHighlightsTitle': '하이라이트 없음',
    'replays.noHighlightsDesc': '경기 중 골을 넣고 리플레이 화면에서 저장을 누르세요!',
    'replays.playMatchNow': '지금 경기 시작하기', 'replays.emptyInstructions': '멋진 골을 넣은 후 리플레이 우측 상단의 저장을 터치하세요!',
    'replays.savedHighlight': '저장된 하이라이트', 'replays.savedDate': '날짜', 'replays.shotDistance': '슈팅 거리',
    'replays.longestStrike': '최장거리 골', 'replays.goalHighlights': '골 하이라이트', 'replays.watchReplay': '다시보기 재생',
    'replays.exitReplay': '다시보기 닫기', 'replays.deleteReplay': '다시보기 삭제',
    'replays.confirmDelete': '이 골 영상을 삭제하시겠습니까?', 'replays.deleteAllConfirm': '모든 다시보기를 삭제하시겠습니까?',
    'replays.deleteAllDesc': '저장된 모든 리플레이를 정말로 삭제하시겠습니까?', 'ads.videoReward': '동영상 보상',
    'ads.coinsReward': '코인 보상', 'ads.watchToEarn': '광고 시청 시 +50 코인 지급',
    'ads.instantBoost': '즉시 코인 부스트', 'ads.integrationFinalizing': '광고 시스템 준비 중입니다.',
    'ads.unlockAllItems': '50종의 공과 50종의 경기장 잔디를 모두 잠금 해제하세요!', 'ads.loading': '광고 불러오는 중...',
    'lang.title': '언어 설정', 'lang.subtitle': '선호하는 언어를 선택하세요 (16개 언어 지원)',
    'lang.autoDetect': '자동 감지된 언어', 'lang.currentlyActive': '현재 적용 중',
    'lang.sdkSyncTitle': 'CrazyGames 동기화', 'lang.sdkSyncDesc': '게임 언어가 CrazyGames 포털 계정 언어와 자동으로 동기화됩니다',
    'lang.searchPlaceholder': '언어 또는 국가 검색...', 'lang.tabAll': '전체 (16)', 'lang.tabPopular': '인기',
    'lang.tabEurope': '유럽', 'lang.tabAmericas': '아메리카', 'lang.tabAsiaMe': '아시아 및 중동',
    'lang.noMatches': '일치하는 언어가 없습니다', 'lang.noMatchesDesc': '다른 언어나 국가명으로 검색해 보세요',
    'lang.resetFilters': '필터 초기화'
}

print("JA and KO loaded.")
