# -*- coding: utf-8 -*-
# Indonesian (id) & Vietnamese (vi)

id = {
    'nav.store': 'Toko', 'nav.profile': 'Profil', 'nav.replays': 'Siaran Ulang', 'nav.coins': 'Koin',
    'nav.language': 'Bahasa', 'nav.bestStreak': 'Kemenangan Beruntun Terbaik', 'nav.online': 'Online', 'nav.connecting': 'Menghubungkan...',
    'game.title': 'FREE KICK LEGENDS', 'menu.quickPlay': 'MAIN CEPAT', 'menu.quickPlaySub': 'PERTANDINGAN ONLINE & OFFLINE',
    'menu.survivalMode': 'MODE BERTAHAN', 'survival.threeLives': '3 NYAWA', 'survival.endlessStreak': 'Rekor Tanpa Batas',
    'survival.best': 'Terbaik', 'survival.streak': 'REKOR', 'survival.onlineAvailable': 'Tersedia Duel 1v1 Online',
    'menu.wagerArena': 'ARENA TARUHAN', 'wager.betCoinsPot': 'Pasang Koin • Pemenang Ambil Semua',
    'wager.onlineDuel': 'Duel Taruhan Koin 1v1 Online', 'wager.duel': 'DUEL', 'wager.arena': 'Arena', 'wager.bet': 'Taruhan',
    'wager.winnerTakes': 'Pemenang Mengambil', 'wager.prizePot': 'Total Hadiah', 'menu.worldCup': 'PIALA DUNIA FIFA',
    'menu.tournamentFormat': 'Format Turnamen', 'menu.practice': 'LATIHAN', 'menu.practiceSub': 'Latihan Tendangan Bebas',
    'menu.shop': 'TOKO', 'menu.onlineMultiplayer': 'Tersedia Multiplayer Online',
    'profile.savedReplaysStats': 'SIARAN ULANG & STATISTIK', 'replays.title': 'Siaran Ulang Tersimpan',
    'common.coins': 'KOIN', 'common.coinsUpper': 'KOIN', 'common.online': 'ONLINE', 'common.offline': 'OFFLINE',
    'common.back': 'KEMBALI', 'common.backToMenu': 'Kembali ke Menu', 'common.active': 'AKTIF', 'common.done': 'SELESAI',
    'common.close': 'TUTUP', 'common.gotIt': 'MENGERTI', 'common.cancel': 'Batal', 'common.continue': 'LANJUTKAN',
    'common.exit': 'KELUAR', 'common.quit': 'KELUAR', 'common.play': 'MAIN', 'common.saved': 'TERSIMPAN', 'common.goal': 'GOL',
    'common.goals': 'gol', 'common.pts': 'POIN', 'common.you': 'Anda', 'common.opponent': 'Lawan',
    'common.watchAdCoins': 'Tonton video iklan untuk +50 koin gratis', 'currency.coins': 'KOIN',
    'btn.play': 'Main Sekarang', 'btn.select': 'Pilih', 'btn.confirm': 'Konfirmasi', 'btn.cancel': 'Batal',
    'btn.close': 'Tutup', 'btn.back': 'Kembali', 'btn.continue': 'Lanjutkan', 'btn.nextMatch': 'Pertandingan Berikutnya',
    'btn.returnMenu': 'Menu Utama', 'btn.equip': 'Gunakan', 'btn.equipped': 'Digunakan', 'btn.unlock': 'Buka Kunci',
    'btn.locked': 'Terkunci', 'btn.saveReplay': 'Simpan Siaran Ulang', 'btn.save': 'SIMPAN', 'btn.saved': 'TERSIMPAN',
    'btn.skip': 'LEWATI', 'btn.playAgain': 'Main Lagi', 'btn.watchAd': 'Tonton Video (+50 Koin)', 'btn.freeCoins': 'Koin Gratis',
    'hud.aim': 'Bidikan', 'hud.power': 'Kekuatan', 'hud.curve': 'Lengkungan', 'hud.kick': 'Tendang',
    'hud.stepAim': 'SESUAIKAN SUDUT', 'hud.stepPower': 'ATUR KEKUATAN', 'hud.stepCurve': 'BERI EFEK LENGKUNGAN',
    'hud.stepKick': 'LEPASKAN TENDANGAN', 'hud.shoot': 'TEMBAK!', 'hud.tapToLock': 'KETUK UNTUK MENGUNCI',
    'hud.tapToKick': 'KETUK UNTUK MENENDANG', 'hud.goal': 'GOL!', 'hud.saved': 'DISELAMATKAN!', 'hud.missed': 'MELESET!',
    'hud.wallBlocked': 'DIBLOK PAGAR BETIS!', 'hud.postHit': 'KENA TIANG!', 'hud.suddenDeath': 'SUDDEN DEATH',
    'hud.goldenGoal': 'GOL EMAS', 'hud.penaltyShootout': 'ADU PENALTI', 'hud.turn': 'Giliran',
    'hud.yourTurn': 'GILIRAN ANDA', 'hud.oppTurn': 'GILIRAN LAWAN', 'hud.aiThinking': 'BOT BERPIKIR...',
    'hud.aiAiming': 'BOT MEMBIDIK...', 'hud.aiStriking': 'BOT MENENDANG...', 'hud.timer': 'Waktu',
    'hud.matchOver': 'PERTANDINGAN SELESAI', 'hud.rematch': 'Tanding Ulang', 'hud.exitMatch': 'Keluar Pertandingan',
    'hud.resume': 'Lanjutkan', 'hud.pause': 'Jeda', 'hud.yourTurnPenalty': 'GILIRAN ANDA MENENDANG PENALTI',
    'hud.oppPenalty': 'LAWAN MENENDANG PENALTI...', 'hud.aiPenalty': 'BOT MENENDANG PENALTI...',
    'hud.playIn': 'KAMERA:', 'hud.ballTracking': 'IKUTI BOLA', 'hud.behindGoal': 'BELAKANG GAWANG',
    'hud.meter': 'METERAN', 'hud.aiGoalkeeper': 'KIPER BOT', 'hud.aiStriker': 'PENYERANG BOT',
    'hud.defenseSim': 'Simulasi Bertahan', 'hud.precisionFK': 'Tendangan Bebas Akurat', 'hud.aiming': 'MEMBIDIK',
    'hud.holdToCharge': 'TAHAN UNTUK MENGISI TENAGA', 'hud.releaseToStrikeInstruction': 'TAHAN SPASI / LAYAR • LEPASKAN UNTUK MENENDANG',
    'hud.weak': 'LEMAH', 'hud.sweetSpot': 'SEMPURNA', 'hud.max': 'MAKS', 'hud.chargingPower': 'MENGISI TENAGA...',
    'hud.replay': 'SIARAN ULANG', 'game.goal': 'GOL!', 'game.saved': 'DITEPAKS',
    'quickPlay.selectMode': 'Pilih mode pertandingan:', 'quickPlay.ranked': 'Peringkat', 'quickPlay.vsAi': 'Vs Bot / Lokal',
    'country.selectTeams': 'PILIH TIM', 'country.nationalTeams': 'Tim Nasional', 'country.teamsAvailable': 'Tim Tersedia',
    'country.tapToSelect': 'Ketuk untuk memilih', 'country.myTeam': 'TIM SAYA', 'country.opponent': 'LAWAN',
    'country.continueToMatch': 'LANJUT KE PERTANDINGAN', 'search.countries': 'Cari negara...', 'teamSelect.teams': 'Tim',
    'teamSelect.searchPlaceholder': 'Cari tim nasional...', 'teamSelect.att': 'SER', 'teamSelect.def': 'BER',
    'team.selectNew': 'PILIH TIM BARU', 'team.selectNewDesc': 'Pilih dari 120 tim nasional di seluruh dunia',
    'online.matchTitle': 'PERTANDINGAN ONLINE', 'online.matchSubtitle': 'Terhubung dan pilih negara secara langsung:',
    'online.createRoom': 'Buat Kamar Pribadi', 'online.joinRoom': 'Gabung Lewat Kode', 'online.joinRoomTitle': 'GABUNG KE KAMAR',
    'online.roomCode': 'Kode Kamar', 'online.copyCode': 'Salin Kode', 'online.codeCopied': 'Tersalin!',
    'online.shareCode': 'Bagikan kode 4 digit ini ke teman Anda:', 'online.enterCode': 'Masukkan kode 4 digit:',
    'online.findMatch': 'Cari Lawan Cepat', 'online.searchingMatch': 'Mencari lawan...', 'online.stillSearching': 'Mencari pemain aktif...',
    'online.retrySearch': 'Coba Lagi', 'online.cancelSearch': 'Batalkan Pencarian', 'online.cancelRoom': 'Batalkan Kamar',
    'online.leaveRoom': 'Tinggalkan Kamar', 'online.inviteLink': 'Salin Tautan Undangan', 'online.linkCopied': 'Tautan Tersalin!',
    'online.lookingOpponent': 'Mencari lawan di seluruh dunia...', 'online.pairingAuto': 'Menghubungkan dengan pemain...', 'online.ready': 'SIAP',
    'online.bothSelected': 'Keduanya siap! Pertandingan dimulai...', 'online.selectTeamBelow': 'Pilih tim Anda di bawah:',
    'online.lockedIn': 'DIKUNCI', 'online.selecting': 'Memilih...', 'online.choosing': 'Sedang memilih tim...',
    'online.opponentLeft': 'Lawan telah meninggalkan kamar', 'online.opponentLeftSub': 'Kembali ke menu sebentar lagi...',
    'online.roomCreated': 'KAMAR DIBUAT', 'online.room': 'Kamar', 'online.host': 'Tuan Rumah', 'online.guest': 'Tamu',
    'online.firstTurn': 'Anda menendang duluan', 'online.secondTurn': 'Lawan menendang duluan',
    'online.matchStartingIn': 'Pertandingan dimulai dalam', 'online.kickoff': 'KICK OFF!',
    'online.leaveMatchTitle': 'TINGGALKAN PERTANDINGAN?', 'online.leaveMatchSub': 'Keluar akan memberikan kemenangan otomatis kepada lawan.',
    'online.leaveMatch': 'TINGGALKAN PERTANDINGAN', 'online.leave': 'TINGGALKAN', 'online.returnToMenu': 'Kembali ke Menu',
    'online.returningToMenu': 'Kembali ke Menu...', 'online.sessionDisconnected': 'Sesi Terputus',
    'online.yourCountry': 'TIM NASIONAL ANDA', 'online.oppCountry': 'TIM NASIONAL LAWAN',
    'online.waitingOpponent': 'Menunggu pilihan lawan...', 'online.waitingOpponentCode': 'Menunggu teman memasukkan kode...',
    'online.connectSub': 'Server multipemain 1v1 langsung di seluruh dunia', 'modal.matchmaking': 'Mencari Lawan...',
    'modal.matchmakingDesc': 'Mencari pemain di server global', 'modal.searchingTime': 'Waktu Pencarian',
    'modal.opponentFound': 'LAWAN DITEMUKAN!', 'modal.connectingBot': 'Menghubungkan bot dalam 30 detik...',
    'modal.quitMatchSub': 'Kemajuan pertandingan saat ini tidak akan disimpan.', 'modal.forfeitMatchTitle': 'MENYERAH?',
    'modal.forfeitMatchSub': 'Keluar sekarang dihitung sebagai kekalahan otomatis.', 'modal.forfeit': 'MENYERAH',
    'match.opponentLeftTitle': 'LAWAN KELUAR DARI PERTANDINGAN', 'match.opponentLeftDesc': 'Koneksi lawan Anda terputus.',
    'match.playAgainUnavailable': 'Tanding ulang tidak tersedia karena lawan telah keluar.',
    'match.waitingOpponent': 'Menunggu jawaban lawan...', 'match.changeTeams': 'GANTI TIM',
    'tournament.selectFormat': 'Pilih format turnamen:', 'tournament.globalCup': 'Piala Global', 'tournament.customCup': 'Piala Khusus',
    'tournament.inDevelopment': 'DALAM PENGEMBANGAN', 'tournament.onlineWorldCup': 'PIALA DUNIA ONLINE',
    'tournament.multiplayerWorldCup': 'Piala Dunia Multipemain & Bagan Sistem Gugur', 'tournament.knockoutBrackets': 'Bagan Gugur 16 Tim',
    'tournament.knockoutBracketsSub': 'Turnamen eliminasi langsung waktu nyata', 'tournament.globalLeaderboards': 'Papan Peringkat Musiman Global',
    'tournament.globalLeaderboardsSub': 'Dapatkan poin peringkat dan trofi juara', 'tournament.exclusiveUnlockables': 'Jersey Juara & Bola Eksklusif',
    'tournament.exclusiveUnlockablesSub': 'Hadiah khusus untuk para juara', 'tournament.playOfflineNow': 'MAIN PIALA DUNIA OFFLINE',
    'tournament.selectYourTeam': 'PILIH TIM ANDA', 'tournament.worldCupQualifiedSub': 'Piala Dunia FIFA • 40 Tim Nasional Lolos (Grup A – J)',
    'tournament.searchCountry': 'Cari negara atau grup...', 'tournament.qualifiedNations': 'Negara yang Lolos',
    'tournament.tapToSelect': 'Ketuk untuk Memilih', 'tournament.selected': 'TERPILIH', 'tournament.ovr': 'OVR',
    'tournament.randomGroupDraw': 'Pengundian grup acak saat mulai', 'tournament.tapAnyCountryPrompt': 'KETUK NEGARA UNTUK MEMILIH TIM ANDA',
    'tournament.enterWorldCup': 'MASUK PIALA DUNIA (GRUP A - J)', 'tournament.backToMenu': 'Menu Utama',
    'tournament.forfeitMatch': 'MENYERAH DARI PERTANDINGAN', 'tournament.continue': 'LANJUT KE BABAK GUGUR',
    'tournament.championTitle': '★ JUARA DUNIA ★', 'tournament.worldChampions': 'JUARA DUNIA',
    'tournament.winnerLiftsCup': 'Anda berhasil mengangkat trofi Piala Dunia!', 'tournament.freeKickCup': 'Turnamen Tendangan Bebas Dunia',
    'tournament.roundOf16': 'Babak 16 Besar', 'tournament.quarterFinals': 'Perempat Final', 'tournament.semiFinal1': 'Semifinal 1',
    'tournament.semiFinal2': 'Semifinal 2', 'tournament.worldFinal': 'Final Piala Dunia', 'tournament.awaitingFinal': 'Menunggu Finalis',
    'tournament.fixture': 'Jadwal', 'tournament.ft': 'SELESAI', 'tournament.tbd': 'AKAN DITENTUKAN', 'tournament.cancelTournament': 'Batalkan Turnamen',
    'practice.selectDrill': 'Pilih latihan:', 'practice.freeKick': 'TENDANGAN BEBAS',
    'practice.freeKickSub': 'Main langsung • Pagar betis dan sudut sempit', 'practice.instant': 'Instan',
    'practice.penalty': 'PENALTI', 'practice.penaltySub': '1v1 lawan kiper • Tanpa batas waktu', 'practice.random': 'Acak',
    'practice.exitTitle': 'KELUAR DARI LATIHAN?', 'practice.exitSub': 'Anda dapat kembali ke menu utama kapan saja.',
    'practice.exitButton': 'KELUAR DARI LATIHAN', 'survival.title': 'Arena Bertahan',
    'survival.subtitle': '3 Nyawa • Rekor Tanpa Batas • Duel', 'survival.arenaTitle': 'ARENA BERTAHAN',
    'survival.onlineSurvivalTitle': 'SURVIVAL 1V1 ONLINE',
    'survival.onlineSurvivalSubtitle': '3 Nyawa • Duel Langsung 1v1 • Tantangan Rekor Gol Tanpa Batas',
    'survival.selectGameMode': 'Pilih mode permainan:', 'survival.offlineSurvivalBtn': 'SURVIVAL OFFLINE',
    'survival.onlineDuelBtn': 'DUEL 1V1 ONLINE', 'survival.rulesBtn': 'Aturan',
    'survival.rulesTitle': 'ATURAN MODE BERTAHAN', 'survival.rulesSubtitle': 'Patuhi 2 aturan ini untuk mencetak rekor tertinggi:',
    'survival.rule1Title': 'Sistem 3 Nyawa',
    'survival.rule1Desc': 'Setiap pemain mulai dengan 3 hati. Tendangan meleset atau ditepis mengurangi 1 nyawa. Yang pertama kehabisan nyawa kalah!',
    'survival.rule2Title': 'Bergantian & Pengatur Waktu 100 Detik',
    'survival.rule2Desc': 'Tendangan bebas bergantian dengan hitungan mundur 100 detik. Cetak gol untuk memperpanjang rekor kemenangan!',
    'survival.backToRules': 'Kembali ke Aturan', 'survival.howItWorks': 'Cara bermain', 'survival.guideBadge': 'PANDUAN BERTAHAN',
    'survival.livesRemaining': 'Sisa Nyawa', 'survival.bestRecord': 'Rekor Sepanjang Masa', 'survival.bestStreak': 'REKOR TERBAIK',
    'survival.startRun': 'Mulai Tantangan', 'survival.personalRecord': 'Rekor Pribadi', 'survival.goalStreak': 'REKOR GOL',
    'survival.goalsStreak': 'REKOR GOL', 'survival.kicks': 'Tendangan', 'survival.duel': 'DUEL SURVIVAL 1V1',
    'survival.duelSub': 'Pertarungan Sistem Gugur Online', 'survival.runEnded': 'TANTANGAN BERAKHIR!',
    'survival.challengeComplete': 'Tantangan Bertahan Selesai', 'survival.finalGoalsStreak': 'Total Rekor Gol',
    'survival.challengeMode': 'Mode Tantangan', 'survival.reviveExtraLife': 'BANGKITKAN (+1 NYAWA EKSTRA)',
    'survival.endSurvivalTitle': 'AKHIRI MODE BERTAHAN?', 'survival.endSurvival': 'AKHIRI', 'survival.endRun': 'SELESAIKAN TANTANGAN',
    'survival.concludeSub': 'Pertandingan akan segera dihentikan.', 'survival.currentStreak': 'Rekor saat ini:',
    'wager.title': 'Arena Taruhan', 'wager.subtitle': 'Pilih nominal taruhan • Pemenang mengambil semua koin!',
    'wager.rookie': 'Arena Pemula', 'wager.pro': 'Arena Profesional', 'wager.champion': 'Arena Juara', 'wager.legend': 'Arena Legenda',
    'wager.entryFee': 'Biaya Masuk', 'wager.entry': 'MASUK', 'wager.prizePot': 'Total Hadiah', 'wager.winPot': 'HADIAH PEMENANG',
    'wager.highRoller': 'Duel Taruhan Tinggi', 'wager.bottomBanner': 'Jelajahi arena • Taruhan tinggi, hadiah berlipat ganda!',
    'wager.tapToSelect': 'Ketuk untuk memilih', 'wager.playWithCoins': 'Main dengan koin', 'wager.needMoreCoins': 'Butuh lebih banyak koin',
    'wager.forfeitWager': 'MENYERAH DARI TARUHAN', 'wager.surrenderTitle': 'MENYERAH DARI TARUHAN?',
    'wager.surrenderSub': 'Menyerah akan mengakibatkan kehilangan koin yang dipasang:', 'wager.surrender': 'MENYERAH', 'wager.victory': 'KEMENANGAN TARUHAN!',
    'wager.coinDuelResults': 'Hasil Duel Koin', 'wager.drawRefunded': 'SERI • BIAYA DIKEMBALIKAN',
    'wager.arenaPot': 'Total Pot Arena', 'wager.netResult': 'Hasil Bersih',
    'wager.opponentLeft': 'Lawan telah meninggalkan arena', 'wager.rematch': 'TANDING ULANG TARUHAN',
    'targetSmash.title': 'TEMBAK TARGET', 'targetSmash.arcadeBadge': 'MODE ARKADE BARU',
    'targetSmash.trickshotSubtitle': 'Target Sasaran & Tendangan Lengkung', 'targetSmash.selectStage': 'Level (1 - 10)',
    'targetSmash.unlocked': 'Terbuka', 'targetSmash.stage': 'Level', 'targetSmash.objective': 'Target',
    'targetSmash.highScore': 'Rekor', 'targetSmash.pts': 'POIN', 'targetSmash.distance': 'Jarak',
    'targetSmash.defendersWall': 'Pagar Betis', 'targetSmash.players': 'Pemain', 'targetSmash.targetScore': 'Skor Target',
    'targetSmash.targetRequired': 'Poin Diperlukan', 'targetSmash.playStage': 'MAIN LEVEL', 'targetSmash.stageLocked': 'LEVEL TERKUNCI',
    'targetSmash.stageCleared': 'LEVEL BERHASIL!', 'targetSmash.stageFailed': 'LEVEL GAGAL', 'targetSmash.finalScore': 'Skor Akhir',
    'targetSmash.coinsReward': 'Hadiah Koin', 'targetSmash.nextStage': 'LEVEL BERIKUTNYA', 'targetSmash.retryStage': 'COBA LAGI',
    'targetSmash.exitToSelect': 'KEMBALI KE LEVEL', 'divisions.title': 'Liga Divisi', 'divisions.titleUpper': 'LIGA DIVISI',
    'divisions.rank': 'Peringkat Divisi', 'divisions.titleTarget': 'Target Gelar', 'divisions.titleClaimed': 'Gelar Diraih!',
    'divisions.ptsForTrophy': 'Poin Menuju Trofi', 'divisions.seasonFinished': 'Musim Selesai',
    'divisions.promotionAchieved': 'Promosi Tercapai!', 'divisions.thisSeason': 'Musim Ini',
    'divisions.matchesLeft': 'Sisa Pertandingan', 'divisions.ptsNeeded': 'Poin Dibutuhkan', 'divisions.win': 'Menang',
    'divisions.draw': 'Seri', 'divisions.loss': 'Kalah', 'divisions.pt': 'POIN', 'divisions.pts': 'POIN',
    'divisions.allTime': 'Rekor Keseluruhan', 'divisions.matchesHistory': 'Riwayat Pertandingan', 'divisions.match': 'Laga',
    'divisions.noMatchesYet': 'Belum ada pertandingan di musim ini', 'divisions.noMatchesSub': 'Mulai musim Anda di bawah ini!',
    'divisions.nextMatchChooseOpponent': 'Laga Berikutnya • Pilih Lawan', 'divisions.whoDoYouWantToPlay': 'Pilih lawan Anda selanjutnya:',
    'divisions.teamsAvailable': 'Tim Tersedia', 'divisions.searchNationalTeam': 'Cari tim nasional...',
    'divisions.playMatchVs': 'MAIN MELAWAN', 'divisions.opponent': 'Lawan', 'divisions.opponentUpper': 'LAWAN',
    'divisions.opponentConnected': 'Lawan Terhubung', 'divisions.change': 'Ubah', 'divisions.chooseOpponent': 'Pilih Lawan',
    'divisions.divShort': 'DIV', 'divisions.of': 'dari', 'divisions.continueTo': 'Lanjut ke', 'divisions.next': 'Berikutnya',
    'divisions.findingOpponent': 'Mencari Lawan Divisi...', 'divisions.matchingWithOnline': 'Mencari pemain di divisi Anda',
    'divisions.searchingActivePlayers': 'Mencari di server divisi...', 'divisions.matchStartingIn': 'Pertandingan dimulai dalam',
    'divisions.cancelMatchmaking': 'Batal', 'divisions.cancelSearch': 'Batalkan Pencarian', 'divisions.wdl': 'M-S-K',
    'division.return': 'Kembali ke Divisi', 'division.reward': 'Hadiah Divisi', 'result.victory': 'MENANG!',
    'result.defeat': 'KALAH', 'result.draw': 'SERI', 'result.champion': 'JUARA DUNIA!', 'result.prizeWon': 'Hadiah Diraih',
    'result.streak': 'Rekor Saat Ini', 'result.newRecord': 'REKOR BARU!', 'result.coinsEarned': 'Koin Diperoleh',
    'result.finalScore': 'Skor Akhir', 'result.totalScore': 'Total Skor', 'result.wonOnPenalties': 'MENANG ADU PENALTI',
    'result.lostOnPenalties': 'KALAH ADU PENALTI', 'result.survivalVictory': 'KEMENANGAN SURVIVAL!',
    'result.survivalDefeat': 'TERELIMINASI DI SURVIVAL', 'result.wagerResults': 'Hasil Taruhan',
    'rematch.invitationTitle': 'Undangan Tanding Ulang', 'rematch.invitationDesc': 'Lawan ingin tanding ulang!',
    'rematch.accept': 'Terima Tanding Ulang', 'rematch.decline': 'Tolak', 'rematch.starting': 'Memulai Tanding Ulang...',
    'rematch.survivalRequested': 'Lawan meminta Tanding Ulang Survival!',
    'rematch.survivalDesc': 'Terima untuk langsung kembali ke duel 1v1!',
    'rematch.wagerChallenge': 'menantang Anda untuk Tanding Ulang Taruhan!', 'stats.goals': 'Gol', 'stats.shots': 'Tendangan',
    'status.live': 'LANGSUNG', 'status.offline': 'OFFLINE', 'status.winner': 'PEMENANG', 'status.eliminated': 'TERELIMINASI',
    'status.survived': 'BERTAHAN', 'status.left': 'KELUAR', 'status.disconnected': 'TERPUTUS',
    'store.title': 'Toko Perlengkapan', 'store.subtitle': 'TEKSTUR BOLA 3D & POLA RUMPUT STADION',
    'store.balls': 'Bola', 'store.pitches': 'Lapangan', 'store.ballStore': 'TOKO BOLA',
    'store.ballStoreDesc': 'Tekstur 3D & Model Pro', 'store.pitchStore': 'TOKO STADION',
    'store.pitchStoreDesc': 'Pola Potongan Rumput Lapangan', 'store.selectCategory': 'PILIH KATEGORI',
    'store.unlockedAndEquipped': 'DIBUKA & DIGUNAKAN', 'store.owned': 'Dimiliki', 'store.buyFor': 'Beli seharga',
    'store.notEnoughCoins': 'KOIN TIDAK CUKUP!', 'store.needMore': 'KURANG', 'store.more': 'LAGI',
    'profile.title': 'Profil Pemain', 'profile.cloudStorageNotice': 'TERSIMPAN DI CLOUD CRAZYGAMES & LOKAL',
    'replays.subtitle': 'Lihat dan kelola rekaman gol terbaik Anda', 'replays.savedReplays': 'SIARAN ULANG TERSIMPAN',
    'replays.savedHighlights': 'CUPLIKAN TERSIMPAN', 'replays.clips': 'Klip', 'replays.savedClips': 'Klip Tersimpan',
    'replays.noSavedReplays': 'BELUM ADA SIARAN ULANG', 'replays.noHighlightsTitle': 'BELUM ADA CUPLIKAN',
    'replays.noHighlightsDesc': 'Cetak gol dalam laga dan ketuk SIMPAN saat tayangan ulang!',
    'replays.playMatchNow': 'MAIN PERTANDINGAN SEKARANG', 'replays.emptyInstructions': 'Cetak gol dan ketuk SIMPAN di pojok kanan atas tayangan ulang!',
    'replays.savedHighlight': 'CUPLIKAN TERSIMPAN', 'replays.savedDate': 'TANGGAL', 'replays.shotDistance': 'JARAK TENDANGAN',
    'replays.longestStrike': 'Tendangan Terjauh', 'replays.goalHighlights': 'Cuplikan Gol', 'replays.watchReplay': 'TONTON SIARAN ULANG',
    'replays.exitReplay': 'KELUAR DARI SIARAN ULANG', 'replays.deleteReplay': 'Hapus Siaran Ulang',
    'replays.confirmDelete': 'Hapus cuplikan gol tersimpan ini?', 'replays.deleteAllConfirm': 'HAPUS SEMUA SIARAN ULANG?',
    'replays.deleteAllDesc': 'Yakin ingin menghapus seluruh koleksi siaran ulang?', 'ads.videoReward': 'HADIAH VIDEO',
    'ads.coinsReward': 'HADIAH KOIN', 'ads.watchToEarn': 'Tonton video iklan untuk mendapatkan +50 koin',
    'ads.instantBoost': 'Tambahan Koin Instan', 'ads.integrationFinalizing': 'Integrasi iklan sedang difinalisasi.',
    'ads.unlockAllItems': 'Buka semua 50 bola dan 50 desain pola rumput!', 'ads.loading': 'MEMUAT IKLAN...',
    'lang.title': 'Pengaturan Bahasa', 'lang.subtitle': 'Pilih bahasa pilihan Anda (Tersedia 16 bahasa dunia)',
    'lang.autoDetect': 'Bahasa Terdeteksi Otomatis', 'lang.currentlyActive': 'AKTIF SAAT INI',
    'lang.sdkSyncTitle': 'Sinkronisasi CrazyGames', 'lang.sdkSyncDesc': 'Bahasa permainan otomatis menyesuaikan dengan akun portal Anda',
    'lang.searchPlaceholder': 'Cari bahasa atau negara...', 'lang.tabAll': 'Semua (16)', 'lang.tabPopular': 'Populer',
    'lang.tabEurope': 'Eropa', 'lang.tabAmericas': 'Amerika', 'lang.tabAsiaMe': 'Asia & Timteng',
    'lang.noMatches': 'Bahasa tidak ditemukan', 'lang.noMatchesDesc': 'Coba ketik nama bahasa atau negara lain',
    'lang.resetFilters': 'Atur Ulang Filter'
}

vi = {
    'nav.store': 'Cửa Hàng', 'nav.profile': 'Hồ Sơ', 'nav.replays': 'Xem Lại', 'nav.coins': 'Xu',
    'nav.language': 'Ngôn Ngữ', 'nav.bestStreak': 'Chuỗi Thắng Cao Nhất', 'nav.online': 'Trực Tuyến', 'nav.connecting': 'Đang kết nối...',
    'game.title': 'FREE KICK LEGENDS', 'menu.quickPlay': 'ĐẤU NHANH', 'menu.quickPlaySub': 'TRẬN ĐẤU ONLINE & OFFLINE',
    'menu.survivalMode': 'CHẾ ĐỘ SINH TỒN', 'survival.threeLives': '3 MẠNG', 'survival.endlessStreak': 'Chuỗi Bất Tận',
    'survival.best': 'Kỷ Lục', 'survival.streak': 'CHUỖI', 'survival.onlineAvailable': 'Đã có Đấu 1v1 Online',
    'menu.wagerArena': 'ĐẤU TRƯỜNG CƯỢC', 'wager.betCoinsPot': 'Đặt Cược Xu • Thắng Ăn Cả',
    'wager.onlineDuel': 'Đấu Cược Xu 1v1 Trực Tuyến', 'wager.duel': 'ĐỐI ĐẦU', 'wager.arena': 'Đấu Trường', 'wager.bet': 'Cược',
    'wager.winnerTakes': 'Người Thắng Nhận', 'wager.prizePot': 'Tổng Thưởng', 'menu.worldCup': 'CÚP THẾ GIỚI FIFA',
    'menu.tournamentFormat': 'Thể Thức Giải Đấu', 'menu.practice': 'LUYỆN TẬP', 'menu.practiceSub': 'Tập Sút Phạt Trực Tiếp',
    'menu.shop': 'CỬA HÀNG', 'menu.onlineMultiplayer': 'Hỗ Trợ Chơi Nhiều Người Trực Tuyến',
    'profile.savedReplaysStats': 'XEM LẠI & THỐNG KÊ', 'replays.title': 'Pha Bóng Đã Lưu',
    'common.coins': 'XU', 'common.coinsUpper': 'XU', 'common.online': 'ONLINE', 'common.offline': 'OFFLINE',
    'common.back': 'QUAY LẠI', 'common.backToMenu': 'Về Menu Chính', 'common.active': 'ĐANG DÙNG', 'common.done': 'HOÀN THÀNH',
    'common.close': 'ĐÓNG', 'common.gotIt': 'ĐÃ HIỂU', 'common.cancel': 'Hủy', 'common.continue': 'TIẾP TỤC',
    'common.exit': 'THOÁT', 'common.quit': 'THOÁT', 'common.play': 'CHƠI', 'common.saved': 'ĐÃ LƯU', 'common.goal': 'VÀO',
    'common.goals': 'bàn', 'common.pts': 'ĐIỂM', 'common.you': 'Bạn', 'common.opponent': 'Đối Thủ',
    'common.watchAdCoins': 'Xem quảng cáo nhận +50 xu miễn phí', 'currency.coins': 'XU',
    'btn.play': 'Chơi Ngay', 'btn.select': 'Chọn', 'btn.confirm': 'Xác Nhận', 'btn.cancel': 'Hủy',
    'btn.close': 'Đóng', 'btn.back': 'Quay Lại', 'btn.continue': 'Tiếp Tục', 'btn.nextMatch': 'Trận Tiếp Theo',
    'btn.returnMenu': 'Menu Chính', 'btn.equip': 'Trang Bị', 'btn.equipped': 'Đã Trang Bị', 'btn.unlock': 'Mở Khóa',
    'btn.locked': 'Đã Khóa', 'btn.saveReplay': 'Lưu Pha Bóng', 'btn.save': 'LƯU', 'btn.saved': 'ĐÃ LƯU',
    'btn.skip': 'BỎ QUA', 'btn.playAgain': 'Chơi Lại', 'btn.watchAd': 'Xem Video (+50 Xu)', 'btn.freeCoins': 'Xu Miễn Phí',
    'hud.aim': 'Ngắm', 'hud.power': 'Lực', 'hud.curve': 'Xoáy', 'hud.kick': 'Sút',
    'hud.stepAim': 'CHỈNH GÓC SÚT', 'hud.stepPower': 'KHÓA LỰC SÚT', 'hud.stepCurve': 'TẠO XOÁY BÓNG',
    'hud.stepKick': 'THỰC HIỆN CÚ SÚT', 'hud.shoot': 'SÚT!', 'hud.tapToLock': 'CHẠM ĐỂ KHÓA',
    'hud.tapToKick': 'CHẠM ĐỂ SÚT', 'hud.goal': 'VÀO!', 'hud.saved': 'CẢN PHÁ!', 'hud.missed': 'TRƯỢT!',
    'hud.wallBlocked': 'HÀNG RÀO CHẶN BÓNG!', 'hud.postHit': 'TRÚNG CỘT DỌC!', 'hud.suddenDeath': 'BÀN THẮNG VÀNG',
    'hud.goldenGoal': 'BÀN THẮNG VÀNG', 'hud.penaltyShootout': 'SÚT LUÂN LƯU 11M', 'hud.turn': 'Lượt',
    'hud.yourTurn': 'LƯỢT CỦA BẠN', 'hud.oppTurn': 'LƯỢT ĐỐI THỦ', 'hud.aiThinking': 'BOT ĐANG TÍNH TOÁN...',
    'hud.aiAiming': 'BOT ĐANG NGẮM...', 'hud.aiStriking': 'BOT ĐANG SÚT...', 'hud.timer': 'Thời Gian',
    'hud.matchOver': 'HẾT GIỜ', 'hud.rematch': 'Tái Đấu', 'hud.exitMatch': 'Rời Trận',
    'hud.resume': 'Tiếp Tục', 'hud.pause': 'Tạm Dừng', 'hud.yourTurnPenalty': 'LƯỢT BẠN SÚT PHẠT ĐỀN',
    'hud.oppPenalty': 'ĐỐI THỦ ĐANG SÚT PHẠT ĐỀN...', 'hud.aiPenalty': 'BOT ĐANG SÚT PHẠT ĐỀN...',
    'hud.playIn': 'GÓC NHÌN:', 'hud.ballTracking': 'THEO DÕI BÓNG', 'hud.behindGoal': 'SAU CẦU MÔN',
    'hud.meter': 'THƯỚC ĐO', 'hud.aiGoalkeeper': 'THỦ MÔN BOT', 'hud.aiStriker': 'TIỀN ĐẠO BOT',
    'hud.defenseSim': 'Mô Phỏng Phòng Ngự', 'hud.precisionFK': 'Sút Phạt Chuẩn Xác', 'hud.aiming': 'ĐANG NGẮM',
    'hud.holdToCharge': 'GIỮ ĐỂ TÍCH LỰC', 'hud.releaseToStrikeInstruction': 'GIỮ PHÍM CÁCH / MÀN HÌNH • THẢ ĐỂ SÚT',
    'hud.weak': 'YẾU', 'hud.sweetSpot': 'HOÀN HẢO', 'hud.max': 'TỐI ĐA', 'hud.chargingPower': 'ĐANG TÍCH LỰC...',
    'hud.replay': 'XEM LẠI', 'game.goal': 'VÀO!', 'game.saved': 'CỨU THUA',
    'quickPlay.selectMode': 'Chọn chế độ chơi:', 'quickPlay.ranked': 'Xếp Hạng', 'quickPlay.vsAi': 'Đấu Với Bot / Cục Bộ',
    'country.selectTeams': 'CHỌN ĐỘI BÓNG', 'country.nationalTeams': 'Đội Tuyển Quốc Gia', 'country.teamsAvailable': 'Đội Tuyển Có Sẵn',
    'country.tapToSelect': 'Chạm để chọn', 'country.myTeam': 'ĐỘI CỦA BẠN', 'country.opponent': 'ĐỐI THỦ',
    'country.continueToMatch': 'TIẾP TỤC VÀO TRẬN', 'search.countries': 'Tìm quốc gia...', 'teamSelect.teams': 'Đội',
    'teamSelect.searchPlaceholder': 'Tìm đội tuyển quốc gia...', 'teamSelect.att': 'CÔNG', 'teamSelect.def': 'THỦ',
    'team.selectNew': 'CHỌN ĐỘI MỚI', 'team.selectNewDesc': 'Lựa chọn từ 120 đội tuyển quốc gia trên khắp thế giới',
    'online.matchTitle': 'TRẬN ĐẤU ONLINE', 'online.matchSubtitle': 'Kết nối trực tiếp và chọn đội tuyển trực tiếp:',
    'online.createRoom': 'Tạo Phòng Riêng', 'online.joinRoom': 'Vào Bằng Mã Phòng', 'online.joinRoomTitle': 'THAM GIA PHÒNG',
    'online.roomCode': 'Mã Phòng', 'online.copyCode': 'Sao Chép Mã', 'online.codeCopied': 'Đã Sao Chép!',
    'online.shareCode': 'Chia sẻ mã 4 số này cho bạn bè:', 'online.enterCode': 'Nhập mã phòng 4 số:',
    'online.findMatch': 'Tìm Trận Nhanh', 'online.searchingMatch': 'Đang tìm đối thủ...', 'online.stillSearching': 'Đang tìm kiếm người chơi...',
    'online.retrySearch': 'Thử Lại', 'online.cancelSearch': 'Hủy Tìm Kiếm', 'online.cancelRoom': 'Hủy Phòng',
    'online.leaveRoom': 'Rời Phòng', 'online.inviteLink': 'Sao Chép Link Mời', 'online.linkCopied': 'Đã Sao Chép Link!',
    'online.lookingOpponent': 'Đang tìm đối thủ trên toàn thế giới...', 'online.pairingAuto': 'Đang ghép nối...', 'online.ready': 'SẴN SÀNG',
    'online.bothSelected': 'Cả hai đã sẵn sàng! Bắt đầu trận...', 'online.selectTeamBelow': 'Chọn đội bóng của bạn bên dưới:',
    'online.lockedIn': 'ĐÃ XÁC NHẬN', 'online.selecting': 'Đang chọn...', 'online.choosing': 'Đang chọn đội tuyển...',
    'online.opponentLeft': 'Đối thủ đã rời khỏi phòng', 'online.opponentLeftSub': 'Chuẩn bị quay lại menu chính...',
    'online.roomCreated': 'ĐÃ TẠO PHÒNG', 'online.room': 'Phòng', 'online.host': 'Chủ Phòng', 'online.guest': 'Khách',
    'online.firstTurn': 'Bạn sút trước', 'online.secondTurn': 'Đối thủ sút trước',
    'online.matchStartingIn': 'Trận đấu bắt đầu sau', 'online.kickoff': 'BẮT ĐẦU TRẬN ĐẤU!',
    'online.leaveMatchTitle': 'RỜI TRẬN ĐẤU?', 'online.leaveMatchSub': 'Thoát trận giữa chừng sẽ tính là bạn bị xử thua.',
    'online.leaveMatch': 'RỜI TRẬN ĐẤU', 'online.leave': 'RỜI', 'online.returnToMenu': 'Về Menu Chính',
    'online.returningToMenu': 'Đang về Menu...', 'online.sessionDisconnected': 'Mất Kết Nối',
    'online.yourCountry': 'ĐỘI CỦA BẠN', 'online.oppCountry': 'ĐỘI ĐỐI THỦ',
    'online.waitingOpponent': 'Đang chờ đối thủ chọn...', 'online.waitingOpponentCode': 'Đang chờ bạn bè nhập mã...',
    'online.connectSub': 'Hệ thống máy chủ thi đấu 1v1 trực tuyến toàn cầu', 'modal.matchmaking': 'Đang Tìm Đối Thủ...',
    'modal.matchmakingDesc': 'Tìm kiếm người chơi trên hệ thống', 'modal.searchingTime': 'Thời Gian Tìm',
    'modal.opponentFound': 'ĐÃ TÌM THẤY ĐỐI THỦ!', 'modal.connectingBot': 'Kết nối với bot sau 30 giây...',
    'modal.quitMatchSub': 'Tiến trình trận đấu hiện tại sẽ không được lưu.', 'modal.forfeitMatchTitle': 'BỎ CUỘC?',
    'modal.forfeitMatchSub': 'Thoát bây giờ sẽ bị tính là một trận thua.', 'modal.forfeit': 'BỎ CUỘC',
    'match.opponentLeftTitle': 'ĐỐI THỦ ĐÃ RỜI TRẬN', 'match.opponentLeftDesc': 'Đối thủ của bạn đã ngắt kết nối.',
    'match.playAgainUnavailable': 'Không thể tái đấu do đối thủ đã thoát.',
    'match.waitingOpponent': 'Đang chờ câu trả lời của đối thủ...', 'match.changeTeams': 'ĐỔI ĐỘI BÓNG',
    'tournament.selectFormat': 'Chọn thể thức:', 'tournament.globalCup': 'Cúp Thế Giới', 'tournament.customCup': 'Cúp Tùy Chỉnh',
    'tournament.inDevelopment': 'ĐANG PHÁT TRIỂN', 'tournament.onlineWorldCup': 'CÚP THẾ GIỚI ONLINE',
    'tournament.multiplayerWorldCup': 'Giải Vô Địch Thế Giới & Nhánh Đấu Trực Tiếp', 'tournament.knockoutBrackets': 'Nhánh Đấu 16 Đội Loại Trực Tiếp',
    'tournament.knockoutBracketsSub': 'Giải đấu loại trực tiếp theo thời gian thực', 'tournament.globalLeaderboards': 'Bảng Xếp Hạng Mùa Giải Toàn Cầu',
    'tournament.globalLeaderboardsSub': 'Nhận điểm xếp hạng và cúp vô địch', 'tournament.exclusiveUnlockables': 'Áo Đấu & Bóng Độc Quyền Vô Địch',
    'tournament.exclusiveUnlockablesSub': 'Phần thưởng danh giá cho nhà vô địch', 'tournament.playOfflineNow': 'ĐẤU WORLD CUP OFFLINE',
    'tournament.selectYourTeam': 'CHỌN ĐỘI TUYỂN CỦA BẠN', 'tournament.worldCupQualifiedSub': 'FIFA World Cup • 40 Quốc Gia Vượt Qua Vòng Loại (Bảng A – J)',
    'tournament.searchCountry': 'Tìm quốc gia hoặc bảng đấu...', 'tournament.qualifiedNations': 'Các Đội Vượt Qua Vòng Loại',
    'tournament.tapToSelect': 'Chạm Để Chọn', 'tournament.selected': 'ĐÃ CHỌN', 'tournament.ovr': 'CHỈ SỐ',
    'tournament.randomGroupDraw': 'Bốc thăm chia bảng ngẫu nhiên khi bắt đầu', 'tournament.tapAnyCountryPrompt': 'CHẠM VÀO MỘT QUỐC GIA ĐỂ CHỌN ĐỘI BÓNG',
    'tournament.enterWorldCup': 'VÀO GIẢI WORLD CUP (BẢNG A - J)', 'tournament.backToMenu': 'Về Menu Chính',
    'tournament.forfeitMatch': 'BỎ CUỘC TRẬN ĐẤU', 'tournament.continue': 'TIẾP TỤC VÀO VÒNG LOẠI TRỰC TIẾP',
    'tournament.championTitle': '★ NHÀ VÔ ĐỊCH THẾ GIỚI ★', 'tournament.worldChampions': 'VÔ ĐỊCH THẾ GIỚI',
    'tournament.winnerLiftsCup': 'Bạn đã nâng cao chiếc Cúp Vàng Thế Giới!', 'tournament.freeKickCup': 'Giải Vô Địch Sút Phạt Toàn Cầu',
    'tournament.roundOf16': 'Vòng 1/8', 'tournament.quarterFinals': 'Tứ Kết', 'tournament.semiFinal1': 'Bán Kết 1',
    'tournament.semiFinal2': 'Bán Kết 2', 'tournament.worldFinal': 'Chung Kết World Cup', 'tournament.awaitingFinal': 'Chờ Đội Vào Chung Kết',
    'tournament.fixture': 'Trận Đấu', 'tournament.ft': 'HẾT GIỜ', 'tournament.tbd': 'CHƯA XÁC ĐỊNH', 'tournament.cancelTournament': 'Hủy Giải Đấu',
    'practice.selectDrill': 'Chọn bài tập:', 'practice.freeKick': 'SÚT PHẠT',
    'practice.freeKickSub': 'Chơi ngay • Vượt hàng rào và góc hiểm', 'practice.instant': 'Nhanh',
    'practice.penalty': 'PHẠT ĐỀN', 'practice.penaltySub': '1v1 với thủ môn • Không giới hạn giờ', 'practice.random': 'Ngẫu Nhiên',
    'practice.exitTitle': 'THOÁT KHỎI LUYỆN TẬP?', 'practice.exitSub': 'Bạn có thể quay lại menu chính bất cứ lúc nào.',
    'practice.exitButton': 'THOÁT LUYỆN TẬP', 'survival.title': 'Đấu Trường Sinh Tồn',
    'survival.subtitle': '3 Mạng • Chuỗi Bất Tận • Đối Đầu', 'survival.arenaTitle': 'ĐẤU TRƯỜNG SINH TỒN',
    'survival.onlineSurvivalTitle': 'SINH TỒN 1V1 ONLINE',
    'survival.onlineSurvivalSubtitle': '3 Mạng • Đấu 1v1 Trực Tiếp • Thử Thách Chuỗi Bàn Thắng',
    'survival.selectGameMode': 'Chọn chế độ chơi:', 'survival.offlineSurvivalBtn': 'SINH TỒN OFFLINE',
    'survival.onlineDuelBtn': 'ĐỐI ĐẦU 1V1 ONLINE', 'survival.rulesBtn': 'Luật Chơi',
    'survival.rulesTitle': 'LUẬT CHẾ ĐỘ SINH TỒN', 'survival.rulesSubtitle': 'Tuân thủ 2 quy tắc sau để phá kỷ lục:',
    'survival.rule1Title': 'Hệ Thống 3 Mạng',
    'survival.rule1Desc': 'Mỗi người bắt đầu với 3 trái tim. Sút hỏng hoặc bị cản phá mất 1 mạng. Người hết mạng trước sẽ thua!',
    'survival.rule2Title': 'Đấu Luân Phiên & Đồng Hồ 100 Giây',
    'survival.rule2Desc': 'Thay phiên nhau sút phạt với đồng hồ đếm ngược 100 giây. Ghi bàn để duy trì chuỗi thắng!',
    'survival.backToRules': 'Quay Lại Luật Chơi', 'survival.howItWorks': 'Cách thức hoạt động', 'survival.guideBadge': 'HƯỚNG DẪN SINH TỒN',
    'survival.livesRemaining': 'Mạng Còn Lại', 'survival.bestRecord': 'Kỷ Lục Mọi Thời Đại', 'survival.bestStreak': 'CHUỖI TỐT NHẤT',
    'survival.startRun': 'Bắt Đầu Lượt Chơi', 'survival.personalRecord': 'Kỷ Lục Cá Nhân', 'survival.goalStreak': 'CHUỖI BÀN THẮNG',
    'survival.goalsStreak': 'CHUỖI BÀN THẮNG', 'survival.kicks': 'Cú Sút', 'survival.duel': 'ĐỐI ĐẦU SINH TỒN 1V1',
    'survival.duelSub': 'Đấu Loại Trực Tuyến', 'survival.runEnded': 'KẾT THÚC LƯỢT CHƠI!',
    'survival.challengeComplete': 'Hoàn Thành Thử Thách Sinh Tồn', 'survival.finalGoalsStreak': 'Tổng Chuỗi Bàn Thắng',
    'survival.challengeMode': 'Chế Độ Thử Thách', 'survival.reviveExtraLife': 'HỒI SINH (+1 MẠNG THÊM)',
    'survival.endSurvivalTitle': 'DỪNG CHẾ ĐỘ SINH TỒN?', 'survival.endSurvival': 'DỪNG', 'survival.endRun': 'KẾT THÚC LƯỢT',
    'survival.concludeSub': 'Trận đấu sẽ dừng lại ngay lập tức.', 'survival.currentStreak': 'Chuỗi hiện tại:',
    'wager.title': 'Đấu Trường Đặt Cược', 'wager.subtitle': 'Chọn mức cược • Người thắng nhận toàn bộ xu!',
    'wager.rookie': 'Đấu Trường Tân Binh', 'wager.pro': 'Đấu Trường Cao Thủ', 'wager.champion': 'Đấu Trường Quán Quân', 'wager.legend': 'Đấu Trường Huyền Thoại',
    'wager.entryFee': 'Phí Tham Gia', 'wager.entry': 'VÀO CỬA', 'wager.prizePot': 'Tổng Thưởng', 'wager.winPot': 'THƯỞNG NGƯỜI THẮNG',
    'wager.highRoller': 'Đấu Cược Lớn Trực Tiếp', 'wager.bottomBanner': 'Khám phá đấu trường • Cược cao, nhân đôi phần thưởng!',
    'wager.tapToSelect': 'Chạm để chọn', 'wager.playWithCoins': 'Chơi bằng xu', 'wager.needMoreCoins': 'Cần thêm xu',
    'wager.forfeitWager': 'BỎ CUỘC', 'wager.surrenderTitle': 'BỎ CUỘC ĐẶT CƯỢC?',
    'wager.surrenderSub': 'Bỏ cuộc sẽ mất toàn bộ số xu đã đặt:', 'wager.surrender': 'BỎ CUỘC', 'wager.victory': 'CHIẾN THẮNG TRẬN CƯỢC!',
    'wager.coinDuelResults': 'Kết Quả Đối Đầu', 'wager.drawRefunded': 'HÒA • HOÀN LẠI TIỀN CƯỢC',
    'wager.arenaPot': 'Hũ Tiền Đấu Trường', 'wager.netResult': 'Thu Nhập Thực Tế',
    'wager.opponentLeft': 'Đối thủ đã thoát khỏi trận', 'wager.rematch': 'TÁI ĐẤU CƯỢC',
    'targetSmash.title': 'BẮN MỤC TIÊU', 'targetSmash.arcadeBadge': 'CHẾ ĐỘ ARCADE MỚI',
    'targetSmash.trickshotSubtitle': 'Mục Tiêu & Cú Sút Xoáy Điệu Nghệ', 'targetSmash.selectStage': 'Màn (1 - 10)',
    'targetSmash.unlocked': 'Đã Mở Khóa', 'targetSmash.stage': 'Màn', 'targetSmash.objective': 'Mục Tiêu',
    'targetSmash.highScore': 'Kỷ Lục', 'targetSmash.pts': 'ĐIỂM', 'targetSmash.distance': 'Khoảng Cách',
    'targetSmash.defendersWall': 'Hàng Rào Chắn', 'targetSmash.players': 'Cầu Thủ', 'targetSmash.targetScore': 'Điểm Yêu Cầu',
    'targetSmash.targetRequired': 'Điểm Cần Đạt', 'targetSmash.playStage': 'CHƠI MÀN NÀY', 'targetSmash.stageLocked': 'MÀN ĐANG KHÓA',
    'targetSmash.stageCleared': 'VƯỢT MÀN THÀNH CÔNG!', 'targetSmash.stageFailed': 'VƯỢT MÀN THẤT BẠI', 'targetSmash.finalScore': 'Điểm Cuối Cùng',
    'targetSmash.coinsReward': 'Thưởng Xu', 'targetSmash.nextStage': 'MÀN TIẾP THEO', 'targetSmash.retryStage': 'THỬ LẠI',
    'targetSmash.exitToSelect': 'CHỌN MÀN KHÁC', 'divisions.title': 'Giải Đấu Hạng', 'divisions.titleUpper': 'GIẢI ĐẤU HẠNG',
    'divisions.rank': 'Thứ Hạng', 'divisions.titleTarget': 'Mục Tiêu Ngôi Vương', 'divisions.titleClaimed': 'Đã Đoạt Ngôi Vương!',
    'divisions.ptsForTrophy': 'Điểm Cần Để Đoạt Cúp', 'divisions.seasonFinished': 'Hết Mùa Giải',
    'divisions.promotionAchieved': 'Thăng Hạng Thành Công!', 'divisions.thisSeason': 'Mùa Này',
    'divisions.matchesLeft': 'Trận Còn Lại', 'divisions.ptsNeeded': 'Điểm Cần Đạt', 'divisions.win': 'Thắng',
    'divisions.draw': 'Hòa', 'divisions.loss': 'Thua', 'divisions.pt': 'ĐIỂM', 'divisions.pts': 'ĐIỂM',
    'divisions.allTime': 'Thành Tích Lịch Sử', 'divisions.matchesHistory': 'Lịch Sử Đấu', 'divisions.match': 'Trận',
    'divisions.noMatchesYet': 'Chưa đấu trận nào trong mùa giải này', 'divisions.noMatchesSub': 'Bắt đầu mùa giải của bạn ngay bên dưới!',
    'divisions.nextMatchChooseOpponent': 'Trận Kế Tiếp • Chọn Đối Thủ', 'divisions.whoDoYouWantToPlay': 'Chọn đối thủ tiếp theo của bạn:',
    'divisions.teamsAvailable': 'Đội Tuyển Có Sẵn', 'divisions.searchNationalTeam': 'Tìm đội tuyển quốc gia...',
    'divisions.playMatchVs': 'THI ĐẤU VỚI', 'divisions.opponent': 'Đối Thủ', 'divisions.opponentUpper': 'ĐỐI THỦ',
    'divisions.opponentConnected': 'Đối Thủ Đã Kết Nối', 'divisions.change': 'Đổi', 'divisions.chooseOpponent': 'Chọn Đối Thủ',
    'divisions.divShort': 'HẠNG', 'divisions.of': '/', 'divisions.continueTo': 'Tiếp tục đến', 'divisions.next': 'Tiếp',
    'divisions.findingOpponent': 'Đang Tìm Đối Thủ Trong Hạng...', 'divisions.matchingWithOnline': 'Tìm kiếm người chơi cùng phân hạng',
    'divisions.searchingActivePlayers': 'Đang quét máy chủ giải đấu...', 'divisions.matchStartingIn': 'Trận đấu bắt đầu sau',
    'divisions.cancelMatchmaking': 'Hủy', 'divisions.cancelSearch': 'Hủy Tìm Kiếm', 'divisions.wdl': 'T-H-B',
    'division.return': 'Về Phân Hạng', 'division.reward': 'Phần Thưởng Hạng', 'result.victory': 'CHIẾN THẮNG!',
    'result.defeat': 'THẤT BẠI', 'result.draw': 'HÒA', 'result.champion': 'VÔ ĐỊCH THẾ GIỚI!', 'result.prizeWon': 'Phần Thưởng Nhận Được',
    'result.streak': 'Chuỗi Thắng', 'result.newRecord': 'KỶ LỤC MỚI!', 'result.coinsEarned': 'Xu Nhận Được',
    'result.finalScore': 'Tỉ Số Chung Cuộc', 'result.totalScore': 'Tổng Điểm', 'result.wonOnPenalties': 'THẮNG TRÊN CHẤM LUÂN LƯU',
    'result.lostOnPenalties': 'THUA TRÊN CHẤM LUÂN LƯU', 'result.survivalVictory': 'CHIẾN THẮNG SINH TỒN!',
    'result.survivalDefeat': 'BỊ LOẠI TRONG SINH TỒN', 'result.wagerResults': 'Kết Quả Trận Cược',
    'rematch.invitationTitle': 'Yêu Cầu Tái Đấu', 'rematch.invitationDesc': 'Đối thủ muốn đấu lại một trận!',
    'rematch.accept': 'Đồng Ý Tái Đấu', 'rematch.decline': 'Từ Chối', 'rematch.starting': 'Đang Bắt Đầu Tái Đấu...',
    'rematch.survivalRequested': 'Đối thủ yêu cầu Tái Đấu Sinh Tồn!',
    'rematch.survivalDesc': 'Chấp nhận để quay lại ngay trận đối đầu 1v1!',
    'rematch.wagerChallenge': 'thách đấu bạn trong Trận Cược Tái Đấu!', 'stats.goals': 'Bàn Thắng', 'stats.shots': 'Cú Sút',
    'status.live': 'TRỰC TIẾP', 'status.offline': 'OFFLINE', 'status.winner': 'THẮNG', 'status.eliminated': 'BỊ LOẠI',
    'status.survived': 'SỐNG SÓT', 'status.left': 'ĐÃ RỜI', 'status.disconnected': 'MẤT KẾT NỐI',
    'store.title': 'Cửa Hàng Trang Bị', 'store.subtitle': 'HỌA TIẾT BÓNG 3D & MẶT CỎ SÂN VẬN ĐỘNG',
    'store.balls': 'Bóng', 'store.pitches': 'Sân Bóng', 'store.ballStore': 'CỬA HÀNG BÓNG',
    'store.ballStoreDesc': 'Họa Tiết 3D & Mẫu Bóng Thi Đấu', 'store.pitchStore': 'CỬA HÀNG SÂN CỎ',
    'store.pitchStoreDesc': 'Kiểu Cắt Cỏ Sân Vận Động', 'store.selectCategory': 'CHỌN DANH MỤC',
    'store.unlockedAndEquipped': 'ĐÃ MỞ KHÓA & TRANG BỊ', 'store.owned': 'Đã Sở Hữu', 'store.buyFor': 'Mua với giá',
    'store.notEnoughCoins': 'KHÔNG ĐỦ XU!', 'store.needMore': 'CẦN THÊM', 'store.more': 'XU NỮA',
    'profile.title': 'Hồ Sơ Cầu Thủ', 'profile.cloudStorageNotice': 'LƯU TRỮ ĐÁM MÂY CRAZYGAMES & BỘ NHỚ MÁY',
    'replays.subtitle': 'Xem và quản lý các siêu phẩm bàn thắng đẹp mắt đã lưu', 'replays.savedReplays': 'PHA BÓNG ĐÃ LƯU',
    'replays.savedHighlights': 'KHOẢNH KHẮC ĐÁNG CHÚ Ý', 'replays.clips': 'Video', 'replays.savedClips': 'Pha Bóng Đã Lưu',
    'replays.noSavedReplays': 'CHƯA CÓ PHA BÓNG NÀO', 'replays.noHighlightsTitle': 'CHƯA CÓ KHOẢNH KHẮC NÀO',
    'replays.noHighlightsDesc': 'Ghi bàn trong trận và chạm LƯU ở góc màn hình khi xem lại!',
    'replays.playMatchNow': 'CHƠI TRẬN ĐẤU NGAY', 'replays.emptyInstructions': 'Ghi một siêu phẩm và bấm LƯU ở góc phải trên cùng của video quay lại!',
    'replays.savedHighlight': 'BÀN THẮNG ĐÃ LƯU', 'replays.savedDate': 'NGÀY', 'replays.shotDistance': 'KHOẢNG CÁCH SÚT',
    'replays.longestStrike': 'Cú Sút Xa Nhất', 'replays.goalHighlights': 'Siêu Phẩm Ghi Bàn', 'replays.watchReplay': 'XEM LẠI PHA BÓNG',
    'replays.exitReplay': 'THOÁT XEM LẠI', 'replays.deleteReplay': 'Xóa Pha Bóng',
    'replays.confirmDelete': 'Bạn có chắc chắn muốn xóa pha bóng đã lưu này?', 'replays.deleteAllConfirm': 'XÓA TẤT CẢ PHA BÓNG?',
    'replays.deleteAllDesc': 'Bạn có chắc chắn muốn xóa toàn bộ bộ sưu tập xem lại?', 'ads.videoReward': 'PHẦN THƯỞNG VIDEO',
    'ads.coinsReward': 'PHẦN THƯỞNG XU', 'ads.watchToEarn': 'Xem video quảng cáo nhận ngay +50 xu',
    'ads.instantBoost': 'Nhận Xu Tức Thì', 'ads.integrationFinalizing': 'Đang hoàn tất tích hợp quảng cáo.',
    'ads.unlockAllItems': 'Mở khóa toàn bộ 50 quả bóng và 50 kiểu mặt sân cỏ!', 'ads.loading': 'ĐANG TẢI QUẢNG CÁO...',
    'lang.title': 'Cài Đặt Ngôn Ngữ', 'lang.subtitle': 'Chọn ngôn ngữ của bạn (Hỗ trợ 16 ngôn ngữ quốc tế)',
    'lang.autoDetect': 'Ngôn Ngữ Tự Động Nhận Diện', 'lang.currentlyActive': 'ĐANG HOẠT ĐỘNG',
    'lang.sdkSyncTitle': 'Đồng Bộ CrazyGames', 'lang.sdkSyncDesc': 'Ngôn ngữ trò chơi tự động đồng bộ theo tài khoản cổng game của bạn',
    'lang.searchPlaceholder': 'Tìm kiếm ngôn ngữ hoặc quốc gia...', 'lang.tabAll': 'Tất Cả (16)', 'lang.tabPopular': 'Phổ Biến',
    'lang.tabEurope': 'Châu Âu', 'lang.tabAmericas': 'Châu Mỹ', 'lang.tabAsiaMe': 'Châu Á & Trung Đông',
    'lang.noMatches': 'Không tìm thấy ngôn ngữ phù hợp', 'lang.noMatchesDesc': 'Hãy thử gõ tên quốc gia hoặc ngôn ngữ khác',
    'lang.resetFilters': 'Đặt Lại Bộ Lọc'
}

print("ID and VI loaded.")
