# -*- coding: utf-8 -*-
# Russian (ru) & Turkish (tr)

ru = {
    'nav.store': 'Магазин', 'nav.profile': 'Профиль', 'nav.replays': 'Повторы', 'nav.coins': 'Монеты',
    'nav.language': 'Язык', 'nav.bestStreak': 'Лучшая серия', 'nav.online': 'Онлайн', 'nav.connecting': 'Подключение...',
    'game.title': 'FREE KICK LEGENDS', 'menu.quickPlay': 'БЫСТРАЯ ИГРА', 'menu.quickPlaySub': 'ОНЛАЙН И ОФФЛАЙН МАТЧИ',
    'menu.survivalMode': 'РЕЖИМ ВЫЖИВАНИЯ', 'survival.threeLives': '3 ЖИЗНИ', 'survival.endlessStreak': 'Бесконечная серия',
    'survival.best': 'Рекорд', 'survival.streak': 'СЕРИЯ', 'survival.onlineAvailable': 'Онлайн дуэль 1 на 1 доступна',
    'menu.wagerArena': 'АРЕНА СТАВОК', 'wager.betCoinsPot': 'Ставь монеты • Победитель забирает всё',
    'wager.onlineDuel': 'Онлайн дуэль 1 на 1 на монеты', 'wager.duel': 'ДУЭЛЬ', 'wager.arena': 'Арена', 'wager.bet': 'Ставка',
    'wager.winnerTakes': 'Победитель получает', 'wager.prizePot': 'Призовой фонд', 'menu.worldCup': 'ЧЕМПИОНАТ МИРА FIFA',
    'menu.tournamentFormat': 'Формат турнира', 'menu.practice': 'ТРЕНИРОВКА', 'menu.practiceSub': 'Отработка штрафных',
    'menu.shop': 'МАГАЗИН', 'menu.onlineMultiplayer': 'Онлайн мультиплеер доступен',
    'profile.savedReplaysStats': 'ПОВТОРЫ И СТАТИСТИКА', 'replays.title': 'Сохраненные повторы',
    'common.coins': 'МОНЕТЫ', 'common.coinsUpper': 'МОНЕТЫ', 'common.online': 'ОНЛАЙН', 'common.offline': 'ОФФЛАЙН',
    'common.back': 'НАЗАД', 'common.backToMenu': 'Вернуться в меню', 'common.active': 'АКТИВНО', 'common.done': 'ГОТОВО',
    'common.close': 'ЗАКРЫТЬ', 'common.gotIt': 'ПОНЯТНО', 'common.cancel': 'Отмена', 'common.continue': 'ПРОДОЛЖИТЬ',
    'common.exit': 'ВЫЙТИ', 'common.quit': 'ВЫХОД', 'common.play': 'ИГРАТЬ', 'common.saved': 'СОХРАНЕНО', 'common.goal': 'ГОЛ',
    'common.goals': 'голов', 'common.pts': 'ОЧК', 'common.you': 'Вы', 'common.opponent': 'Соперник',
    'common.watchAdCoins': 'Смотреть рекламу за +50 бесплатных монет', 'currency.coins': 'МОНЕТЫ',
    'btn.play': 'Играть сейчас', 'btn.select': 'Выбрать', 'btn.confirm': 'Подтвердить', 'btn.cancel': 'Отмена',
    'btn.close': 'Закрыть', 'btn.back': 'Назад', 'btn.continue': 'Продолжить', 'btn.nextMatch': 'Следующий матч',
    'btn.returnMenu': 'В главное меню', 'btn.equip': 'Надеть', 'btn.equipped': 'Надето', 'btn.unlock': 'Разблокировать',
    'btn.locked': 'Заблокировано', 'btn.saveReplay': 'Сохранить повтор', 'btn.save': 'СОХРАНИТЬ', 'btn.saved': 'СОХРАНЕНО',
    'btn.skip': 'ПРОПУСТИТЬ', 'btn.playAgain': 'Играть снова', 'btn.watchAd': 'Смотреть видео (+50 монет)', 'btn.freeCoins': 'Бесплатные монеты',
    'hud.aim': 'Прицел', 'hud.power': 'Сила', 'hud.curve': 'Кручение', 'hud.kick': 'Удар',
    'hud.stepAim': 'УСТАНОВИТЕ УГОЛ', 'hud.stepPower': 'ВЫБЕРИТЕ СИЛУ УДАРА', 'hud.stepCurve': 'ЗАКРУТИТЕ МЯЧ',
    'hud.stepKick': 'ВЫПОЛНИТЕ УДАР', 'hud.shoot': 'УДАР!', 'hud.tapToLock': 'НАЖМИТЕ ДЛЯ ФИКСАЦИИ',
    'hud.tapToKick': 'НАЖМИТЕ ДЛЯ УДАРА', 'hud.goal': 'ГОЛ!', 'hud.saved': 'СЕЙВ!', 'hud.missed': 'МИМО!',
    'hud.wallBlocked': 'СТЕНКА ЗАБЛОКИРОВАЛА!', 'hud.postHit': 'ШТАНГА!', 'hud.suddenDeath': 'ДО ЗОЛОТОГО ГОЛА',
    'hud.goldenGoal': 'ЗОЛОТОЙ ГОЛ', 'hud.penaltyShootout': 'СЕРИЯ ПЕНАЛЬТИ', 'hud.turn': 'Ход',
    'hud.yourTurn': 'ВАШ ХОД', 'hud.oppTurn': 'ХОД СОПЕРНИКА', 'hud.aiThinking': 'ИИ ДУМАЕТ...',
    'hud.aiAiming': 'ИИ ЦЕЛИТСЯ...', 'hud.aiStriking': 'ИИ БЬЕТ...', 'hud.timer': 'Время',
    'hud.matchOver': 'МАТЧ ОКОНЧЕН', 'hud.rematch': 'Реванш', 'hud.exitMatch': 'Выйти из матча',
    'hud.resume': 'Продолжить', 'hud.pause': 'Пауза', 'hud.yourTurnPenalty': 'ВАШ УДАР С ПЕНАЛЬТИ',
    'hud.oppPenalty': 'СОПЕРНИК БЬЕТ ПЕНАЛЬТИ...', 'hud.aiPenalty': 'ИИ БЬЕТ ПЕНАЛЬТИ...',
    'hud.playIn': 'КАМЕРА:', 'hud.ballTracking': 'СЛЕДИТЬ ЗА МЯЧОМ', 'hud.behindGoal': 'ЗА ВОРОТАМИ',
    'hud.meter': 'ШКАЛА', 'hud.aiGoalkeeper': 'ИИ ВРАТАРЬ', 'hud.aiStriker': 'ИИ НАПАДАЮЩИЙ',
    'hud.defenseSim': 'Симуляция защиты', 'hud.precisionFK': 'Точный штрафной удар', 'hud.aiming': 'ПРИЦЕЛИВАНИЕ',
    'hud.holdToCharge': 'УДЕРЖИВАЙТЕ ДЛЯ СИЛЫ', 'hud.releaseToStrikeInstruction': 'УДЕРЖИВАЙТЕ ПРОБЕЛ / ЭКРАН • ОТПУСТИТЕ ДЛЯ УДАРА',
    'hud.weak': 'СЛАБО', 'hud.sweetSpot': 'ИДЕАЛЬНО', 'hud.max': 'МАКС', 'hud.chargingPower': 'НАБОР СИЛЫ...',
    'hud.replay': 'ПОВТОР', 'game.goal': 'ГОЛ!', 'game.saved': 'СЕЙВ',
    'quickPlay.selectMode': 'Выберите режим матча:', 'quickPlay.ranked': 'Рейтинговый', 'quickPlay.vsAi': 'Против ИИ / Локально',
    'country.selectTeams': 'ВЫБОР КОМАНД', 'country.nationalTeams': 'Сборные страны', 'country.teamsAvailable': 'Доступные сборные',
    'country.tapToSelect': 'Нажмите, чтобы выбрать', 'country.myTeam': 'МОЯ КОМАНДА', 'country.opponent': 'СОПЕРНИК',
    'country.continueToMatch': 'ПЕРЕЙТИ К МАТЧУ', 'search.countries': 'Поиск страны...', 'teamSelect.teams': 'Команды',
    'teamSelect.searchPlaceholder': 'Поиск сборной...', 'teamSelect.att': 'НАП', 'teamSelect.def': 'ЗАЩ',
    'team.selectNew': 'ВЫБРАТЬ НОВУЮ СБОРНУЮ', 'team.selectNewDesc': 'Выберите из 120 национальных сборных мира',
    'online.matchTitle': 'ОНЛАЙН МАТЧ', 'online.matchSubtitle': 'Подключайтесь и выбирайте сборные в реальном времени:',
    'online.createRoom': 'Создать приватную комнату', 'online.joinRoom': 'Войти по коду', 'online.joinRoomTitle': 'ВОЙТИ В КОМНАТУ',
    'online.roomCode': 'Код комнаты', 'online.copyCode': 'Копировать код', 'online.codeCopied': 'Скопировано!',
    'online.shareCode': 'Отправьте этот 4-значный код другу:', 'online.enterCode': 'Введите 4-значный код:',
    'online.findMatch': 'Быстрый онлайн матч', 'online.searchingMatch': 'Поиск соперников...', 'online.stillSearching': 'Поиск активных игроков...',
    'online.retrySearch': 'Повторить поиск', 'online.cancelSearch': 'Отменить поиск', 'online.cancelRoom': 'Отменить комнату',
    'online.leaveRoom': 'Покинуть комнату', 'online.inviteLink': 'Копировать ссылку-приглашение', 'online.linkCopied': 'Ссылка скопирована!',
    'online.lookingOpponent': 'Поиск соперника по всему миру...', 'online.pairingAuto': 'Подключение к игроку...', 'online.ready': 'ГОТОВ',
    'online.bothSelected': 'Оба готовы! Матч начинается...', 'online.selectTeamBelow': 'Выберите вашу команду ниже:',
    'online.lockedIn': 'ПОДТВЕРЖДЕНО', 'online.selecting': 'Выбор...', 'online.choosing': 'Выбирает сборную...',
    'online.opponentLeft': 'Соперник покинул комнату', 'online.opponentLeftSub': 'Возврат в меню через пару секунд...',
    'online.roomCreated': 'КОМНАТА СОЗДАНА', 'online.room': 'Комната', 'online.host': 'Хост', 'online.guest': 'Гость',
    'online.firstTurn': 'Вы бьете первым', 'online.secondTurn': 'Соперник бьет первым',
    'online.matchStartingIn': 'Матч начнется через', 'online.kickoff': 'СТАРТ МАТЧА!',
    'online.leaveMatchTitle': 'ВЫЙТИ ИЗ МАТЧА?', 'online.leaveMatchSub': 'Выход принесет автоматическую победу сопернику.',
    'online.leaveMatch': 'ВЫЙТИ ИЗ МАТЧА', 'online.leave': 'ВЫЙТИ', 'online.returnToMenu': 'В главное меню',
    'online.returningToMenu': 'Возврат в меню...', 'online.sessionDisconnected': 'Сессия отключена',
    'online.yourCountry': 'ВАША СБОРНАЯ', 'online.oppCountry': 'СБОРНАЯ СОПЕРНИКА',
    'online.waitingOpponent': 'Ожидание выбора соперника...', 'online.waitingOpponentCode': 'Ожидание друга с кодом...',
    'online.connectSub': 'Глобальные мультиплеерные 1v1 серверы', 'modal.matchmaking': 'Поиск соперника...',
    'modal.matchmakingDesc': 'Поиск игроков на серверах', 'modal.searchingTime': 'Время поиска',
    'modal.opponentFound': 'СОПЕРНИК НАЙДЕН!', 'modal.connectingBot': 'Подключение бота через 30с...',
    'modal.quitMatchSub': 'Текущий прогресс матча будет потерян.', 'modal.forfeitMatchTitle': 'СДАТЬСЯ?',
    'modal.forfeitMatchSub': 'Выход засчитывается как автоматическое поражение.', 'modal.forfeit': 'СДАТЬСЯ',
    'match.opponentLeftTitle': 'СОПЕРНИК ПОКИНУЛ МАТЧ', 'match.opponentLeftDesc': 'Ваш соперник отключился.',
    'match.playAgainUnavailable': 'Реванш недоступен, так как соперник вышел.',
    'match.waitingOpponent': 'Ожидание ответа соперника...', 'match.changeTeams': 'СМЕНИТЬ КОМАНДЫ',
    'tournament.selectFormat': 'Выберите формат:', 'tournament.globalCup': 'Мировой Кубок', 'tournament.customCup': 'Свой Кубок',
    'tournament.inDevelopment': 'В РАЗРАБОТКЕ', 'tournament.onlineWorldCup': 'ОНЛАЙН ЧЕМПИОНАТ МИРА',
    'tournament.multiplayerWorldCup': 'Сетевые чемпионаты и турнирные сетки', 'tournament.knockoutBrackets': 'Сетка плей-офф на 16 команд',
    'tournament.knockoutBracketsSub': 'Турниры на выбывание в реальном времени', 'tournament.globalLeaderboards': 'Глобальный сезонный рейтинг',
    'tournament.globalLeaderboardsSub': 'Зарабатывайте очки рейтинга и кубки', 'tournament.exclusiveUnlockables': 'Эксклюзивная форма и мячи',
    'tournament.exclusiveUnlockablesSub': 'Награды для чемпионов мира', 'tournament.playOfflineNow': 'ИГРАТЬ ЧМ ОФФЛАЙН',
    'tournament.selectYourTeam': 'ВЫБЕРИТЕ СБОРНУЮ', 'tournament.worldCupQualifiedSub': 'FIFA World Cup • 40 отобранных сборных (Группы A – J)',
    'tournament.searchCountry': 'Поиск страны или группы...', 'tournament.qualifiedNations': 'Отобранные страны',
    'tournament.tapToSelect': 'Нажмите для выбора', 'tournament.selected': 'ВЫБРАНО', 'tournament.ovr': 'ОБЩ',
    'tournament.randomGroupDraw': 'Случайная жеребьевка групп на старте', 'tournament.tapAnyCountryPrompt': 'НАЖМИТЕ НА СТРАНУ, ЧТОБЫ ВЫБРАТЬ',
    'tournament.enterWorldCup': 'НАЧАТЬ ЧЕМПИОНАТ МИРА (ГРУППЫ A - J)', 'tournament.backToMenu': 'В главное меню',
    'tournament.forfeitMatch': 'СДАТЬ МАТЧ', 'tournament.continue': 'ПЕРЕЙТИ В ПЛЕЙ-ОФФ',
    'tournament.championTitle': '★ ЧЕМПИОНЫ МИРА ★', 'tournament.worldChampions': 'ЧЕМПИОНЫ МИРА',
    'tournament.winnerLiftsCup': 'Вы подняли главный Кубок мира над головой!', 'tournament.freeKickCup': 'Мировой турнир по штрафным ударам',
    'tournament.roundOf16': '1/8 Финала', 'tournament.quarterFinals': '1/4 Финала', 'tournament.semiFinal1': 'Полуфинал 1',
    'tournament.semiFinal2': 'Полуфинал 2', 'tournament.worldFinal': 'Финал Чемпионата Мира', 'tournament.awaitingFinal': 'Ожидание финалиста',
    'tournament.fixture': 'Матч', 'tournament.ft': 'КОНЕЦ', 'tournament.tbd': 'ОПРЕДЕЛИТСЯ', 'tournament.cancelTournament': 'Отменить турнир',
    'practice.selectDrill': 'Выберите упражнение:', 'practice.freeKick': 'ШТРАФНОЙ УДАР',
    'practice.freeKickSub': 'Мгновенная игра • Стенка и углы ворот', 'practice.instant': 'Быстро',
    'practice.penalty': 'ПЕНАЛЬТИ', 'practice.penaltySub': '1 на 1 против вратаря • Без таймера', 'practice.random': 'Случайно',
    'practice.exitTitle': 'ВЫЙТИ ИЗ ТРЕНИРОВКИ?', 'practice.exitSub': 'Вы можете вернуться в главное меню в любой момент.',
    'practice.exitButton': 'ВЫЙТИ ИЗ ТРЕНИРОВКИ', 'survival.title': 'Арена Выживания',
    'survival.subtitle': '3 Жизни • Бесконечные серии • Дуэли', 'survival.arenaTitle': 'АРЕНА ВЫЖИВАНИЯ',
    'survival.onlineSurvivalTitle': 'ОНЛАЙН ВЫЖИВАНИЕ 1 НА 1',
    'survival.onlineSurvivalSubtitle': '3 Жизни • Онлайн дуэль в прямом эфире • Бесконечная серия голов',
    'survival.selectGameMode': 'Выберите режим игры:', 'survival.offlineSurvivalBtn': 'ОФФЛАЙН ВЫЖИВАНИЕ',
    'survival.onlineDuelBtn': 'ОНЛАЙН ДУЭЛЬ 1 НА 1', 'survival.rulesBtn': 'Правила',
    'survival.rulesTitle': 'ПРАВИЛА ВЫЖИВАНИЯ', 'survival.rulesSubtitle': 'Соблюдайте 2 правила, чтобы побить рекорд:',
    'survival.rule1Title': 'Система 3 жизней',
    'survival.rule1Desc': 'Оба игрока начинают с 3 сердцами. Промах или сейв отнимает 1 жизнь. Проиграл тот, у кого раньше кончились жизни!',
    'survival.rule2Title': 'Поочередные удары и таймер 100с',
    'survival.rule2Desc': 'Удары по очереди с таймером на 100 секунд. Забивайте голы для увеличения победной серии!',
    'survival.backToRules': 'Назад к правилам', 'survival.howItWorks': 'Как это работает', 'survival.guideBadge': 'ГИД ПО ВЫЖИВАНИЮ',
    'survival.livesRemaining': 'Осталось жизней', 'survival.bestRecord': 'Рекорд за все время', 'survival.bestStreak': 'ЛУЧШАЯ СЕРИЯ',
    'survival.startRun': 'Начать забег', 'survival.personalRecord': 'Личный рекорд', 'survival.goalStreak': 'СЕРИЯ ГОЛОВ',
    'survival.goalsStreak': 'СЕРИЯ ГОЛОВ', 'survival.kicks': 'Удары', 'survival.duel': 'ДУЭЛЬ НА ВЫЖИВАНИЕ 1 НА 1',
    'survival.duelSub': 'Онлайн битва на вылет', 'survival.runEnded': 'ЗАБЕГ ОКОНЧЕН!',
    'survival.challengeComplete': 'Испытание завершено', 'survival.finalGoalsStreak': 'Итоговая серия голов',
    'survival.challengeMode': 'Режим испытания', 'survival.reviveExtraLife': 'ВОСКРЕСИТЬ (+1 ЖИЗНЬ)',
    'survival.endSurvivalTitle': 'ЗАВЕРШИТЬ ВЫЖИВАНИЕ?', 'survival.endSurvival': 'ЗАВЕРШИТЬ', 'survival.endRun': 'ЗАКОНЧИТЬ ЗАБЕГ',
    'survival.concludeSub': 'Матч будет немедленно остановлен.', 'survival.currentStreak': 'Текущая серия:',
    'wager.title': 'Арены Ставок', 'wager.subtitle': 'Выбирай ставку • Победитель забирает банк!',
    'wager.rookie': 'Арена Новичков', 'wager.pro': 'Арена Профи', 'wager.champion': 'Арена Чемпионов', 'wager.legend': 'Арена Легенд',
    'wager.entryFee': 'Входной взнос', 'wager.entry': 'ВХОД', 'wager.prizePot': 'Призовой банк', 'wager.winPot': 'ПРИЗ ПОБЕДИТЕЛЯ',
    'wager.highRoller': 'Дуэль на крупные ставки', 'wager.bottomBanner': 'Исследуй арены • Высокие ставки, удвоенный куш!',
    'wager.tapToSelect': 'Нажмите для выбора', 'wager.playWithCoins': 'Играть на монеты', 'wager.needMoreCoins': 'Нужно больше монет',
    'wager.forfeitWager': 'СДАТЬ СТАВКУ', 'wager.surrenderTitle': 'СДАТЬ СТАВКУ?',
    'wager.surrenderSub': 'Сдача приведет к потере поставленных монет:', 'wager.surrender': 'СДАТЬСЯ', 'wager.victory': 'ПОБЕДА В СТАВКЕ!',
    'wager.coinDuelResults': 'Результаты дуэли', 'wager.drawRefunded': 'НИЧЬЯ • ВЗНОС ВОЗВРАЩЕН',
    'wager.arenaPot': 'Банк арены', 'wager.netResult': 'Чистый выигрыш',
    'wager.opponentLeft': 'Соперник отключился от арены', 'wager.rematch': 'РЕВАНШ СО СТАВКОЙ',
    'targetSmash.title': 'ТИР ПО МИШЕНЯМ', 'targetSmash.arcadeBadge': 'НОВЫЙ АРКАДНЫЙ РЕЖИМ',
    'targetSmash.trickshotSubtitle': 'Мишени и Крученые Удары', 'targetSmash.selectStage': 'Уровень (1 - 10)',
    'targetSmash.unlocked': 'Разблокировано', 'targetSmash.stage': 'Уровень', 'targetSmash.objective': 'Задача',
    'targetSmash.highScore': 'Рекорд', 'targetSmash.pts': 'ОЧК', 'targetSmash.distance': 'Дистанция',
    'targetSmash.defendersWall': 'Стенка', 'targetSmash.players': 'Игроки', 'targetSmash.targetScore': 'Целевой счет',
    'targetSmash.targetRequired': 'Требуется очков', 'targetSmash.playStage': 'ИГРАТЬ УРОВЕНЬ', 'targetSmash.stageLocked': 'УРОВЕНЬ ЗАКРЫТ',
    'targetSmash.stageCleared': 'УРОВЕНЬ ПРОЙДЕН!', 'targetSmash.stageFailed': 'УРОВЕНЬ ПРОВАЛЕН', 'targetSmash.finalScore': 'Итоговый счет',
    'targetSmash.coinsReward': 'Награда в монетах', 'targetSmash.nextStage': 'СЛЕДУЮЩИЙ УРОВЕНЬ', 'targetSmash.retryStage': 'ПОВТОРИТЬ',
    'targetSmash.exitToSelect': 'К ВЫБОРУ УРОВНЕЙ', 'divisions.title': 'Лига Дивизионов', 'divisions.titleUpper': 'ЛИГА ДИВИЗИОНОВ',
    'divisions.rank': 'Место в дивизионе', 'divisions.titleTarget': 'Цель для титула', 'divisions.titleClaimed': 'Титул завоеван!',
    'divisions.ptsForTrophy': 'Очки до кубка чемпиона', 'divisions.seasonFinished': 'Сезон завершен',
    'divisions.promotionAchieved': 'Повышение в классе!', 'divisions.thisSeason': 'В этом сезоне',
    'divisions.matchesLeft': 'Осталось матчей', 'divisions.ptsNeeded': 'Нужно очков', 'divisions.win': 'Победа',
    'divisions.draw': 'Ничья', 'divisions.loss': 'Поражение', 'divisions.pt': 'ОЧК', 'divisions.pts': 'ОЧК',
    'divisions.allTime': 'История матчей', 'divisions.matchesHistory': 'История игр', 'divisions.match': 'Матч',
    'divisions.noMatchesYet': 'В этом сезоне матчей еще не сыграно', 'divisions.noMatchesSub': 'Начните свой путь в дивизионах!',
    'divisions.nextMatchChooseOpponent': 'Следующий матч • Выберите соперника', 'divisions.whoDoYouWantToPlay': 'Выберите соперника:',
    'divisions.teamsAvailable': 'Доступные сборные', 'divisions.searchNationalTeam': 'Поиск национальной сборной...',
    'divisions.playMatchVs': 'ИГРАТЬ МАТЧ ПРОТИВ', 'divisions.opponent': 'Соперник', 'divisions.opponentUpper': 'СОПЕРНИК',
    'divisions.opponentConnected': 'Соперник подключен', 'divisions.change': 'Сменить', 'divisions.chooseOpponent': 'Выбрать соперника',
    'divisions.divShort': 'ДИВ', 'divisions.of': 'из', 'divisions.continueTo': 'Перейти к', 'divisions.next': 'Далее',
    'divisions.findingOpponent': 'Поиск соперника в дивизионе...', 'divisions.matchingWithOnline': 'Подбор игроков вашего дивизиона',
    'divisions.searchingActivePlayers': 'Поиск по серверам дивизиона...', 'divisions.matchStartingIn': 'Матч начнется через',
    'divisions.cancelMatchmaking': 'Отменить подбор', 'divisions.cancelSearch': 'Отменить поиск', 'divisions.wdl': 'В-Н-П',
    'division.return': 'Назад в дивизионы', 'division.reward': 'Награда дивизиона', 'result.victory': 'ПОБЕДА!',
    'result.defeat': 'ПОРАЖЕНИЕ', 'result.draw': 'НИЧЬЯ', 'result.champion': 'ЧЕМПИОН МИРА!', 'result.prizeWon': 'Выигрыш',
    'result.streak': 'Текущая серия', 'result.newRecord': 'НОВЫЙ РЕКОРД!', 'result.coinsEarned': 'Заработано монет',
    'result.finalScore': 'Итоговый счет', 'result.totalScore': 'Всего очков', 'result.wonOnPenalties': 'ПОБЕДА ПО ПЕНАЛЬТИ',
    'result.lostOnPenalties': 'ПОРАЖЕНИЕ ПО ПЕНАЛЬТИ', 'result.survivalVictory': 'ПОБЕДА В ВЫЖИВАНИИ!',
    'result.survivalDefeat': 'ВЫБЫВАНИЕ ИЗ ВЫЖИВАНИЯ', 'result.wagerResults': 'Итоги ставки',
    'rematch.invitationTitle': 'Запрос реванша', 'rematch.invitationDesc': 'Соперник хочет сыграть реванш!',
    'rematch.accept': 'Принять реванш', 'rematch.decline': 'Отклонить', 'rematch.starting': 'Запуск реванша...',
    'rematch.survivalRequested': 'Соперник запросил реванш в Выживании!',
    'rematch.survivalDesc': 'Примите, чтобы мгновенно вернуться в дуэль 1 на 1!',
    'rematch.wagerChallenge': 'вызывает вас на реванш со ставкой!', 'stats.goals': 'Голы', 'stats.shots': 'Удары',
    'status.live': 'ПРЯМОЙ ЭФИР', 'status.offline': 'ОФФЛАЙН', 'status.winner': 'ПОБЕДИТЕЛЬ', 'status.eliminated': 'ВЫБЫЛ',
    'status.survived': 'ВЫЖИЛ', 'status.left': 'ВЫШЕЛ', 'status.disconnected': 'ОТКЛЮЧЕН',
    'store.title': 'Магазин экипировки', 'store.subtitle': '3D ТЕКСТУРЫ МЯЧЕЙ И ГАЗОНОВ',
    'store.balls': 'Мячи', 'store.pitches': 'Газоны', 'store.ballStore': 'МАГАЗИН МЯЧЕЙ',
    'store.ballStoreDesc': '3D текстуры и про-модели', 'store.pitchStore': 'МАГАЗИН СТАДИОНОВ',
    'store.pitchStoreDesc': 'Стрижки газонов мировых стадионов', 'store.selectCategory': 'ВЫБЕРИТЕ КАТЕГОРИЮ',
    'store.unlockedAndEquipped': 'РАЗБЛОКИРОВАНО И НАДЕТО', 'store.owned': 'Куплено', 'store.buyFor': 'Купить за',
    'store.notEnoughCoins': 'НЕ ХВАТАЕТ МОНЕТ!', 'store.needMore': 'НУЖНО ЕЩЕ', 'store.more': 'БОЛЬШЕ',
    'profile.title': 'Профиль игрока', 'profile.cloudStorageNotice': 'СОХРАНЕНИЕ В ОБЛАКЕ CRAZYGAMES И ЛОКАЛЬНО',
    'replays.subtitle': 'Смотрите и управляйте лучшими сохраненными голами', 'replays.savedReplays': 'СОХРАНЕННЫЕ ПОВТОРЫ',
    'replays.savedHighlights': 'ЛУЧШИЕ МОМЕНТЫ', 'replays.clips': 'Видео', 'replays.savedClips': 'Сохраненные клипы',
    'replays.noSavedReplays': 'НЕТ СОХРАНЕННЫХ ПОВТОРОВ', 'replays.noHighlightsTitle': 'НЕТ ЗАПИСЕЙ',
    'replays.noHighlightsDesc': 'Забейте красивый гол и нажмите СОХРАНИТЬ в повторе!',
    'replays.playMatchNow': 'СЫГРАТЬ МАТЧ', 'replays.emptyInstructions': 'Забейте гол и нажмите СОХРАНИТЬ в правом верхнем углу повтора!',
    'replays.savedHighlight': 'СОХРАНЕННЫЙ МОМЕНТ', 'replays.savedDate': 'ДАТА', 'replays.shotDistance': 'ДИСТАНЦИЯ УДАРА',
    'replays.longestStrike': 'Самый дальний удар', 'replays.goalHighlights': 'Лучшие моменты', 'replays.watchReplay': 'СМОТРЕТЬ ПОВТОР',
    'replays.exitReplay': 'ВЫЙТИ ИЗ ПОВТОРА', 'replays.deleteReplay': 'Удалить повтор', 'replays.confirmDelete': 'Удалить этот повтор?',
    'replays.deleteAllConfirm': 'УДАЛИТЬ ВСЕ ПОВТОРЫ?', 'replays.deleteAllDesc': 'Вы уверены, что хотите стереть все повторы?',
    'ads.videoReward': 'НАГРАДА ЗА ВИДЕО', 'ads.coinsReward': 'НАГРАДА В МОНЕТАХ', 'ads.watchToEarn': 'Смотрите видео за +50 монет',
    'ads.instantBoost': 'Мгновенный бонус монет', 'ads.integrationFinalizing': 'Интеграция рекламы завершается.',
    'ads.unlockAllItems': 'Откройте все 50 мячей и 50 стилей газона!', 'ads.loading': 'ЗАГРУЗКА РЕКЛАМЫ...',
    'lang.title': 'Настройки языка', 'lang.subtitle': 'Выберите ваш язык (доступно 16 мировых языков)',
    'lang.autoDetect': 'Язык определен автоматически', 'lang.currentlyActive': 'АКТИВЕН СЕЙЧАС',
    'lang.sdkSyncTitle': 'Синхронизация CrazyGames', 'lang.sdkSyncDesc': 'Язык игры автоматически подстраивается под настройки портала',
    'lang.searchPlaceholder': 'Поиск языка или страны...', 'lang.tabAll': 'Все (16)', 'lang.tabPopular': 'Популярные',
    'lang.tabEurope': 'Европа', 'lang.tabAmericas': 'Америка', 'lang.tabAsiaMe': 'Азия и Ближний Восток',
    'lang.noMatches': 'Язык не найден', 'lang.noMatchesDesc': 'Попробуйте ввести другое название страны или языка',
    'lang.resetFilters': 'Сбросить фильтры'
}

tr = {
    'nav.store': 'Mağaza', 'nav.profile': 'Profil', 'nav.replays': 'Tekrarlar', 'nav.coins': 'Altın',
    'nav.language': 'Dil', 'nav.bestStreak': 'En İyi Seri', 'nav.online': 'Çevrimiçi', 'nav.connecting': 'Bağlanıyor...',
    'game.title': 'FREE KICK LEGENDS', 'menu.quickPlay': 'HIZLI MAÇ', 'menu.quickPlaySub': 'ÇEVRİMİÇİ VE ÇEVRİMDIŞI MAÇLAR',
    'menu.survivalMode': 'HAYATTA KALMA MODU', 'survival.threeLives': '3 CAN', 'survival.endlessStreak': 'Sonsuz Seri',
    'survival.best': 'Rekor', 'survival.streak': 'SERİ', 'survival.onlineAvailable': 'Çevrimiçi 1v1 Hayatta Kalma',
    'menu.wagerArena': 'BAHİS ARENASI', 'wager.betCoinsPot': 'Altın Koy • Kazanan Tüm Havuzu Alır',
    'wager.onlineDuel': 'Çevrimiçi 1v1 Altın Bahis Düellosu', 'wager.duel': 'DÜELLO', 'wager.arena': 'Arena', 'wager.bet': 'Bahis',
    'wager.winnerTakes': 'Kazanan Alır', 'wager.prizePot': 'Ödül Havuzu', 'menu.worldCup': 'FIFA DÜNYA KUPASI',
    'menu.tournamentFormat': 'Turnuva Formatı', 'menu.practice': 'ANTRENMAN', 'menu.practiceSub': 'Serbest Vuruş Çalışması',
    'menu.shop': 'MAĞAZA', 'menu.onlineMultiplayer': 'Çevrimiçi Çok Oyunculu Mevcut',
    'profile.savedReplaysStats': 'TEKRARLAR VE İSTATİSTİK', 'replays.title': 'Kayıtlı Tekrarlar',
    'common.coins': 'ALTIN', 'common.coinsUpper': 'ALTIN', 'common.online': 'ÇEVRİMİÇİ', 'common.offline': 'ÇEVRİMDIŞI',
    'common.back': 'GERİ', 'common.backToMenu': 'Menüye Dön', 'common.active': 'AKTİF', 'common.done': 'BİTTİ VE DÖN',
    'common.close': 'KAPAT', 'common.gotIt': 'ANLADIM', 'common.cancel': 'İptal', 'common.continue': 'DEVAM ET',
    'common.exit': 'ÇIK', 'common.quit': 'ÇIKIŞ', 'common.play': 'OYNA', 'common.saved': 'KAYDEDİLDİ', 'common.goal': 'GOL',
    'common.goals': 'gol', 'common.pts': 'PUAN', 'common.you': 'Sen', 'common.opponent': 'Rakip',
    'common.watchAdCoins': '+50 ücretsiz altın için video izle', 'currency.coins': 'ALTIN',
    'btn.play': 'Şimdi Oyna', 'btn.select': 'Seç', 'btn.confirm': 'Onayla', 'btn.cancel': 'İptal',
    'btn.close': 'Kapat', 'btn.back': 'Geri', 'btn.continue': 'Devam', 'btn.nextMatch': 'Sonraki Maç',
    'btn.returnMenu': 'Ana Menü', 'btn.equip': 'Kuşan', 'btn.equipped': 'Kuşanıldı', 'btn.unlock': 'Kilidi Aç',
    'btn.locked': 'Kilitli', 'btn.saveReplay': 'Tekrarı Kaydet', 'btn.save': 'KAYDET', 'btn.saved': 'KAYDEDİLDİ',
    'btn.skip': 'GEÇ', 'btn.playAgain': 'Tekrar Oyna', 'btn.watchAd': 'Reklam İzle (+50 Altın)', 'btn.freeCoins': 'Ücretsiz Altın',
    'hud.aim': 'Nişan', 'hud.power': 'Güç', 'hud.curve': 'Falso', 'hud.kick': 'Şut',
    'hud.stepAim': 'HEDEF AÇISINI AYARLA', 'hud.stepPower': 'ŞUT GÜCÜNÜ KİLİTLE', 'hud.stepCurve': 'TOPA FALSO VER',
    'hud.stepKick': 'ŞUTU ÇEK', 'hud.shoot': 'ŞUT!', 'hud.tapToLock': 'KİLİTLEMEK İÇİN DOKUN',
    'hud.tapToKick': 'ŞUT İÇİN DOKUN', 'hud.goal': 'GOL!', 'hud.saved': 'KURTARIŞ!', 'hud.missed': 'DIŞARI!',
    'hud.wallBlocked': 'BARAJ ENGELLEDİ!', 'hud.postHit': 'DİREKTEN DÖNDÜ!', 'hud.suddenDeath': 'ALTIN GOL',
    'hud.goldenGoal': 'ALTIN GOL', 'hud.penaltyShootout': 'SERİ PENALTI ATIŞLARI', 'hud.turn': 'Sıra',
    'hud.yourTurn': 'SENİN SIRAN', 'hud.oppTurn': 'RAKİBİN SIRASI', 'hud.aiThinking': 'YAPAY ZEKA DÜŞÜNÜYOR...',
    'hud.aiAiming': 'YAPAY ZEKA NİŞAN ALIYOR...', 'hud.aiStriking': 'YAPAY ZEKA VURUYOR...', 'hud.timer': 'Süre',
    'hud.matchOver': 'MAÇ BİTTİ', 'hud.rematch': 'Rövanş', 'hud.exitMatch': 'Maçtan Çık',
    'hud.resume': 'Devam Et', 'hud.pause': 'Duraklat', 'hud.yourTurnPenalty': 'PENALTIYI SEN KULLANIYORSUN',
    'hud.oppPenalty': 'RAKİP PENALTI KULLANIYOR...', 'hud.aiPenalty': 'YAPAY ZEKA PENALTI KULLANIYOR...',
    'hud.playIn': 'KAMERA:', 'hud.ballTracking': 'TOPU TAKİP ET', 'hud.behindGoal': 'KALE ARKASI',
    'hud.meter': 'GÖSTERGE', 'hud.aiGoalkeeper': 'YAPAY ZEKA KALECİ', 'hud.aiStriker': 'YAPAY ZEKA FORVET',
    'hud.defenseSim': 'Savunma Simülasyonu', 'hud.precisionFK': 'Hassas Serbest Vuruş', 'hud.aiming': 'NİŞAN ALINIYOR',
    'hud.holdToCharge': 'GÜÇ YÜKLEMEK İÇİN BASILI TUT', 'hud.releaseToStrikeInstruction': 'BOŞLUK / EKRANA BASILI TUT • VURMAK İÇİN BIRAK',
    'hud.weak': 'ZAYIF', 'hud.sweetSpot': 'MÜKEMMEL', 'hud.max': 'MAKS', 'hud.chargingPower': 'GÜÇ YÜKLENİYOR...',
    'hud.replay': 'TEKRAR', 'game.goal': 'GOL!', 'game.saved': 'KURTARIŞ',
    'quickPlay.selectMode': 'Maç modunu seç:', 'quickPlay.ranked': 'Dereceli', 'quickPlay.vsAi': 'Vs Yapay Zeka / Yerel',
    'country.selectTeams': 'TAKIM SEÇİMİ', 'country.nationalTeams': 'Milli Takımlar', 'country.teamsAvailable': 'Mevcut Takımlar',
    'country.tapToSelect': 'Seçmek için dokun', 'country.myTeam': 'BENİM TAKIMIM', 'country.opponent': 'RAKİP',
    'country.continueToMatch': 'MAÇA GEÇ', 'search.countries': 'Ülke ara...', 'teamSelect.teams': 'Takımlar',
    'teamSelect.searchPlaceholder': 'Milli takım ara...', 'teamSelect.att': 'HÜC', 'teamSelect.def': 'SAV',
    'team.selectNew': 'YENİ TAKIM SEÇ', 'team.selectNewDesc': 'Dünyadan 120 milli takım arasından seçim yap',
    'online.matchTitle': 'ÇEVRİMİÇİ MAÇ', 'online.matchSubtitle': 'Canlı bağlanın ve birlikte milli takım seçin:',
    'online.createRoom': 'Özel Oda Oluştur', 'online.joinRoom': 'Kodla Katıl', 'online.joinRoomTitle': 'ÖZEL ODAYA KATIL',
    'online.roomCode': 'Oda Kodu', 'online.copyCode': 'Kodu Kopyala', 'online.codeCopied': 'Kopyalandı!',
    'online.shareCode': 'Bu 4 haneli kodu arkadaşınla paylaş:', 'online.enterCode': '4 haneli kodu gir:',
    'online.findMatch': 'Hızlı Eşleşme', 'online.searchingMatch': 'Rakip aranıyor...', 'online.stillSearching': 'Aktif oyuncular aranıyor...',
    'online.retrySearch': 'Tekrar Dene', 'online.cancelSearch': 'Aramayı İptal Et', 'online.cancelRoom': 'Odayı İptal Et',
    'online.leaveRoom': 'Odadan Çık', 'online.inviteLink': 'Davet Linkini Kopyala', 'online.linkCopied': 'Link Kopyalandı!',
    'online.lookingOpponent': 'Dünya genelinde rakip aranıyor...', 'online.pairingAuto': 'Oyuncuyla eşleşiliyor...', 'online.ready': 'HAZIR',
    'online.bothSelected': 'İki taraf da hazır! Maç başlıyor...', 'online.selectTeamBelow': 'Aşağıdan takımını seç:',
    'online.lockedIn': 'ONAYLANDI', 'online.selecting': 'Seçiliyor...', 'online.choosing': 'Milli takım seçiyor...',
    'online.opponentLeft': 'Rakip odadan ayrıldı', 'online.opponentLeftSub': 'Kısa süre içinde menüye dönülüyor...',
    'online.roomCreated': 'ODA OLUŞTURULDU', 'online.room': 'Oda', 'online.host': 'Kurucu', 'online.guest': 'Misafir',
    'online.firstTurn': 'İlk şutu sen çekiyorsun', 'online.secondTurn': 'İlk şutu rakip çekiyor',
    'online.matchStartingIn': 'Maç Başlıyor', 'online.kickoff': 'BAŞLAMA VURUŞU!',
    'online.leaveMatchTitle': 'MAÇTAN AYRIL?', 'online.leaveMatchSub': 'Ayrılmak rakibe hükmen galibiyet kazandıracaktır.',
    'online.leaveMatch': 'MAÇTAN ÇIK', 'online.leave': 'ÇIK', 'online.returnToMenu': 'Menüye Dön',
    'online.returningToMenu': 'Menüye Dönülüyor...', 'online.sessionDisconnected': 'Oturum Kesildi',
    'online.yourCountry': 'SENİN TAKIMIN', 'online.oppCountry': 'RAKİP TAKIM',
    'online.waitingOpponent': 'Rakibin seçimi bekleniyor...', 'online.waitingOpponentCode': 'Arkadaşının kodla girmesi bekleniyor...',
    'online.connectSub': 'Canlı 1v1 çok oyunculu sunucular', 'modal.matchmaking': 'Rakip Aranıyor...',
    'modal.matchmakingDesc': 'Küresel sunucularda rakip aranıyor', 'modal.searchingTime': 'Arama Süresi',
    'modal.opponentFound': 'RAKİP BULUNDU!', 'modal.connectingBot': '30sn içinde bota bağlanacak...',
    'modal.quitMatchSub': 'Mevcut maç ilerlemesi kaydedilmeyecek.', 'modal.forfeitMatchTitle': 'TESLİM OL?',
    'modal.forfeitMatchSub': 'Ayrılmak otomatik yenilgi sayılır.', 'modal.forfeit': 'TESLİM OL',
    'match.opponentLeftTitle': 'RAKİP MAÇTAN AYRILDI', 'match.opponentLeftDesc': 'Rakibinin bağlantısı koptu.',
    'match.playAgainUnavailable': 'Rakip ayrıldığı için tekrar oynanamaz.',
    'match.waitingOpponent': 'Rakibin yanıtı bekleniyor...', 'match.changeTeams': 'TAKIMLARI DEĞİŞTİR',
    'tournament.selectFormat': 'Turnuva formatı seç:', 'tournament.globalCup': 'Küresel Kupa', 'tournament.customCup': 'Özel Kupa',
    'tournament.inDevelopment': 'GELİŞTİRİLİYOR', 'tournament.onlineWorldCup': 'ÇEVRİMİÇİ DÜNYA KUPASI',
    'tournament.multiplayerWorldCup': 'Çok Oyunculu Dünya Kupası & Eleme Ağaçları', 'tournament.knockoutBrackets': '16 Takımlı Eleme Turları',
    'tournament.knockoutBracketsSub': 'Canlı eşleşmeli eleme turnuvaları', 'tournament.globalLeaderboards': 'Küresel Sezon Lider Tablosu',
    'tournament.globalLeaderboardsSub': 'Sıralama puanları ve kupalar kazan', 'tournament.exclusiveUnlockables': 'Özel Şampiyon Formaları ve Toplar',
    'tournament.exclusiveUnlockablesSub': 'Turnuva galiplerine özel ödüller', 'tournament.playOfflineNow': 'ÇEVRİMDIŞI DÜNYA KUPASI OYNA',
    'tournament.selectYourTeam': 'TAKIMINI SEÇ', 'tournament.worldCupQualifiedSub': 'FIFA Dünya Kupası • 40 Katılımcı Ülke (Grup A – J)',
    'tournament.searchCountry': 'Ülke veya grup ara...', 'tournament.qualifiedNations': 'Katılan Ülkeler',
    'tournament.tapToSelect': 'Seçmek İçin Dokun', 'tournament.selected': 'SEÇİLDİ', 'tournament.ovr': 'GÜÇ',
    'tournament.randomGroupDraw': 'Başlangıçta rastgele grup kuraları', 'tournament.tapAnyCountryPrompt': 'TAKIMINI SEÇMEK İÇİN BİR ÜLKEYE DOKUN',
    'tournament.enterWorldCup': 'DÜNYA KUPASINA GİR (GRUP A - J)', 'tournament.backToMenu': 'Menüye Dön',
    'tournament.forfeitMatch': 'MAÇI BIRAK', 'tournament.continue': 'ELEME TURLARINA GEÇ',
    'tournament.championTitle': '★ DÜNYA ŞAMPİYONU ★', 'tournament.worldChampions': 'DÜNYA ŞAMPİYONU',
    'tournament.winnerLiftsCup': 'Dünya Kupasını havaya kaldırdın!', 'tournament.freeKickCup': 'Dünya Serbest Vuruş Turnuvası',
    'tournament.roundOf16': 'Son 16 Turu', 'tournament.quarterFinals': 'Çeyrek Final', 'tournament.semiFinal1': 'Yarı Final 1',
    'tournament.semiFinal2': 'Yarı Final 2', 'tournament.worldFinal': 'Dünya Kupası Finali', 'tournament.awaitingFinal': 'Finalist Bekleniyor',
    'tournament.fixture': 'Eşleşme', 'tournament.ft': 'MS', 'tournament.tbd': 'BELİRLENECEK', 'tournament.cancelTournament': 'Turnuvayı İptal Et',
    'practice.selectDrill': 'Çalışma seç:', 'practice.freeKick': 'SERBEST VURUŞ',
    'practice.freeKickSub': 'Hızlı oyun • Baraj ve köşe vuruşları', 'practice.instant': 'Anında',
    'practice.penalty': 'PENALTI', 'practice.penaltySub': 'Kaleciye karşı 1v1 • Süresiz', 'practice.random': 'Rastgele',
    'practice.exitTitle': 'ANTRENMANDAN ÇIK?', 'practice.exitSub': 'İstediğin zaman ana menüye dönebilirsin.',
    'practice.exitButton': 'ANTRENMANDAN ÇIK', 'survival.title': 'Hayatta Kalma Arenası',
    'survival.subtitle': '3 Can • Sınırsız Seri • Düellolar', 'survival.arenaTitle': 'HAYATTA KALMA ARENASI',
    'survival.onlineSurvivalTitle': 'ÇEVRİMİÇİ 1V1 HAYATTA KALMA',
    'survival.onlineSurvivalSubtitle': '3 Can • Canlı 1v1 Düello • Sonsuz Gol Serisi Mücadelesi',
    'survival.selectGameMode': 'Oyun modunu seç:', 'survival.offlineSurvivalBtn': 'ÇEVRİMDIŞI HAYATTA KALMA',
    'survival.onlineDuelBtn': 'ÇEVRİMİÇİ 1V1 DÜELLO', 'survival.rulesBtn': 'Kurallar',
    'survival.rulesTitle': 'HAYATTA KALMA KURALLARI', 'survival.rulesSubtitle': 'Rekor kırmak için bu 2 kuralı takip et:',
    'survival.rule1Title': '3 Can Sistemi',
    'survival.rule1Desc': 'Her oyuncu 3 kalple başlar. Kaçan şut veya kurtarış 1 can götürür. Canları ilk biten kaybeder!',
    'survival.rule2Title': 'Sırayla Şut & 100sn Zamanlayıcı',
    'survival.rule2Desc': '100 saniye geri sayımlı dönüşümlü serbest vuruşlar. Serini büyütüp kazanmak için gol at!',
    'survival.backToRules': 'Kurallara Dön', 'survival.howItWorks': 'Nasıl çalışır', 'survival.guideBadge': 'HAYATTA KALMA REHBERİ',
    'survival.livesRemaining': 'Kalan Canlar', 'survival.bestRecord': 'Tüm Zamanların Rekoru', 'survival.bestStreak': 'EN İYİ SERİ',
    'survival.startRun': 'Oyunu Başlat', 'survival.personalRecord': 'Kişisel Rekor', 'survival.goalStreak': 'GOL SERİSİ',
    'survival.goalsStreak': 'GOL SERİSİ', 'survival.kicks': 'Şutlar', 'survival.duel': '1V1 HAYATTA KALMA DÜELLOSU',
    'survival.duelSub': 'Çevrimiçi Eleme Maçı', 'survival.runEnded': 'OYUN BİTTİ!',
    'survival.challengeComplete': 'Hayatta Kalma Mücadelesi Tamamlandı', 'survival.finalGoalsStreak': 'Son Gol Serisi',
    'survival.challengeMode': 'Mücadele Modu', 'survival.reviveExtraLife': 'CANLAN (+1 EKSTRA CAN)',
    'survival.endSurvivalTitle': 'HAYATTA KALMAYI BİTİR?', 'survival.endSurvival': 'BİTİR', 'survival.endRun': 'OYUNU SONLANDIR',
    'survival.concludeSub': 'Maç derhal sonlandırılacak.', 'survival.currentStreak': 'Mevcut seri:',
    'wager.title': 'Bahis Arenaları', 'wager.subtitle': 'Bahsini seç • Kazanan tüm altınları alır!',
    'wager.rookie': 'Çaylak Arenası', 'wager.pro': 'Pro Arena', 'wager.champion': 'Şampiyon Arenası', 'wager.legend': 'Efsane Arenası',
    'wager.entryFee': 'Giriş Ücreti', 'wager.entry': 'GİRİŞ', 'wager.prizePot': 'Ödül Havuzu', 'wager.winPot': 'KAZANAN ÖDÜLÜ',
    'wager.highRoller': 'Büyük Bahisli Canlı Düello', 'wager.bottomBanner': 'Arenaları keşfet • Yüksek bahisler, iki katı kazanç!',
    'wager.tapToSelect': 'Seçmek için dokun', 'wager.playWithCoins': 'Altınla oyna', 'wager.needMoreCoins': 'Daha fazla altın lazım',
    'wager.forfeitWager': 'BAHİSTEN ÇEKİL', 'wager.surrenderTitle': 'BAHİSTEN ÇEKİL?',
    'wager.surrenderSub': 'Çekilmek bahsini kaybetmene neden olur:', 'wager.surrender': 'ÇEKİL', 'wager.victory': 'BAHİS ZAFERİ!',
    'wager.coinDuelResults': 'Düello Sonuçları', 'wager.drawRefunded': 'BERABERLİK • ÜCRET İADE EDİLDİ',
    'wager.arenaPot': 'Arena Havuzu', 'wager.netResult': 'Net Kazanç',
    'wager.opponentLeft': 'Rakip arenadan ayrıldı', 'wager.rematch': 'BAHİSLİ RÖVANŞ',
    'targetSmash.title': 'HEDEF VURMA', 'targetSmash.arcadeBadge': 'YENİ ATARİ MODU',
    'targetSmash.trickshotSubtitle': 'Hedefler & Falsolu Vuruşlar', 'targetSmash.selectStage': 'Bölüm (1 - 10)',
    'targetSmash.unlocked': 'Açıldı', 'targetSmash.stage': 'Bölüm', 'targetSmash.objective': 'Hedef',
    'targetSmash.highScore': 'Rekor', 'targetSmash.pts': 'PUAN', 'targetSmash.distance': 'Mesafe',
    'targetSmash.defendersWall': 'Baraj', 'targetSmash.players': 'Oyuncular', 'targetSmash.targetScore': 'Hedef Puan',
    'targetSmash.targetRequired': 'Gereken Puan', 'targetSmash.playStage': 'BÖLÜMÜ OYNA', 'targetSmash.stageLocked': 'BÖLÜM KİLİTLİ',
    'targetSmash.stageCleared': 'BÖLÜM TAMAMLANDI!', 'targetSmash.stageFailed': 'BÖLÜM GEÇİLEMEDİ', 'targetSmash.finalScore': 'Son Puan',
    'targetSmash.coinsReward': 'Altın Ödülü', 'targetSmash.nextStage': 'SONRAKİ BÖLÜM', 'targetSmash.retryStage': 'TEKRAR DENE',
    'targetSmash.exitToSelect': 'BÖLÜMLERE DÖN', 'divisions.title': 'Küme Ligi', 'divisions.titleUpper': 'KÜME LİGİ',
    'divisions.rank': 'Küme Sıralaması', 'divisions.titleTarget': 'Şampiyonluk Hedefi', 'divisions.titleClaimed': 'Şampiyonluk Kazanıldı!',
    'divisions.ptsForTrophy': 'Kupa İçin Gereken Puan', 'divisions.seasonFinished': 'Sezon Bitti',
    'divisions.promotionAchieved': 'Üst Kümeye Çıkıldı!', 'divisions.thisSeason': 'Bu Sezon',
    'divisions.matchesLeft': 'Kalan Maçlar', 'divisions.ptsNeeded': 'Gereken Puan', 'divisions.win': 'Galibiyet',
    'divisions.draw': 'Beraberlik', 'divisions.loss': 'Mağlubiyet', 'divisions.pt': 'P', 'divisions.pts': 'PUAN',
    'divisions.allTime': 'Geçmiş Kayıtlar', 'divisions.matchesHistory': 'Maç Geçmişi', 'divisions.match': 'Maç',
    'divisions.noMatchesYet': 'Bu sezon henüz maç yapılmadı', 'divisions.noMatchesSub': 'Sezonuna aşağıdan başla!',
    'divisions.nextMatchChooseOpponent': 'Sonraki Maç • Rakip Seç', 'divisions.whoDoYouWantToPlay': 'Sonraki rakibini seç:',
    'divisions.teamsAvailable': 'Mevcut Takımlar', 'divisions.searchNationalTeam': 'Milli takım ara...',
    'divisions.playMatchVs': 'MAÇ YAP:', 'divisions.opponent': 'Rakip', 'divisions.opponentUpper': 'RAKİP',
    'divisions.opponentConnected': 'Rakip Bağlandı', 'divisions.change': 'Değiştir', 'divisions.chooseOpponent': 'Rakip Seç',
    'divisions.divShort': 'KÜME', 'divisions.of': '/', 'divisions.continueTo': 'Şuraya Geç:', 'divisions.next': 'İleri',
    'divisions.findingOpponent': 'Küme Rakibi Aranıyor...', 'divisions.matchingWithOnline': 'Kümendeki oyuncularla eşleşiliyor',
    'divisions.searchingActivePlayers': 'Küme sunucularında aranıyor...', 'divisions.matchStartingIn': 'Maç başlıyor',
    'divisions.cancelMatchmaking': 'İptal Et', 'divisions.cancelSearch': 'Aramayı İptal Et', 'divisions.wdl': 'G-B-M',
    'division.return': 'Kümeler Menüsüne Dön', 'division.reward': 'Küme Ödülü', 'result.victory': 'GALİBİYET!',
    'result.defeat': 'MAĞLUBİYET', 'result.draw': 'BERABERLİK', 'result.champion': 'DÜNYA ŞAMPİYONU!', 'result.prizeWon': 'Kazanılan Ödül',
    'result.streak': 'Mevcut Seri', 'result.newRecord': 'YENİ REKOR!', 'result.coinsEarned': 'Kazanılan Altın',
    'result.finalScore': 'Maç Sonucu', 'result.totalScore': 'Toplam Puan', 'result.wonOnPenalties': 'PENALTILARLA KAZANDIN',
    'result.lostOnPenalties': 'PENALTILARLA KAYBETTİN', 'result.survivalVictory': 'HAYATTA KALMA ZAFERİ!',
    'result.survivalDefeat': 'ELENDİN', 'result.wagerResults': 'Bahis Sonuçları',
    'rematch.invitationTitle': 'Rövanş İstendi', 'rematch.invitationDesc': 'Rakip tekrar oynamak istiyor!',
    'rematch.accept': 'Rövanşı Kabul Et', 'rematch.decline': 'Reddet', 'rematch.starting': 'Rövanş Başlatılıyor...',
    'rematch.survivalRequested': 'Rakip Hayatta Kalma Rövanşı İstedi!',
    'rematch.survivalDesc': 'Hemen 1v1 Düelloya dönmek için kabul et!',
    'rematch.wagerChallenge': 'seni Bahisli Rövanşa davet ediyor!', 'stats.goals': 'Goller', 'stats.shots': 'Şutlar',
    'status.live': 'CANLI', 'status.offline': 'ÇEVRİMDIŞI', 'status.winner': 'KAZANAN', 'status.eliminated': 'ELENDİ',
    'status.survived': 'HAYATTA KALDI', 'status.left': 'AYRILDI', 'status.disconnected': 'BAĞLANTI KOPTU',
    'store.title': 'Ekipman Mağazası', 'store.subtitle': '3D TOP KAPLAMALARI VE ÇİM DESENLERİ',
    'store.balls': 'Toplar', 'store.pitches': 'Çimler', 'store.ballStore': 'TOP MAĞAZASI',
    'store.ballStoreDesc': '3D Kaplamalar & Pro Modeller', 'store.pitchStore': 'STADYUM MAĞAZASI',
    'store.pitchStoreDesc': 'Stadyum Çim Kesim Desenleri', 'store.selectCategory': 'KATEGORİ SEÇ',
    'store.unlockedAndEquipped': 'AÇILDI VE KUŞANILDI', 'store.owned': 'Sahip Olundu', 'store.buyFor': 'Satın Al:',
    'store.notEnoughCoins': 'YETERSİZ ALTIN!', 'store.needMore': 'GEREKEN', 'store.more': 'DAHA',
    'profile.title': 'Oyuncu Profili', 'profile.cloudStorageNotice': 'CRAZYGAMES BULUT VE YEREL KAYIT',
    'replays.subtitle': 'Kayıtlı en iyi gollerini izle ve yönet', 'replays.savedReplays': 'KAYITLI TEKRARLAR',
    'replays.savedHighlights': 'KAYITLI ÖNEMLİ ANLAR', 'replays.clips': 'Videolar', 'replays.savedClips': 'Kayıtlı Klipler',
    'replays.noSavedReplays': 'HENÜZ KAYITLI TEKRAR YOK', 'replays.noHighlightsTitle': 'KAYITLI AN YOK',
    'replays.noHighlightsDesc': 'Bir maçta gol at ve tekrar sırasında KAYDET butonuna bas!',
    'replays.playMatchNow': 'ŞİMDİ MAÇ OYNA', 'replays.emptyInstructions': 'Gol at ve tekrar ekranında sağ üstteki KAYDET tuşuna dokun!',
    'replays.savedHighlight': 'KAYITLI AN', 'replays.savedDate': 'TARİH', 'replays.shotDistance': 'ŞUT MESAFESİ',
    'replays.longestStrike': 'En Uzak Şut', 'replays.goalHighlights': 'Gol Anları', 'replays.watchReplay': 'TEKRARI İZLE',
    'replays.exitReplay': 'TEKRARDAN ÇIK', 'replays.deleteReplay': 'Tekrarı Sil', 'replays.confirmDelete': 'Bu kaydı silmek istiyor musunuz?',
    'replays.deleteAllConfirm': 'TÜM TEKRARLARI SİL?', 'replays.deleteAllDesc': 'Tüm kayıtları silmek istediğinizden emin misiniz?',
    'ads.videoReward': 'VİDEO ÖDÜLÜ', 'ads.coinsReward': 'ALTIN ÖDÜLÜ', 'ads.watchToEarn': '+50 altın kazanmak için video reklam izle',
    'ads.instantBoost': 'Anında Altın Takviyesi', 'ads.integrationFinalizing': 'Reklam entegrasyonu tamamlanıyor.',
    'ads.unlockAllItems': '50 top kaplamasını ve 50 stadyum çimini aç!', 'ads.loading': 'REKLAM YÜKLENİYOR...',
    'lang.title': 'Dil Ayarları', 'lang.subtitle': 'Tercih ettiğin dili seç (16 dil desteklenir)',
    'lang.autoDetect': 'Otomatik Tespit Edilen Dil', 'lang.currentlyActive': 'ŞU ANDA AKTİF',
    'lang.sdkSyncTitle': 'CrazyGames Senkronizasyonu', 'lang.sdkSyncDesc': 'Oyun dili CrazyGames portalınızla otomatik senkronize olur',
    'lang.searchPlaceholder': 'Dil veya ülke ara...', 'lang.tabAll': 'Tümü (16)', 'lang.tabPopular': 'Popüler',
    'lang.tabEurope': 'Avrupa', 'lang.tabAmericas': 'Amerika', 'lang.tabAsiaMe': 'Asya & OD',
    'lang.noMatches': 'Eşleşen dil bulunamadı', 'lang.noMatchesDesc': 'Başka bir dil veya ülke adı deneyin',
    'lang.resetFilters': 'Filtreleri Sıfırla'
}

print("RU and TR loaded.")
